// Auto-genererad filmdata (handlingar, citat, karaktärer, skådespelare)
export const film = {
    'Handlingar': [
      { title: 'The Shawshank Redemption', definition: 'En oskyldigt dömd man bygger ett nytt liv och en livslång vänskap i fängelset.', difficulty: 'medel' },
      { title: 'Moonlight', definition: 'En ung man växer upp genom tre faser av livet medan han kämpar med identitet, kärlek och tystnad.', difficulty: 'medel' },
      { title: 'Harakiri', definition: 'En samuraj söker rättvisa och avslöjar hyckleri och brutalitet i ett feodalt system.', difficulty: 'medel' },
      { title: 'Limitless', definition: 'En författare får tillgång till en drog som gör honom extremt intelligent och förändrar hans liv.', difficulty: 'medel' },
      { title: 'Interstellar', definition: 'En grupp astronauter reser genom rymden för att hitta en ny framtid för mänskligheten.', difficulty: 'medel' },
      { title: 'The Death of Stalin', definition: 'Efter Stalins död utbryter kaos, maktspel och paranoia bland Sovjets ledare.', difficulty: 'medel' },
      { title: 'Doctor Glas', definition: 'En läkare blir indragen i ett moraliskt dilemma när han försöker hjälpa en kvinna i ett olyckligt äktenskap.', difficulty: 'medel' },
      { title: 'Two Prosecutors', definition: 'En idealistisk åklagare försöker navigera ett korrupt och farligt rättssystem.', difficulty: 'medel' },
      { title: 'GoodFellas', definition: 'En ung man dras in i maffians värld och får uppleva både makt och förfall.', difficulty: 'medel' },
      { title: 'Snatch', definition: 'Kriminella, boxare och bedragare kolliderar i en kaotisk jakt på en enorm diamant.', difficulty: 'medel' },
      { title: 'A Different Man', definition: 'En man genomgår en drastisk förändring i utseende och börjar ifrågasätta identitet och självbild.', difficulty: 'medel' },
      { title: 'The Lord of the Rings: The Fellowship of the Ring', definition: 'En hobbit får i uppdrag att förstöra en mäktig ring innan mörkret tar över världen.', difficulty: 'medel' },
      { title: '1917', definition: 'Två soldater måste korsa ett krigsfält för att leverera en avgörande order i tid.', difficulty: 'medel' },
      { title: 'Hamnet', definition: 'En känslomässig berättelse inspirerad av familj, sorg och skapandets ursprung.', difficulty: 'medel' },
      { title: 'Inglourious Basterds', definition: 'Under andra världskriget planerar en grupp soldater och en biografägare hämnd mot nazisterna.', difficulty: 'medel' },
      { title: 'First Cow', definition: 'Två män bygger ett litet partnerskap kring mjölk, överlevnad och drömmar i vilda västern.', difficulty: 'medel' },
      { title: 'Holy Spider', definition: 'En journalist utreder en mördare som riktar in sig på kvinnor och avslöjar ett mörkt samhällsklimat.', difficulty: 'medel' },
      { title: 'Inside Man', definition: 'En smart bankrånare och en förhandlare hamnar i ett intrikat psykologiskt spel.', difficulty: 'medel' },
      { title: 'Society of the Snow', definition: 'Överlevande från en flygkrasch måste samarbeta i extrem kyla för att hålla sig vid liv.', difficulty: 'medel' },
      { title: 'Nocturnal Animals', definition: 'En kvinna konfronteras med en mörk roman som speglar ett gammalt förhållande och förlorade val.', difficulty: 'medel' },
      { title: 'Shogun', definition: 'En brittisk sjöman hamnar i feodalt Japan och dras in i politiska och kulturella konflikter.', difficulty: 'medel' },
      { title: 'A Fish Called Wanda', definition: 'Ett gäng brottslingar, lögner och svartsjuka leder till kaos i en brittisk komedi.', difficulty: 'medel' },
      { title: 'The Basketball Diaries', definition: 'En lovande ung idrottare faller in i missbruk och självdestruktion.', difficulty: 'medel' },
      { title: 'The Fighter', definition: 'En boxare försöker nå framgång medan familj, lojalitet och missbruk drar honom åt olika håll.', difficulty: 'medel' },
      { title: 'The Dirt', definition: 'Ett glamoröst men kaotiskt porträtt av ett rockband fyllt av excess, konflikter och fame.', difficulty: 'medel' },
      { title: 'Hereditary', definition: 'En familj drabbas av sorg och ett växande mörker som avslöjar något demoniskt.', difficulty: 'medel' },
      { title: 'Mississippi Burning', definition: 'Två FBI-agenter utreder medborgarrättsmord i ett våldsamt och rasistiskt samhälle.', difficulty: 'medel' },
      { title: 'War Dogs', definition: 'Två unga män blir vapenhandlare och hamnar i en farlig värld av pengar och lögner.', difficulty: 'medel' },
      { title: 'All of Us Are Dead', definition: 'Ett zombieutbrott i en skola tvingar elever att kämpa för överlevnad.', difficulty: 'medel' },
      { title: 'Project Hail Mary', definition: 'En ensam forskare vaknar upp i rymden och måste rädda jorden med hjälp av vetenskap och oväntad vänskap.', difficulty: 'medel' },
      { title: 'The Goonies', definition: 'En grupp barn letar efter en piratskatt för att rädda sina hem.', difficulty: 'medel' },
      { title: 'Come and See', definition: 'En ung pojke upplever krigets fasor och förlorar oskulden i en av filmhistoriens mörkaste skildringar.', difficulty: 'medel' },
      { title: 'Entergalactic', definition: 'En konstnär navigerar kärlek, vänskap och ambition i New Yorks kreativa nattliv.', difficulty: 'medel' },
      { title: 'Moana', definition: 'En ung kvinna ger sig ut över havet för att rädda sitt folk och upptäcka sin identitet.', difficulty: 'medel' },
      { title: 'Captain Marvel', definition: 'En flygpilot får tillbaka sitt förflutna och upptäcker sin plats i ett interstellärt krig.', difficulty: 'medel' },
      { title: 'The Hateful Eight', definition: 'Åtta misstänksamma främlingar fastnar i en snöstorm och avslöjar sina mörka motiv.', difficulty: 'medel' },
      { title: 'The Terminator', definition: 'En cyborg skickas från framtiden för att döda en kvinna som kan förändra mänsklighetens öde.', difficulty: 'medel' },
      { title: 'Despicable Me', definition: 'En före detta superskurk får sitt liv vänt upp och ner när tre flickor kommer in i hans värld.', difficulty: 'medel' },
      { title: 'Dunkirk', definition: 'Soldater, civila och piloter kämpar för överlevnad under evakueringen från Dunkerque.', difficulty: 'medel' },
      { title: 'Home Alone', definition: 'En pojke lämnas ensam hemma och försvarar huset mot två klantiga tjuvar.', difficulty: 'medel' },
      { title: 'The Boy in the Striped Pyjamas', definition: 'En pojke blir vän med en fånge utanför ett koncentrationsläger och förstår inte det verkliga sammanhanget.', difficulty: 'medel' },
      { title: 'Doctor Strange', definition: 'En arrogant kirurg lär sig magi och måste skydda världen från kosmiska hot.', difficulty: 'medel' },
      { title: 'Skyfall', definition: 'James Bond tvingas konfrontera sitt förflutna och skydda MI6 från en farlig fiende.', difficulty: 'medel' },
      { title: 'Tenet', definition: 'En agent använder tidsvändning för att stoppa en katastrof som hotar världen.', difficulty: 'medel' },
      { title: 'John Wick', definition: 'En pensionerad lönnmördare ger sig ut på en våldsam hämndresa efter en personlig tragedi.', difficulty: 'medel' },
      { title: 'Saving Private Ryan', definition: 'En grupp soldater skickas bakom fiendens linjer för att hitta en saknad soldat under andra världskriget.', difficulty: 'medel' },
      { title: 'The Pianist', definition: 'En pianist försöker överleva Förintelsen medan Warszawa faller samman runt honom.', difficulty: 'medel' },
      { title: 'Train to Busan', definition: 'Passagerare på ett tåg kämpar för överlevnad när ett zombieutbrott sprider sig genom Korea.', difficulty: 'medel' },
      { title: 'Hacksaw Ridge', definition: 'En soldat vägrar bära vapen men räddar liv som medic på slagfältet.', difficulty: 'medel' },
      { title: 'Anatomy of a Fall', definition: 'En författare anklagas efter ett dödsfall och ett äktenskap dissekeras i rättssal.', difficulty: 'medel' },
      { title: 'Coach Carter', definition: 'En basketcoach ställer hårda krav på sina spelare för att få dem att lyckas både på och utanför planen.', difficulty: 'medel' },
      { title: 'Godzilla Minus One', definition: 'En traumatisk efterkrigshistoria följer människor som försöker överleva samtidigt som ett monster hotar Japan.', difficulty: 'medel' },
      { title: 'War of the Worlds', definition: 'En vanlig man måste skydda sin familj när jorden invaderas av utomjordiska maskiner.', difficulty: 'medel' },
      { title: 'Mission: Impossible', definition: 'En agent blir falskt anklagad och måste avslöja en förrädare i en högteknologisk spionthriller.', difficulty: 'medel' },
      { title: 'Jarhead', definition: 'En marinsoldat upplever krigets monotoni, frustration och psykologiska tryck under Gulfkriget.', difficulty: 'medel' },
      { title: 'A Fistful of Dollars', definition: 'En vandrande revolverman manipulerar två rivaliserande gäng i en våldsam gränsstad.', difficulty: 'medel' },
      { title: 'Die Hard', definition: 'En ensam polis måste rädda gisslan i en skyskrapa under ett brutalt julaftonsdrama.', difficulty: 'medel' },
      { title: 'Indiana Jones and the Temple of Doom', definition: 'Indiana Jones kastas in i ett mörkt äventyr som handlar om kult, skatter och räddningsaktioner.', difficulty: 'medel' },
      { title: 'Pixels', definition: 'Videospelsfigurer blir verkliga och en grupp udda hjältar måste rädda världen.', difficulty: 'medel' },
      { title: 'Black Panther: Wakanda Forever', definition: 'Wakanda sörjer sin kung och försöker skydda sin framtid från nya hot.', difficulty: 'medel' },
      { title: 'World War Z', definition: 'En före detta FN-utredare reser världen runt för att stoppa en zombiepandemi.', difficulty: 'medel' },
      { title: 'Chernobyl', definition: 'En katastrofal reaktorolycka leder till en kamp om sanning, ansvar och överlevnad.', difficulty: 'medel' },
      { title: 'Pacific Rim', definition: 'Människor styr enorma robotar för att bekämpa monster som stiger upp ur havet.', difficulty: 'medel' },
      { title: 'I Am Legend', definition: 'En ensam man överlever i ett öde New York medan han försöker hitta botemedel och mening.', difficulty: 'medel' },
      { title: 'Shang-Chi and the Legend of the Ten Rings', definition: 'En man konfronterar sin familjs förflutna och kämpar mot sin fars organisation.', difficulty: 'medel' },
      { title: 'Back to the Future Part II', definition: 'Marty och Doc reser till framtiden för att reparera tidslinjen men skapar nya problem.', difficulty: 'medel' },
      { title: 'Men in Black', definition: 'Två agenter skyddar jorden från utomjordiska hot i hemlighet.', difficulty: 'medel' },
      { title: 'Rocky', definition: 'En underskattad boxare får chansen att slåss om titeln och bevisa sitt värde.', difficulty: 'medel' },
      { title: 'Terminator 2: Judgment Day', definition: 'En robot från framtiden måste skydda en pojke som kan avgöra mänsklighetens öde.', difficulty: 'medel' },
      { title: 'Fury', definition: 'En stridshärdad stridsvagnsbesättning kämpar sig genom krigets brutalitet mot slutet av andra världskriget.', difficulty: 'medel' },
      { title: 'The Sound of Music', definition: 'En kvinna förändrar en familjs liv genom musik, kärlek och mod inför krigshot.', difficulty: 'medel' },
      { title: 'Raiders of the Lost Ark', definition: 'Indiana Jones söker arken innan nazisterna får tag på dess kraft.', difficulty: 'medel' },
      { title: 'Saw', definition: 'Två män vaknar fastkedjade i ett rum och måste lösa brutala gåtor för att överleva.', difficulty: 'medel' },
      { title: 'Ocean\'s Eleven', definition: 'En grupp skickliga tjuvar planerar ett sofistikerat kasino-rån i Las Vegas.', difficulty: 'medel' },
      { title: 'Rush Hour', definition: 'Två mycket olika poliser tvingas samarbeta för att rädda en kidnappad flicka.', difficulty: 'medel' },
      { title: 'Civil War', definition: 'Under ett framtida inbördeskrig reser journalister genom ett splittrat USA.', difficulty: 'medel' },
    ],
    'Citat': [
      { title: 'The Shawshank Redemption', definition: '"Get busy living, or get busy dying."', difficulty: 'lätt' },
      { title: 'Moonlight', definition: '"In moonlight, black boys look blue."', difficulty: 'lätt' },
      { title: 'Harakiri', definition: '"Honorable men are a lot of nonsense."', difficulty: 'lätt' },
      { title: 'Limitless', definition: '"This is your life on NZT."', difficulty: 'lätt' },
      { title: 'Interstellar', definition: '"Love is the one thing that transcends time and space."', difficulty: 'lätt' },
      { title: 'The Death of Stalin', definition: '"What is a committee? A committee is a suicide pact."', difficulty: 'lätt' },
      { title: 'Doctor Glas', definition: '"A human life is a labyrinth of secrets."', difficulty: 'lätt' },
      { title: 'Two Prosecutors', definition: '"Justice is only real when it survives power."', difficulty: 'lätt' },
      { title: 'GoodFellas', definition: '"As far back as I can remember, I always wanted to be a gangster."', difficulty: 'lätt' },
      { title: 'Snatch', definition: '"Do you know what nemesis means?"', difficulty: 'lätt' },
      { title: 'A Different Man', definition: '"Who are you when the mask is gone?"', difficulty: 'lätt' },
      { title: 'The Lord of the Rings: The Fellowship of the Ring', definition: '"One does not simply walk into Mordor."', difficulty: 'lätt' },
      { title: '1917', definition: '"This is not a game."', difficulty: 'lätt' },
      { title: 'Hamnet', definition: '"Grief is the price of love."', difficulty: 'lätt' },
      { title: 'Inglourious Basterds', definition: '"This is a bingo!"', difficulty: 'lätt' },
      { title: 'First Cow', definition: '"Friendship is a kind of survival."', difficulty: 'lätt' },
      { title: 'Holy Spider', definition: '"The city is full of hidden violence."', difficulty: 'lätt' },
      { title: 'Inside Man', definition: '"It\'s a perfect robbery."', difficulty: 'lätt' },
      { title: 'Society of the Snow', definition: '"We are still here."', difficulty: 'lätt' },
      { title: 'Nocturnal Animals', definition: '"You don\'t know what a man is capable of until he\'s hurt."', difficulty: 'lätt' },
      { title: 'Shogun', definition: '"A different world demands a different self."', difficulty: 'lätt' },
      { title: 'A Fish Called Wanda', definition: '"Don\'t call me stupid."', difficulty: 'lätt' },
      { title: 'The Basketball Diaries', definition: '"This is a diary of a teenager\'s descent."', difficulty: 'lätt' },
      { title: 'The Fighter', definition: '"It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving."', difficulty: 'lätt' },
      { title: 'The Dirt', definition: '"Sex, drugs, and rock and roll."', difficulty: 'lätt' },
      { title: 'Hereditary', definition: '"We suffer what our family suffers."', difficulty: 'lätt' },
      { title: 'Mississippi Burning', definition: '"The law is coming."', difficulty: 'lätt' },
      { title: 'War Dogs', definition: '"There\'s always a deal to be made."', difficulty: 'lätt' },
      { title: 'All of Us Are Dead', definition: '"Survive together."', difficulty: 'lätt' },
      { title: 'Project Hail Mary', definition: '"Science is the answer."', difficulty: 'lätt' },
      { title: 'The Goonies', definition: '"Goonies never say die!"', difficulty: 'lätt' },
      { title: 'Come and See', definition: '"War changes everything."', difficulty: 'lätt' },
      { title: 'Entergalactic', definition: '"Fall in love with the moment."', difficulty: 'lätt' },
      { title: 'Moana', definition: '"The ocean chose you."', difficulty: 'lätt' },
      { title: 'Captain Marvel', definition: '"Higher, further, faster, baby."', difficulty: 'lätt' },
      { title: 'The Hateful Eight', definition: '"There ain\'t no bigger crime than not turning the wagon around."', difficulty: 'lätt' },
      { title: 'The Terminator', definition: '"I\'ll be back."', difficulty: 'lätt' },
      { title: 'Despicable Me', definition: '"It\'s so fluffy!"', difficulty: 'lätt' },
      { title: 'Dunkirk', definition: '"Home."', difficulty: 'lätt' },
      { title: 'Home Alone', definition: '"Keep the change, ya filthy animal!"', difficulty: 'lätt' },
      { title: 'The Boy in the Striped Pyjamas', definition: '"Some things are better left unseen."', difficulty: 'lätt' },
      { title: 'Doctor Strange', definition: '"Dormammu, I\'ve come to bargain."', difficulty: 'lätt' },
      { title: 'Skyfall', definition: '"For England, James?"', difficulty: 'lätt' },
      { title: 'Tenet', definition: '"Don\'t try to understand it. Feel it."', difficulty: 'lätt' },
      { title: 'John Wick', definition: '"Yeah, I\'m thinking I\'m back."', difficulty: 'lätt' },
      { title: 'Saving Private Ryan', definition: '"Earn this."', difficulty: 'lätt' },
      { title: 'The Pianist', definition: '"I can play."', difficulty: 'lätt' },
      { title: 'Train to Busan', definition: '"Don\'t open that door!"', difficulty: 'lätt' },
      { title: 'Hacksaw Ridge', definition: '"Lord, please help me get one more."', difficulty: 'lätt' },
      { title: 'Anatomy of a Fall', definition: '"The truth is a matter of perspective."', difficulty: 'lätt' },
      { title: 'Coach Carter', definition: '"Our deepest fear is that we are powerful beyond measure."', difficulty: 'lätt' },
      { title: 'Godzilla Minus One', definition: '"We have to live."', difficulty: 'lätt' },
      { title: 'War of the Worlds', definition: '"This is not a war any of us started."', difficulty: 'lätt' },
      { title: 'Mission: Impossible', definition: '"Your mission, should you choose to accept it..."', difficulty: 'lätt' },
      { title: 'Jarhead', definition: '"Welcome to the suck."', difficulty: 'lätt' },
      { title: 'A Fistful of Dollars', definition: '"My mistake. Four coffins."', difficulty: 'lätt' },
      { title: 'Die Hard', definition: '"Yippee-ki-yay."', difficulty: 'lätt' },
      { title: 'Indiana Jones and the Temple of Doom', definition: '"Fortune and glory, kid."', difficulty: 'lätt' },
      { title: 'Pixels', definition: '"Game on."', difficulty: 'lätt' },
      { title: 'Black Panther: Wakanda Forever', definition: '"Show them who we are."', difficulty: 'lätt' },
      { title: 'World War Z', definition: '"Be safe. Be strong. Be human."', difficulty: 'lätt' },
      { title: 'Chernobyl', definition: '"What is the cost of lies?"', difficulty: 'lätt' },
      { title: 'Pacific Rim', definition: '"Today, we are cancelling the apocalypse."', difficulty: 'lätt' },
      { title: 'I Am Legend', definition: '"I can save everybody."', difficulty: 'lätt' },
      { title: 'Shang-Chi and the Legend of the Ten Rings', definition: '"You are a product of all who came before you."', difficulty: 'lätt' },
      { title: 'Back to the Future Part II', definition: '"Great Scott!"', difficulty: 'lätt' },
      { title: 'Men in Black', definition: '"The universe is big, but you don\'t have to be."', difficulty: 'lätt' },
      { title: 'Rocky', definition: '"Yo, Adrian!"', difficulty: 'lätt' },
      { title: 'Terminator 2: Judgment Day', definition: '"Hasta la vista, baby."', difficulty: 'lätt' },
      { title: 'Fury', definition: '"Ideals are peaceful. History is violent."', difficulty: 'lätt' },
      { title: 'The Sound of Music', definition: '"The hills are alive with the sound of music."', difficulty: 'lätt' },
      { title: 'Raiders of the Lost Ark', definition: '"Snakes. Why did it have to be snakes?"', difficulty: 'lätt' },
      { title: 'Saw', definition: '"Game over."', difficulty: 'lätt' },
      { title: 'Ocean\'s Eleven', definition: '"You gonna do something or stand there and bleed?"', difficulty: 'lätt' },
      { title: 'Rush Hour', definition: '"Do you understand the words coming out of my mouth?"', difficulty: 'lätt' },
      { title: 'Civil War', definition: '"Stay alive."', difficulty: 'lätt' },
    ],
    'Karaktärer': [
      { title: 'The Shawshank Redemption', definition: 'Andy Dufresne, Red, Warden Norton, Brooks Hatlen, Captain Hadley', difficulty: 'lätt' },
      { title: 'Moonlight', definition: 'Chiron, Paula, Juan, Kevin, Teresa', difficulty: 'lätt' },
      { title: 'Harakiri', definition: 'Hanshiro Tsugumo, Motome Chijiiwa, Saito, Hikokuro, Ii', difficulty: 'lätt' },
      { title: 'Limitless', definition: 'Eddie Morra, Vernon, Lindy, Carl Van Loon, Melissa', difficulty: 'lätt' },
      { title: 'Interstellar', definition: 'Cooper, Murph, Brand, Dr. Mann, TARS', difficulty: 'lätt' },
      { title: 'The Death of Stalin', definition: 'Nikita Khrushchev, Lavrentiy Beria, Georgy Malenkov, Vasily Stalin, Molotov', difficulty: 'lätt' },
      { title: 'Doctor Glas', definition: 'Doctor Glas, Helga Gregorius, Pastor Gregorius, Markel, Mrs. Glas', difficulty: 'lätt' },
      { title: 'Two Prosecutors', definition: 'Alexander Kornyev, prison officials, party agents, family members, local authorities', difficulty: 'lätt' },
      { title: 'GoodFellas', definition: 'Henry Hill, Jimmy Conway, Tommy DeVito, Karen Hill, Paulie Cicero', difficulty: 'lätt' },
      { title: 'Snatch', definition: 'Turkish, Tommy, Brick Top, Mickey O\'Neil, Franky Four Fingers', difficulty: 'lätt' },
      { title: 'A Different Man', definition: 'Edward, Ingrid, Oswald, Guy, Rebecca', difficulty: 'lätt' },
      { title: 'The Lord of the Rings: The Fellowship of the Ring', definition: 'Frodo, Sam, Gandalf, Aragorn, Boromir', difficulty: 'lätt' },
      { title: '1917', definition: 'Schofield, Blake, Lieutenant Blake, Colonel Mackenzie, Blake\'s brother', difficulty: 'lätt' },
      { title: 'Hamnet', definition: 'Agnes, William, Hamnet, Judith, Susanna', difficulty: 'lätt' },
      { title: 'Inglourious Basterds', definition: 'Shosanna, Aldo Raine, Hans Landa, Bridget von Hammersmark, Hugo Stiglitz', difficulty: 'lätt' },
      { title: 'First Cow', definition: 'Cookie, King-Lu, Chief Factor, local trappers, the cow owner', difficulty: 'lätt' },
      { title: 'Holy Spider', definition: 'Rahimi, Saeed Hanaei, journalist network, police investigators, victims\' families', difficulty: 'lätt' },
      { title: 'Inside Man', definition: 'Detective Frazier, Dalton Russell, Madeleine White, Captain John Darius, Bank Chairman', difficulty: 'lätt' },
      { title: 'Society of the Snow', definition: 'Numa, Canessa, Paez, Roberto, Antonio', difficulty: 'lätt' },
      { title: 'Nocturnal Animals', definition: 'Susan, Edward, Tony, Helen, Bobby Andes', difficulty: 'lätt' },
      { title: 'Shogun', definition: 'John Blackthorne, Lord Toranaga, Lady Mariko, Ishido, Yabushige', difficulty: 'lätt' },
      { title: 'A Fish Called Wanda', definition: 'Wanda, Archie Leach, Otto, Ken, George', difficulty: 'lätt' },
      { title: 'The Basketball Diaries', definition: 'Jim Carroll, Mickey, Neutron, Pedro, Reggie', difficulty: 'lätt' },
      { title: 'The Fighter', definition: 'Micky Ward, Dicky Eklund, Charlene Fleming, Alice Ward, Arthur', difficulty: 'lätt' },
      { title: 'The Dirt', definition: 'Vince Neil, Nikki Sixx, Tommy Lee, Mick Mars, Pamela', difficulty: 'lätt' },
      { title: 'Hereditary', definition: 'Annie, Peter, Charlie, Steve, Joan', difficulty: 'lätt' },
      { title: 'Mississippi Burning', definition: 'Agent Ward, Agent Anderson, Deputy Pell, Mrs. Pell, Klansmen', difficulty: 'lätt' },
      { title: 'War Dogs', definition: 'Efraim, David, Iz, Henry, Marlboro', difficulty: 'lätt' },
      { title: 'All of Us Are Dead', definition: 'Nam On-jo, Lee Cheong-san, Yoon Gwi-nam, Lee Su-hyeok, Choi Nam-ra', difficulty: 'lätt' },
      { title: 'Project Hail Mary', definition: 'Ryland Grace, Rocky, Eva Stratt, Yao, Dmitri', difficulty: 'lätt' },
      { title: 'The Goonies', definition: 'Mikey, Mouth, Data, Chunk, Brand', difficulty: 'lätt' },
      { title: 'Come and See', definition: 'Florya, Glasha, the partisans, German officers, villagers', difficulty: 'lätt' },
      { title: 'Entergalactic', definition: 'Jabari, Meadow, Karina, Jimmy, Lenox', difficulty: 'lätt' },
      { title: 'Moana', definition: 'Moana, Maui, Tala, Chief Tui, Te Fiti', difficulty: 'lätt' },
      { title: 'Captain Marvel', definition: 'Carol Danvers, Nick Fury, Talos, Maria Rambeau, Yon-Rogg', difficulty: 'lätt' },
      { title: 'The Hateful Eight', definition: 'John Ruth, Daisy Domergue, Major Warren, Chris Mannix, Oswaldo Mobray', difficulty: 'lätt' },
      { title: 'The Terminator', definition: 'Sarah Connor, The Terminator, Kyle Reese, Detective Vukovich, Ginger', difficulty: 'lätt' },
      { title: 'Despicable Me', definition: 'Gru, Margo, Edith, Agnes, Dr. Nefario', difficulty: 'lätt' },
      { title: 'Dunkirk', definition: 'Tommy, Farrier, Dawson, Alex, Collins', difficulty: 'lätt' },
      { title: 'Home Alone', definition: 'Kevin, Harry, Marv, Kate, Peter', difficulty: 'lätt' },
      { title: 'The Boy in the Striped Pyjamas', definition: 'Bruno, Shmuel, Father, Mother, Gretel', difficulty: 'lätt' },
      { title: 'Doctor Strange', definition: 'Stephen Strange, Wong, Ancient One, Mordo, Christine Palmer', difficulty: 'lätt' },
      { title: 'Skyfall', definition: 'James Bond, M, Silva, Q, Eve Moneypenny', difficulty: 'lätt' },
      { title: 'Tenet', definition: 'The Protagonist, Neil, Kat, Andrei Sator, Priya', difficulty: 'lätt' },
      { title: 'John Wick', definition: 'John Wick, Viggo Tarasov, Winston, Marcus, Daisy', difficulty: 'lätt' },
      { title: 'Saving Private Ryan', definition: 'Captain Miller, Private Ryan, Sergeant Horvath, Private Jackson, Private Reiben', difficulty: 'lätt' },
      { title: 'The Pianist', definition: 'Wladyslaw Szpilman, Dorota, Captain Hosenfeld, Szpilman\'s family, Jurek', difficulty: 'lätt' },
      { title: 'Train to Busan', definition: 'Seok-woo, Su-an, Sang-hwa, Seong-kyeong, Yong-guk', difficulty: 'lätt' },
      { title: 'Hacksaw Ridge', definition: 'Desmond Doss, Dorothy, Smitty, Captain Glover, Sergeant Howell', difficulty: 'lätt' },
      { title: 'Anatomy of a Fall', definition: 'Sandra, Samuel, Daniel, the judge, the lawyer', difficulty: 'lätt' },
      { title: 'Coach Carter', definition: 'Ken Carter, Timo Cruz, Kenyon Stone, Damien Carter, Junior Battle', difficulty: 'lätt' },
      { title: 'Godzilla Minus One', definition: 'Koichi Shikishima, Noriko Oishi, Akiko, Captain Tachibana, Sumiko Ota', difficulty: 'lätt' },
      { title: 'War of the Worlds', definition: 'Ray Ferrier, Rachel Ferrier, Robbie Ferrier, Harlan Ogilvy, Mary Ann', difficulty: 'lätt' },
      { title: 'Mission: Impossible', definition: 'Ethan Hunt, Jim Phelps, Claire Phelps, Luther Stickell, Franz Krieger', difficulty: 'lätt' },
      { title: 'Jarhead', definition: 'Anthony Swofford, Troy, Peter, Fergus, Major Schumann', difficulty: 'lätt' },
      { title: 'A Fistful of Dollars', definition: 'Joe, Ramon Rojo, Esteban Rojo, Marisol, Silvanito', difficulty: 'lätt' },
      { title: 'Die Hard', definition: 'John McClane, Hans Gruber, Holly Gennaro, Al Powell, Karl', difficulty: 'lätt' },
      { title: 'Indiana Jones and the Temple of Doom', definition: 'Indiana Jones, Short Round, Willie Scott, Mola Ram, Chattar Lal', difficulty: 'lätt' },
      { title: 'Pixels', definition: 'Sam Brenner, Cooper, Ludlow, President Cooper, Q*bert', difficulty: 'lätt' },
      { title: 'Black Panther: Wakanda Forever', definition: 'Shuri, Ramonda, Nakia, Okoye, Namor', difficulty: 'lätt' },
      { title: 'World War Z', definition: 'Gerry Lane, Karin Lane, Rachel Lane, Thierry Umutoni, Seger', difficulty: 'lätt' },
      { title: 'Chernobyl', definition: 'Valery Legasov, Boris Shcherbina, Ulana Khomyuk, Anatoly Dyatlov, Lyudmilla Ignatenko', difficulty: 'lätt' },
      { title: 'Pacific Rim', definition: 'Raleigh Becket, Mako Mori, Stacker Pentecost, Newton Geiszler, Hermann Gottlieb', difficulty: 'lätt' },
      { title: 'I Am Legend', definition: 'Robert Neville, Sam, Anna, Ethan, infected humans', difficulty: 'lätt' },
      { title: 'Shang-Chi and the Legend of the Ten Rings', definition: 'Shang-Chi, Katy, Wenwu, Xialing, Morris', difficulty: 'lätt' },
      { title: 'Back to the Future Part II', definition: 'Marty McFly, Doc Brown, Jennifer Parker, Biff Tannen, Lorraine McFly', difficulty: 'lätt' },
      { title: 'Men in Black', definition: 'Agent J, Agent K, Edgar, Zed, Dr. Laurel Weaver', difficulty: 'lätt' },
      { title: 'Rocky', definition: 'Rocky Balboa, Adrian, Mickey, Apollo Creed, Paulie', difficulty: 'lätt' },
      { title: 'Terminator 2: Judgment Day', definition: 'Sarah Connor, John Connor, T-800, T-1000, Dyson', difficulty: 'lätt' },
      { title: 'Fury', definition: 'Wardaddy, Bible, Coon-Ass, Gordo, Norman', difficulty: 'lätt' },
      { title: 'The Sound of Music', definition: 'Maria, Captain von Trapp, Liesl, Rolf, Max', difficulty: 'lätt' },
      { title: 'Raiders of the Lost Ark', definition: 'Indiana Jones, Marion Ravenwood, Sallah, Belloq, Toht', difficulty: 'lätt' },
      { title: 'Saw', definition: 'Adam, Lawrence Gordon, Jigsaw, Tapp, Amanda', difficulty: 'lätt' },
      { title: 'Ocean\'s Eleven', definition: 'Danny Ocean, Rusty Ryan, Linus Caldwell, Terry Benedict, Tess Ocean', difficulty: 'lätt' },
      { title: 'Rush Hour', definition: 'Detective Lee, Detective Carter, Juntao, Solon Han, Consul Han', difficulty: 'lätt' },
      { title: 'Civil War', definition: 'Lee, Jessie, Joel, Sammy, the President', difficulty: 'lätt' },
    ],
    'Skådespelare': [
      { title: 'Keanu Reeves', definition: 'Kanadensisk skådespelare – The Matrix, John Wick. Global actionstjärna.', difficulty: 'lätt' },
      { title: 'Leonardo DiCaprio', definition: 'Amerikansk skådespelare – Titanic, Inception, The Revenant.', difficulty: 'lätt' },
      { title: 'Denzel Washington', definition: 'Amerikansk skådespelare – Training Day, Malcolm X, Fences.', difficulty: 'lätt' },
      { title: 'Meryl Streep', definition: 'Amerikansk skådespelerska – rekordmånga Oscar-nomineringar.', difficulty: 'lätt' },
      { title: 'Tom Hanks', definition: 'Amerikansk skådespelare – Forrest Gump, Saving Private Ryan, Cast Away.', difficulty: 'lätt' },
      { title: 'Robert De Niro', definition: 'Amerikansk skådespelare – Taxi Driver, Raging Bull, The Godfather Part II.', difficulty: 'lätt' },
      { title: 'Al Pacino', definition: 'Amerikansk skådespelare – The Godfather, Scarface, Scent of a Woman.', difficulty: 'lätt' },
      { title: 'Brad Pitt', definition: 'Amerikansk skådespelare och producent – Fight Club, Seven, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Scarlett Johansson', definition: 'Amerikansk skådespelerska – Black Widow, Lost in Translation, Marriage Story.', difficulty: 'lätt' },
      { title: 'Johnny Depp', definition: 'Amerikansk skådespelare – Pirates of the Caribbean, Edward Scissorhands.', difficulty: 'lätt' },
      { title: 'Christian Bale', definition: 'Brittisk skådespelare – The Dark Knight-trilogin, The Machinist.', difficulty: 'lätt' },
      { title: 'Cate Blanchett', definition: 'Australisk skådespelerska – Blue Jasmine, Carol, The Lord of the Rings.', difficulty: 'lätt' },
      { title: 'Morgan Freeman', definition: 'Amerikansk skådespelare – The Shawshank Redemption, Seven, Million Dollar Baby.', difficulty: 'lätt' },
      { title: 'Matt Damon', definition: 'Amerikansk skådespelare – Good Will Hunting, The Martian, Bourne-serien.', difficulty: 'lätt' },
      { title: 'Will Smith', definition: 'Amerikansk skådespelare – Men in Black, Independence Day, The Pursuit of Happyness.', difficulty: 'lätt' },
      { title: 'Joaquin Phoenix', definition: 'Amerikansk skådespelare – Joker, Her, Walk the Line.', difficulty: 'lätt' },
      { title: 'Natalie Portman', definition: 'Israelisk-amerikansk skådespelerska – Black Swan, V for Vendetta, Star Wars.', difficulty: 'lätt' },
      { title: 'Ryan Gosling', definition: 'Kanadensisk skådespelare – La La Land, Drive, Blade Runner 2049.', difficulty: 'lätt' },
      { title: 'Emma Stone', definition: 'Amerikansk skådespelerska – La La Land, Easy A, The Favourite.', difficulty: 'lätt' },
      { title: 'Hugh Jackman', definition: 'Australisk skådespelare – Wolverine i X-Men, Les Misérables, The Greatest Showman.', difficulty: 'lätt' },
      { title: 'Samuel L. Jackson', definition: 'Amerikansk skådespelare – Pulp Fiction, Nick Fury i Marvel.', difficulty: 'lätt' },
      { title: 'Sandra Bullock', definition: 'Amerikansk skådespelerska – Speed, Gravity, The Blind Side.', difficulty: 'lätt' },
      { title: 'Anne Hathaway', definition: 'Amerikansk skådespelerska – The Devil Wears Prada, Les Misérables, The Dark Knight Rises.', difficulty: 'lätt' },
      { title: 'Chris Hemsworth', definition: 'Australisk skådespelare – Thor i Marvel Cinematic Universe.', difficulty: 'lätt' },
      { title: 'Robert Downey Jr.', definition: 'Amerikansk skådespelare – Iron Man, Sherlock Holmes.', difficulty: 'lätt' },
      { title: 'Chris Evans', definition: 'Amerikansk skådespelare – Captain America, Knives Out, Snowpiercer.', difficulty: 'lätt' },
      { title: 'Benedict Cumberbatch', definition: 'Brittisk skådespelare – Sherlock, Doctor Strange, The Imitation Game.', difficulty: 'lätt' },
      { title: 'Tom Cruise', definition: 'Amerikansk skådespelare – Mission: Impossible, Top Gun, Jerry Maguire.', difficulty: 'lätt' },
      { title: 'Nicole Kidman', definition: 'Australisk skådespelerska – Moulin Rouge!, The Hours, Big Little Lies.', difficulty: 'lätt' },
      { title: 'Charlize Theron', definition: 'Sydafrikansk-amerikansk skådespelerska – Monster, Mad Max: Fury Road, Atomic Blonde.', difficulty: 'lätt' },
      { title: 'George Clooney', definition: 'Amerikansk skådespelare och regissör – Ocean\'s Eleven, Gravity, Up in the Air.', difficulty: 'lätt' },
      { title: 'Harrison Ford', definition: 'Amerikansk skådespelare – Han Solo i Star Wars och Indiana Jones.', difficulty: 'lätt' },
      { title: 'Mark Ruffalo', definition: 'Amerikansk skådespelare – Hulk i Marvel, Spotlight, Foxcatcher.', difficulty: 'lätt' },
      { title: 'Jeremy Renner', definition: 'Amerikansk skådespelare – The Hurt Locker, The Town, Hawkeye.', difficulty: 'lätt' },
      { title: 'Anthony Hopkins', definition: 'Walesisk skådespelare – The Silence of the Lambs, The Father, Thor.', difficulty: 'lätt' },
      { title: 'Ian McKellen', definition: 'Engelsk skådespelare – Gandalf i The Lord of the Rings, Magneto i X-Men.', difficulty: 'lätt' },
      { title: 'Patrick Stewart', definition: 'Engelsk skådespelare – Captain Picard i Star Trek, Professor X i X-Men.', difficulty: 'lätt' },
      { title: 'Kate Winslet', definition: 'Engelsk skådespelerska – Titanic, Eternal Sunshine, Mare of Easttown.', difficulty: 'lätt' },
      { title: 'Julia Roberts', definition: 'Amerikansk skådespelerska – Pretty Woman, Erin Brockovich, Ocean\'s Eleven.', difficulty: 'lätt' },
      { title: 'Reese Witherspoon', definition: 'Amerikansk skådespelerska – Legally Blonde, Walk the Line, Big Little Lies.', difficulty: 'lätt' },
      { title: 'Jennifer Lawrence', definition: 'Amerikansk skådespelerska – The Hunger Games, Silver Linings Playbook, American Hustle.', difficulty: 'lätt' },
      { title: 'Brie Larson', definition: 'Amerikansk skådespelerska – Room, Captain Marvel, Short Term 12.', difficulty: 'lätt' },
      { title: 'Gal Gadot', definition: 'Israelisk skådespelerska – Wonder Woman i DC-filmerna.', difficulty: 'lätt' },
      { title: 'Zoe Saldana', definition: 'Amerikansk skådespelerska – Avatar, Guardians of the Galaxy, Star Trek.', difficulty: 'lätt' },
      { title: 'Millie Bobby Brown', definition: 'Brittisk skådespelerska – Stranger Things, Enola Holmes, Godzilla.', difficulty: 'lätt' },
      { title: 'Michael B. Jordan', definition: 'Amerikansk skådespelare – Creed, Black Panther, Fruitvale Station.', difficulty: 'lätt' },
      { title: 'Chadwick Boseman', definition: 'Amerikansk skådespelare – Black Panther, 42, Get on Up.', difficulty: 'lätt' },
      { title: 'Idris Elba', definition: 'Brittisk skådespelare – Luther, The Wire, Thor, Pacific Rim.', difficulty: 'lätt' },
      { title: 'Daniel Craig', definition: 'Engelsk skådespelare – James Bond i bl.a. Skyfall.', difficulty: 'lätt' },
      { title: 'Rami Malek', definition: 'Amerikansk skådespelare – Bohemian Rhapsody, Mr. Robot.', difficulty: 'lätt' },
      { title: 'Dev Patel', definition: 'Brittisk skådespelare – Slumdog Millionaire, Lion, The Green Knight.', difficulty: 'lätt' },
      { title: 'Pedro Pascal', definition: 'Chilensk-amerikansk skådespelare – The Mandalorian, Narcos, The Last of Us.', difficulty: 'lätt' },
      { title: 'Oscar Isaac', definition: 'Guatemalansk-amerikansk skådespelare – Ex Machina, Dune, Star Wars.', difficulty: 'lätt' },
      { title: 'Adam Driver', definition: 'Amerikansk skådespelare – Marriage Story, Star Wars, BlacKkKlansman.', difficulty: 'lätt' },
      { title: 'Tilda Swinton', definition: 'Skotsk skådespelerska – Michael Clayton, We Need to Talk About Kevin, Doctor Strange.', difficulty: 'lätt' },
      { title: 'Frances McDormand', definition: 'Amerikansk skådespelerska – Fargo, Three Billboards, Nomadland.', difficulty: 'lätt' },
      { title: 'Viola Davis', definition: 'Amerikansk skådespelerska – Fences, The Help, How to Get Away with Murder.', difficulty: 'lätt' },
      { title: 'Lupita Nyong\'o', definition: 'Kenyansk-mexikansk skådespelerska – 12 Years a Slave, Black Panther, Us.', difficulty: 'lätt' },
      { title: 'Mahershala Ali', definition: 'Amerikansk skådespelare – Moonlight, Green Book, True Detective.', difficulty: 'lätt' },
      { title: 'Javier Bardem', definition: 'Spansk skådespelare – No Country for Old Men, Biutiful, Skyfall.', difficulty: 'lätt' },
      { title: 'Penélope Cruz', definition: 'Spansk skådespelerska – Vicky Cristina Barcelona, Volver, Parallel Mothers.', difficulty: 'lätt' },
      { title: 'Antonio Banderas', definition: 'Spansk skådespelare – Desperado, The Mask of Zorro, rösten till Puss in Boots.', difficulty: 'lätt' },
      { title: 'Gael García Bernal', definition: 'Mexikansk skådespelare – Y Tu Mamá También, The Motorcycle Diaries, Mozart in the Jungle.', difficulty: 'lätt' },
      { title: 'Diego Luna', definition: 'Mexikansk skådespelare – Rogue One, Andor, Y Tu Mamá También.', difficulty: 'lätt' },
      { title: 'Salma Hayek', definition: 'Mexikansk-amerikansk skådespelerska – Frida, Desperado, Eternals.', difficulty: 'lätt' },
      { title: 'Wagner Moura', definition: 'Brasiliansk skådespelare – Narcos, Elite Squad.', difficulty: 'lätt' },
      { title: 'Ricardo Darín', definition: 'Argentinsk skådespelare – The Secret in Their Eyes, Wild Tales, Nine Queens.', difficulty: 'lätt' },
      { title: 'Tony Leung Chiu-wai', definition: 'Skådespelare från Hongkong – In the Mood for Love, Infernal Affairs, Shang-Chi.', difficulty: 'lätt' },
      { title: 'Andy Lau', definition: 'Skådespelare och sångare från Hongkong – Infernal Affairs, Running Out of Time.', difficulty: 'lätt' },
      { title: 'Donnie Yen', definition: 'Skådespelare och kampsportare från Hongkong – Ip Man, Rogue One.', difficulty: 'lätt' },
      { title: 'Maggie Cheung', definition: 'Skådespelerska från Hongkong – In the Mood for Love, Hero, Center Stage.', difficulty: 'lätt' },
      { title: 'Jackie Chan', definition: 'Skådespelare och stuntlegend från Hongkong – Rush Hour, Police Story.', difficulty: 'lätt' },
      { title: 'Jet Li', definition: 'Kinesisk skådespelare och kampsportare – Hero, Once Upon a Time in China, Lethal Weapon 4.', difficulty: 'lätt' },
      { title: 'Zhang Ziyi', definition: 'Kinesisk skådespelerska – Crouching Tiger Hidden Dragon, Hero, Memoirs of a Geisha.', difficulty: 'lätt' },
      { title: 'Gong Li', definition: 'Kinesisk skådespelerska – Raise the Red Lantern, Memoirs of a Geisha.', difficulty: 'lätt' },
      { title: 'Takeshi Kitano', definition: 'Japansk skådespelare och regissör – Hana-bi, Sonatine.', difficulty: 'lätt' },
      { title: 'Ken Watanabe', definition: 'Japansk skådespelare – The Last Samurai, Inception, Letters from Iwo Jima.', difficulty: 'lätt' },
      { title: 'Song Kang-ho', definition: 'Sydkoreansk skådespelare – Parasite, Memories of Murder, The Host.', difficulty: 'lätt' },
      { title: 'Lee Byung-hun', definition: 'Sydkoreansk skådespelare – Joint Security Area, I Saw the Devil.', difficulty: 'lätt' },
      { title: 'Bae Doona', definition: 'Sydkoreansk skådespelerska – Cloud Atlas, Sense8, Kingdom.', difficulty: 'lätt' },
      { title: 'Heath Ledger', definition: 'Australisk skådespelare – The Dark Knight, Brokeback Mountain.', difficulty: 'lätt' },
      { title: 'Russell Crowe', definition: 'Nyzeeländsk-född skådespelare – Gladiator, A Beautiful Mind, L.A. Confidential.', difficulty: 'lätt' },
      { title: 'Hugo Weaving', definition: 'Engelsk-australisk skådespelare – The Matrix, The Lord of the Rings, V for Vendetta.', difficulty: 'lätt' },
      { title: 'Sam Neill', definition: 'Nyzeeländsk skådespelare – Jurassic Park, The Piano, Peaky Blinders.', difficulty: 'lätt' },
      { title: 'Mel Gibson', definition: 'Amerikansk-australisk skådespelare – Mad Max, Lethal Weapon, Braveheart.', difficulty: 'lätt' },
      { title: 'Liam Neeson', definition: 'Irländsk skådespelare – Schindler\'s List, Taken, Batman Begins.', difficulty: 'lätt' },
      { title: 'Colin Farrell', definition: 'Irländsk skådespelare – In Bruges, The Banshees of Inisherin, The Lobster.', difficulty: 'lätt' },
      { title: 'Cillian Murphy', definition: 'Irländsk skådespelare – Peaky Blinders, Oppenheimer, 28 Days Later.', difficulty: 'lätt' },
      { title: 'Daniel Day-Lewis', definition: 'Engelsk-irländsk skådespelare – There Will Be Blood, Lincoln, Gangs of New York.', difficulty: 'lätt' },
      { title: 'Helena Bonham Carter', definition: 'Engelsk skådespelerska – Fight Club, The King\'s Speech, Harry Potter.', difficulty: 'lätt' },
      { title: 'Emma Thompson', definition: 'Engelsk skådespelerska – Sense and Sensibility, Love Actually, Saving Mr. Banks.', difficulty: 'lätt' },
      { title: 'Gary Oldman', definition: 'Engelsk skådespelare – Darkest Hour, The Dark Knight, Tinker Tailor Soldier Spy.', difficulty: 'lätt' },
      { title: 'Ralph Fiennes', definition: 'Engelsk skådespelare – The English Patient, Schindler\'s List, Voldemort i Harry Potter.', difficulty: 'lätt' },
      { title: 'Jude Law', definition: 'Engelsk skådespelare – The Talented Mr. Ripley, Sherlock Holmes, The New Pope.', difficulty: 'lätt' },
      { title: 'Keira Knightley', definition: 'Engelsk skådespelerska – Pirates of the Caribbean, Pride & Prejudice, Atonement.', difficulty: 'lätt' },
      { title: 'Naomi Watts', definition: 'Brittisk-australisk skådespelerska – Mulholland Drive, The Ring, King Kong.', difficulty: 'lätt' },
      { title: 'Monica Bellucci', definition: 'Italiensk skådespelerska – Malèna, The Matrix-uppföljarna, Spectre.', difficulty: 'lätt' },
      { title: 'Sophia Loren', definition: 'Italiensk skådespelerska – klassisk stjärna känd för Two Women.', difficulty: 'lätt' },
      { title: 'Jean Reno', definition: 'Fransk skådespelare – Léon: The Professional, Ronin, The Da Vinci Code.', difficulty: 'lätt' },
      { title: 'Marion Cotillard', definition: 'Fransk skådespelerska – La Vie en Rose, Inception, Rust and Bone.', difficulty: 'lätt' },
      { title: 'Vincent Cassel', definition: 'Fransk skådespelare – Black Swan, La Haine, Eastern Promises.', difficulty: 'lätt' },
      { title: 'Gérard Depardieu', definition: 'Fransk skådespelare – Cyrano de Bergerac, Green Card.', difficulty: 'lätt' },
      { title: 'Max von Sydow', definition: 'Svensk skådespelare – Det sjunde inseglet, The Exorcist.', difficulty: 'lätt' },
      { title: 'Alicia Vikander', definition: 'Svensk skådespelerska – Ex Machina, The Danish Girl, Tomb Raider.', difficulty: 'lätt' },
      { title: 'Mads Mikkelsen', definition: 'Dansk skådespelare – Another Round, Casino Royale, Hannibal.', difficulty: 'lätt' },
      { title: 'Viggo Mortensen', definition: 'Dansk-amerikansk skådespelare – The Lord of the Rings, Green Book, Eastern Promises.', difficulty: 'lätt' },
      { title: 'Michael Fassbender', definition: 'Irländsk-tysk skådespelare – X-Men, Shame, 12 Years a Slave.', difficulty: 'lätt' },
      { title: 'Timothée Chalamet', definition: 'Amerikansk skådespelare – Call Me by Your Name, Dune, Wonka.', difficulty: 'lätt' },
      { title: 'Austin Butler', definition: 'Amerikansk skådespelare – Elvis, Dune: Part Two, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Barry Keoghan', definition: 'Irländsk skådespelare – Saltburn, The Banshees of Inisherin.', difficulty: 'lätt' },
      { title: 'Paul Mescal', definition: 'Irländsk skådespelare – Aftersun, Normal People, Gladiator II.', difficulty: 'lätt' },
      { title: 'Jacob Elordi', definition: 'Australisk skådespelare – Euphoria, Saltburn, Priscilla.', difficulty: 'lätt' },
      { title: 'Anya Taylor-Joy', definition: 'Argentinsk-brittisk skådespelerska – The Queen\'s Gambit, Furiosa, The Witch.', difficulty: 'lätt' },
      { title: 'Jodie Comer', definition: 'Engelsk skådespelerska – Killing Eve, The Last Duel, Free Guy.', difficulty: 'lätt' },
      { title: 'Nicholas Hoult', definition: 'Engelsk skådespelare – Mad Max: Fury Road, The Great, X-Men.', difficulty: 'lätt' },
      { title: 'Riz Ahmed', definition: 'Brittisk skådespelare – Sound of Metal, Nightcrawler, The Night Of.', difficulty: 'lätt' },
      { title: 'Jesse Plemons', definition: 'Amerikansk skådespelare – The Power of the Dog, Fargo, Civil War.', difficulty: 'lätt' },
      { title: 'Michelle Yeoh', definition: 'Malaysisk skådespelerska – Everything Everywhere All at Once, Crouching Tiger Hidden Dragon.', difficulty: 'lätt' },
      { title: 'Ke Huy Quan', definition: 'Amerikansk skådespelare – Everything Everywhere All at Once, Indiana Jones and the Temple of Doom.', difficulty: 'lätt' },
      { title: 'Brendan Fraser', definition: 'Kanadensisk-amerikansk skådespelare – The Whale, The Mummy.', difficulty: 'lätt' },
      { title: 'Adrien Brody', definition: 'Amerikansk skådespelare – The Pianist, The Brutalist, The Grand Budapest Hotel.', difficulty: 'lätt' },
      { title: 'Toni Collette', definition: 'Australisk skådespelerska – Hereditary, The Sixth Sense.', difficulty: 'lätt' },
      { title: 'Isabelle Huppert', definition: 'Fransk skådespelerska – Elle, The Piano Teacher, Amour.', difficulty: 'lätt' },
      { title: 'Léa Seydoux', definition: 'Fransk skådespelerska – Blue Is the Warmest Colour, No Time to Die, Dune: Part Two.', difficulty: 'lätt' },
      { title: 'Juliette Binoche', definition: 'Fransk skådespelerska – The English Patient, Certified Copy, Chocolat.', difficulty: 'lätt' },
      { title: 'Halle Berry', definition: 'Amerikansk skådespelerska – Monster\'s Ball, X-Men, John Wick: Chapter 3.', difficulty: 'lätt' },
      { title: 'Jennifer Connelly', definition: 'Amerikansk skådespelerska – A Beautiful Mind, Top Gun: Maverick, Requiem for a Dream.', difficulty: 'lätt' },
      { title: 'Elizabeth Olsen', definition: 'Amerikansk skådespelerska – WandaVision, Martha Marcy May Marlene.', difficulty: 'lätt' },
      { title: 'Dakota Johnson', definition: 'Amerikansk skådespelerska – Fifty Shades, Suspiria.', difficulty: 'lätt' },
      { title: 'Amy Adams', definition: 'Amerikansk skådespelerska – Arrival, American Hustle, Enchanted.', difficulty: 'lätt' },
      { title: 'Aubrey Plaza', definition: 'Amerikansk skådespelerska – Parks and Recreation, Emily the Criminal, The White Lotus.', difficulty: 'lätt' },
      { title: 'Rachel Zegler', definition: 'Amerikansk skådespelerska – West Side Story, The Hunger Games-prequel.', difficulty: 'lätt' },
      { title: 'Sydney Sweeney', definition: 'Amerikansk skådespelerska – Euphoria, Reality, Anyone But You.', difficulty: 'lätt' },
      { title: 'Jenna Ortega', definition: 'Amerikansk skådespelerska – Wednesday, Scream, Beetlejuice Beetlejuice.', difficulty: 'lätt' },
      { title: 'Steven Spielberg', definition: 'Oscarsbelönad regissör – Jaws, E.T., Schindler\'s List.', difficulty: 'lätt' },
      { title: 'Martin Scorsese', definition: 'Oscarsbelönad regissör – The Godfather Part II, The Deer Hunter, Raging Bull (Goodfellas, The Irishman).', difficulty: 'lätt' },
      { title: 'Quentin Tarantino', definition: 'Regissör (Palme d\'Or) – Pulp Fiction, Kill Bill, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Christopher Nolan', definition: 'Oscarsbelönad regissör – Inception, The Dark Knight, Oppenheimer.', difficulty: 'lätt' },
      { title: 'Francis Ford Coppola', definition: 'Regissör – The Godfather, Apocalypse Now, The Conversation.', difficulty: 'lätt' },
      { title: 'Peter Jackson', definition: 'Oscarsbelönad regissör – The Lord of the Rings-trilogin, The Hobbit.', difficulty: 'lätt' },
      { title: 'Bong Joon-ho', definition: 'Oscarsbelönad regissör – Parasite, Memories of Murder, Snowpiercer.', difficulty: 'lätt' },
      { title: 'Clint Eastwood', definition: 'Oscarsbelönad regissör – Unforgiven, Million Dollar Baby, Gran Torino.', difficulty: 'lätt' },
      { title: 'Alfred Hitchcock', definition: 'Regissör – Rear Window, Psycho, Vertigo.', difficulty: 'lätt' },
      { title: 'Guillermo del Toro', definition: 'Oscarsbelönad regissör – The Shape of Water, Pan\'s Labyrinth.', difficulty: 'lätt' },
      { title: 'Alfonso Cuarón', definition: 'Oscarsbelönad regissör – Roma, Children of Men, Gravity.', difficulty: 'lätt' },
      { title: 'Akira Kurosawa', definition: 'Regissör – Seven Samurai, Rashomon, Ran.', difficulty: 'lätt' },
      { title: 'Ingmar Bergman', definition: 'Svensk regissör – Det sjunde inseglet, Persona.', difficulty: 'lätt' },
      { title: 'Denis Villeneuve', definition: 'Regissör – Dune, Blade Runner 2049, Arrival.', difficulty: 'lätt' },
      { title: 'Paul Thomas Anderson', definition: 'Regissör – There Will Be Blood, Magnolia, Boogie Nights.', difficulty: 'lätt' },
      { title: 'James Cameron', definition: 'Oscarsbelönad regissör – Titanic, Avatar, The Terminator.', difficulty: 'lätt' },
      { title: 'Spike Lee', definition: 'Oscarsbelönad regissör – Do the Right Thing, Malcolm X, BlacKkKlansman.', difficulty: 'lätt' },
    ],
};
