// Auto-genererad filmdata (handlingar, citat, karaktärer, skådespelare)
export const film = {
    'Handlingar': [
      { title: 'The Seat', definition: 'En berättelse om press, närvaro och platsens betydelse i en liten, koncentrerad dramatisk värld.', difficulty: 'medel', noFill: true },
      { title: 'Torrente: The Dumb Arm of the Law', definition: 'En korrupt och klantig före detta polis försöker lösa brott på sitt eget kaotiska sätt.', difficulty: 'medel', noFill: true },
      { title: 'Johnny English Strikes Again', definition: 'En inkompetent agent tvingas rädda landet efter ett stort cyberhot.', difficulty: 'medel', noFill: true },
      { title: 'Johnny English Reborn', definition: 'Johnny English återvänder och måste stoppa en internationell konspiration.', difficulty: 'medel', noFill: true },
      { title: 'Johnny English', definition: 'En fumlig agent får chansen att rädda nationen när allt går fel för de riktiga proffsen.', difficulty: 'medel', noFill: true },
      { title: 'Robin Hood: Men in Tights', definition: 'En parodisk version av Robin Hood-myten fylld med satir och slapstick.', difficulty: 'medel', noFill: true },
      { title: 'Wolfs', definition: 'Två fixare tvingas samarbeta under en natt av kaos och kriminalitet.', difficulty: 'medel', noFill: true },
      { title: 'The Man with the Iron Fists 2', definition: 'En krigare dras in i våldsamma konflikter och kämpar för rättvisa i en brutal värld.', difficulty: 'medel', noFill: true },
      { title: 'The Man with the Iron Fists', definition: 'En smed blir en krigare när guld, makt och hämnd kolliderar.', difficulty: 'medel', noFill: true },
      { title: 'Piece By Piece', definition: 'En dokumentär berättad genom kreativa, visuella byggbitar om en artists liv och karriär.', difficulty: 'medel', noFill: true },
      { title: 'Kiss the Girls', definition: 'En kriminalthriller där en man jagar en seriemördare och räddar kidnappade kvinnor.', difficulty: 'medel', noFill: true },
      { title: 'Nikita', definition: 'En dömd kvinna omformas till statens mördare men börjar längta efter frihet.', difficulty: 'medel', noFill: true },
      { title: 'The Ridiculous 6', definition: 'En vild westernparodi följer sex halvbröder på en absurd resa.', difficulty: 'medel', noFill: true },
      { title: 'You Don\'t Mess with the Zohan', definition: 'En israelisk agent låtsas vara frisör i New York för att börja om sitt liv.', difficulty: 'medel', noFill: true },
      { title: 'Home Alone 2: Lost in New York', definition: 'En pojke blir ensam i New York och måste stoppa två tjuvar igen.', difficulty: 'medel', noFill: true },
      { title: 'Night at the Museum: Battle of the Smithsonian', definition: 'En nattlig museumvakt reser till ett nytt museum fullt av historisk kaos.', difficulty: 'medel', noFill: true },
      { title: 'Ricky Stanicky', definition: 'Tre vänner hittar på en påhittad vän som snart blir ett stort problem.', difficulty: 'medel', noFill: true },
      { title: 'Grown Ups 2', definition: 'En grupp gamla vänner återförenas för mer kaotisk familjekomedi.', difficulty: 'medel', noFill: true },
      { title: 'How to Train Your Dragon 2', definition: 'Hiccup utforskar en större värld där drakar och människor hotas av ett nytt krig.', difficulty: 'medel', noFill: true },
      { title: 'Kung Fu Panda 2', definition: 'Po måste förstå sitt förflutna för att kunna besegra en mäktig fiende.', difficulty: 'medel', noFill: true },
      { title: 'Smile', definition: 'En psykolog får en förbannelse som sprider skräck genom traumatiska möten och fasansfulla leenden.', difficulty: 'medel', noFill: true },
      { title: 'Pirates of the Caribbean: At World\'s End', definition: 'Piraterna samlas för att slå tillbaka mot makter som vill utplåna deras värld.', difficulty: 'medel', noFill: true },
      { title: 'Toy Story 2', definition: 'Woody kidnappas och upptäcker sitt förflutna medan Buzz och vännerna försöker rädda honom.', difficulty: 'medel', noFill: true },
      { title: 'Encanto', definition: 'En familj med magiska gåvor försöker hålla ihop när deras hemlighet börjar spricka.', difficulty: 'medel', noFill: true },
      { title: 'Creep', definition: 'En videofilmare accepterar ett jobb som blir alltmer obehagligt och manipulativt.', difficulty: 'medel', noFill: true },
      { title: 'Big Hero 6', definition: 'Ett ungt geni och hans robotvän bildar ett team för att stoppa en skurk i San Fransokyo.', difficulty: 'medel', noFill: true },
      { title: 'Diary of a Wimpy Kid: Rodrick Rules', definition: 'Greg försöker överleva sin brors kaos samtidigt som skol- och familjelivet spårar ur.', difficulty: 'medel', noFill: true },
      { title: 'Guardians of the Galaxy Vol. 3', definition: 'Guardians försöker rädda en av sina egna och möter sitt mest känslomässiga hot hittills.', difficulty: 'medel', noFill: true },
      { title: 'Blink Twice', definition: 'En grupp människor hamnar i ett farligt spel där makt, minne och kontroll kolliderar.', difficulty: 'medel', noFill: true },
      { title: 'Hercules', definition: 'En halvgud måste återta sin plats och bevisa sitt hjärtas styrka.', difficulty: 'medel', noFill: true },
      { title: 'Night at the Museum', definition: 'En nattvakt upptäcker att museets utställningar får liv efter mörkrets inbrott.', difficulty: 'medel', noFill: true },
      { title: 'Ford v Ferrari', definition: 'Två män försöker bygga en bil som kan slå Ferrari i Le Mans.', difficulty: 'medel', noFill: true },
      { title: 'Thor', definition: 'En arrogant gud förvisas till jorden och måste lära sig ödmjukhet för att bli värdig.', difficulty: 'medel', noFill: true },
      { title: 'Madagascar', definition: 'Fyra djur från zoo hamnar på vildvuxna öar och måste anpassa sig.', difficulty: 'medel', noFill: true },
      { title: 'The Incredibles', definition: 'En superhjältefamilj tvingas återvända till handling när en ny fiende hotar världen.', difficulty: 'medel', noFill: true },
      { title: 'Guardians of the Galaxy Vol. 2', definition: 'Guardians försöker förstå familj, lojalitet och förlåtelse när gamla hemligheter avslöjas.', difficulty: 'medel', noFill: true },
      { title: 'Romeo + Juliet', definition: 'Två unga älskande kämpar mot en våldsam familjefejd i moderniserad stil.', difficulty: 'medel', noFill: true },
      { title: 'The Parent Trap', definition: 'Två tvillingar som separerats vid födseln försöker föra sina föräldrar tillbaka till varandra.', difficulty: 'medel', noFill: true },
      { title: 'Pirates of the Caribbean: Dead Man\'s Chest', definition: 'Jack Sparrow jagar ett sätt att undkomma Davy Jones och rädda sitt eget liv.', difficulty: 'medel', noFill: true },
      { title: 'The Ritual', definition: 'Fyra vänner vandrar in i en nordisk skog och möter något uråldrigt och skrämmande.', difficulty: 'medel', noFill: true },
      { title: 'Doctor Strange in the Multiverse of Madness', definition: 'Stephen Strange korsar multiversum och möter nya hot, allianser och versioner av sig själv.', difficulty: 'medel', noFill: true },
      { title: 'Grown Ups', definition: 'Fem gamla vänner återförenas under en sommar fylld av familj, nostalgi och kaos.', difficulty: 'medel', noFill: true },
      { title: 'Rogue One: A Star Wars Story', definition: 'En grupp rebeller försöker stjäla ritningarna till Dödsstjärnan.', difficulty: 'medel', noFill: true },
      { title: 'Scooby-Doo', definition: 'Ett gammalt gäng återförenas för att lösa ett mysterium på en ö full av konstiga händelser.', difficulty: 'medel', noFill: true },
      { title: 'Thor: The Dark World', definition: 'Thor måste rädda både Asgård och jorden från en uråldrig mörk kraft.', difficulty: 'medel', noFill: true },
      { title: '2012', definition: 'En global katastrof tvingar människor att kämpa för överlevnad när världen går under.', difficulty: 'medel', noFill: true },
      { title: 'Magazine Dreams', definition: 'En bodybuilder kämpar med ambition, ensamhet och psykisk ohälsa i sin jakt på erkännande.', difficulty: 'medel', noFill: true },
      { title: 'Carry-On', definition: 'En säkerhetsagent pressas att släppa igenom ett farligt paket under ett intensivt julskift.', difficulty: 'medel', noFill: true },
      { title: 'Creep 2', definition: 'En dokumentärfilmare möter en man med mörka hemligheter och tvingas överleva ett farligt psykologiskt spel.', difficulty: 'medel', noFill: true },
      { title: 'The Girl Next Door', definition: 'En tonåring blir förälskad i sin granne men upptäcker att hennes liv är långt mer komplicerat än det verkar.', difficulty: 'medel', noFill: true },
      { title: 'Thor: Love and Thunder', definition: 'Thor möter en ny gudomlig fiende medan han försöker förstå kärlek, förlust och mening.', difficulty: 'medel', noFill: true },
      { title: 'Billy Elliot', definition: 'En pojke i ett hårt samhälle upptäcker balett och följer sin passion trots motstånd.', difficulty: 'medel', noFill: true },
      { title: 'Brothers', definition: 'En soldat tros vara död och hans familj splittras när sanningen långsamt kommer fram.', difficulty: 'medel', noFill: true },
      { title: 'Kung Fu Panda 4', definition: 'Po står inför ett nytt ansvar när han måste hitta sin efterträdare och möta nya fiender.', difficulty: 'medel', noFill: true },
      { title: 'Rise of the Guardians', definition: 'Legendariska väktare förenas för att stoppa en mörk kraft som hotar barns hopp.', difficulty: 'medel', noFill: true },
      { title: 'Robots', definition: 'I en värld av maskiner försöker en ung uppfinnare förverkliga sina drömmar.', difficulty: 'medel', noFill: true },
      { title: 'Epic', definition: 'En ung flicka dras in i en hemlig värld där naturens krafter avgör balansen mellan gott och ont.', difficulty: 'medel', noFill: true },
      { title: 'Dr. No', definition: 'James Bond skickas till Jamaica för att utreda ett farligt spionmysterium.', difficulty: 'medel', noFill: true },
      { title: 'The Creator', definition: 'I en framtida värld där AI och människor är i konflikt blir en man tvungen att välja sida.', difficulty: 'medel', noFill: true },
      { title: 'Star Wars: The Last Jedi', definition: 'Luke Skywalker återvänder när motståndet kämpar för att överleva mot Första Ordningen.', difficulty: 'medel', noFill: true },
      { title: 'Hoodwinked!', definition: 'En satirisk version av Rödluvan där olika berättelser korsas i en kriminalgåta.', difficulty: 'medel', noFill: true },
      { title: 'Open Season', definition: 'Ett tamt djur kastas ut i vildmarken och måste lära sig överleva med nya vänner.', difficulty: 'medel', noFill: true },
      { title: 'Despicable Me 2', definition: 'En före detta superskurk dras in i ett nytt uppdrag och hittar oväntad kärlek.', difficulty: 'medel', noFill: true },
      { title: 'Aladdin', definition: 'En gatupojke får tillgång till en magisk lampa och försöker vinna prinsessans hjärta.', difficulty: 'medel', noFill: true },
      { title: 'The Game', definition: 'En rik man dras in i ett mystiskt spel som suddar ut gränsen mellan verklighet och manipulation.', difficulty: 'medel', noFill: true },
      { title: 'The Iron Giant', definition: 'En pojke blir vän med en gigantisk robot och försöker skydda honom från världens rädsla.', difficulty: 'medel', noFill: true },
      { title: 'The Incredible Hulk', definition: 'En forskare jagas av militären samtidigt som han försöker kontrollera sin inre monsterversion.', difficulty: 'medel', noFill: true },
      { title: 'Sinister', definition: 'En författare hittar hemska filmer och dras in i en övernaturlig spiral av våld.', difficulty: 'medel', noFill: true },
      { title: 'Star Wars: The Force Awakens', definition: 'En ny generation dras in i kampen mot mörkret när gamla hjältar återvänder.', difficulty: 'medel', noFill: true },
      { title: 'Rango', definition: 'En ödla blir sheriff i en torr ökenstad och tvingas hitta sitt sanna jag.', difficulty: 'medel', noFill: true },
      { title: 'Transformers', definition: 'En tonåring blir indragen i ett krig mellan robotar från rymden.', difficulty: 'medel', noFill: true },
      { title: 'The Shawshank Redemption', definition: 'En oskyldigt dömd man bygger ett nytt liv och en livslång vänskap i fängelset.', difficulty: 'medel' },
      { title: 'Moonlight', definition: 'En ung man växer upp genom tre faser av livet medan han kämpar med identitet, kärlek och tystnad.', difficulty: 'medel' },
      { title: 'Harakiri', definition: 'En samuraj söker rättvisa och avslöjar hyckleri och brutalitet i ett feodalt system.', difficulty: 'medel' },
      { title: 'Limitless', definition: 'En författare får tillgång till en drog som gör honom extremt intelligent och förändrar hans liv.', difficulty: 'medel' },
      { title: 'Interstellar', definition: 'En grupp astronauter reser genom rymden för att hitta en ny framtid för mänskligheten.', difficulty: 'medel' },
      { title: 'The Death of Stalin', definition: 'Efter Stalins död utbryter kaos, maktspel och paranoia bland Sovjets ledare.', difficulty: 'medel' },
      { title: 'Doctor Glas', definition: 'En läkare blir indragen i ett moraliskt dilemma när han försöker hjälpa en kvinna i ett olyckligt äktenskap.', difficulty: 'medel' },
      { title: 'Two Prosecutors', definition: 'En idealistisk åklagare försöker navigera ett korrupt och farligt rättssystem.', difficulty: 'medel' },
      { title: 'GoodFellas', definition: 'En ung man dras in i maffians värld och får uppleva både makt och förfall.', difficulty: 'medel' },
      { title: 'Snatch', definition: 'Kriminella, boxare och bedragare kolliderar i en kaotisk jakt på en enorm diamant.', difficulty: 'medel' },
      { title: 'A Different Man', definition: 'En man genomgår en drastisk förändring i utseende och börjar ifrågasätta identitet och självbild.', difficulty: 'medel' },
      { title: 'The Lord of the Rings: The Fellowship of the Ring', definition: 'En hobbit får i uppdrag att förstöra en mäktig ring innan mörkret tar över världen.', difficulty: 'medel' },
      { title: '1917', definition: 'Två soldater måste korsa ett krigsfält för att leverera en avgörande order i tid.', difficulty: 'medel' },
      { title: 'Hamnet', definition: 'En känslomässig berättelse inspirerad av familj, sorg och skapandets ursprung.', difficulty: 'medel' },
      { title: 'Inglourious Basterds', definition: 'Under andra världskriget planerar en grupp soldater och en biografägare hämnd mot nazisterna.', difficulty: 'medel' },
      { title: 'First Cow', definition: 'Två män bygger ett litet partnerskap kring mjölk, överlevnad och drömmar i vilda västern.', difficulty: 'medel' },
      { title: 'Holy Spider', definition: 'En journalist utreder en mördare som riktar in sig på kvinnor och avslöjar ett mörkt samhällsklimat.', difficulty: 'medel' },
      { title: 'Inside Man', definition: 'En smart bankrånare och en förhandlare hamnar i ett intrikat psykologiskt spel.', difficulty: 'medel' },
      { title: 'Society of the Snow', definition: 'Överlevande från en flygkrasch måste samarbeta i extrem kyla för att hålla sig vid liv.', difficulty: 'medel' },
      { title: 'Nocturnal Animals', definition: 'En kvinna konfronteras med en mörk roman som speglar ett gammalt förhållande och förlorade val.', difficulty: 'medel' },
      { title: 'Shogun', definition: 'En brittisk sjöman hamnar i feodalt Japan och dras in i politiska och kulturella konflikter.', difficulty: 'medel' },
      { title: 'A Fish Called Wanda', definition: 'Ett gäng brottslingar, lögner och svartsjuka leder till kaos i en brittisk komedi.', difficulty: 'medel' },
      { title: 'The Basketball Diaries', definition: 'En lovande ung idrottare faller in i missbruk och självdestruktion.', difficulty: 'medel' },
      { title: 'The Fighter', definition: 'En boxare försöker nå framgång medan familj, lojalitet och missbruk drar honom åt olika håll.', difficulty: 'medel' },
      { title: 'The Dirt', definition: 'Ett glamoröst men kaotiskt porträtt av ett rockband fyllt av excess, konflikter och fame.', difficulty: 'medel' },
      { title: 'Hereditary', definition: 'En familj drabbas av sorg och ett växande mörker som avslöjar något demoniskt.', difficulty: 'medel' },
      { title: 'Mississippi Burning', definition: 'Två FBI-agenter utreder medborgarrättsmord i ett våldsamt och rasistiskt samhälle.', difficulty: 'medel' },
      { title: 'War Dogs', definition: 'Två unga män blir vapenhandlare och hamnar i en farlig värld av pengar och lögner.', difficulty: 'medel' },
      { title: 'All of Us Are Dead', definition: 'Ett zombieutbrott i en skola tvingar elever att kämpa för överlevnad.', difficulty: 'medel' },
      { title: 'Project Hail Mary', definition: 'En ensam forskare vaknar upp i rymden och måste rädda jorden med hjälp av vetenskap och oväntad vänskap.', difficulty: 'medel' },
      { title: 'The Goonies', definition: 'En grupp barn letar efter en piratskatt för att rädda sina hem.', difficulty: 'medel' },
      { title: 'Come and See', definition: 'En ung pojke upplever krigets fasor och förlorar oskulden i en av filmhistoriens mörkaste skildringar.', difficulty: 'medel' },
      { title: 'Entergalactic', definition: 'En konstnär navigerar kärlek, vänskap och ambition i New Yorks kreativa nattliv.', difficulty: 'medel' },
      { title: 'Moana', definition: 'En ung kvinna ger sig ut över havet för att rädda sitt folk och upptäcka sin identitet.', difficulty: 'medel' },
      { title: 'Captain Marvel', definition: 'En flygpilot får tillbaka sitt förflutna och upptäcker sin plats i ett interstellärt krig.', difficulty: 'medel' },
      { title: 'The Hateful Eight', definition: 'Åtta misstänksamma främlingar fastnar i en snöstorm och avslöjar sina mörka motiv.', difficulty: 'medel' },
      { title: 'The Terminator', definition: 'En cyborg skickas från framtiden för att döda en kvinna som kan förändra mänsklighetens öde.', difficulty: 'medel' },
      { title: 'Despicable Me', definition: 'En före detta superskurk får sitt liv vänt upp och ner när tre flickor kommer in i hans värld.', difficulty: 'medel' },
      { title: 'Dunkirk', definition: 'Soldater, civila och piloter kämpar för överlevnad under evakueringen från Dunkerque.', difficulty: 'medel' },
      { title: 'Home Alone', definition: 'En pojke lämnas ensam hemma och försvarar huset mot två klantiga tjuvar.', difficulty: 'medel' },
      { title: 'The Boy in the Striped Pyjamas', definition: 'En pojke blir vän med en fånge utanför ett koncentrationsläger och förstår inte det verkliga sammanhanget.', difficulty: 'medel' },
      { title: 'Doctor Strange', definition: 'En arrogant kirurg lär sig magi och måste skydda världen från kosmiska hot.', difficulty: 'medel' },
      { title: 'Skyfall', definition: 'James Bond tvingas konfrontera sitt förflutna och skydda MI6 från en farlig fiende.', difficulty: 'medel' },
      { title: 'Tenet', definition: 'En agent använder tidsvändning för att stoppa en katastrof som hotar världen.', difficulty: 'medel' },
      { title: 'John Wick', definition: 'En pensionerad lönnmördare ger sig ut på en våldsam hämndresa efter en personlig tragedi.', difficulty: 'medel' },
      { title: 'Saving Private Ryan', definition: 'En grupp soldater skickas bakom fiendens linjer för att hitta en saknad soldat under andra världskriget.', difficulty: 'medel' },
      { title: 'The Pianist', definition: 'En pianist försöker överleva Förintelsen medan Warszawa faller samman runt honom.', difficulty: 'medel' },
      { title: 'Train to Busan', definition: 'Passagerare på ett tåg kämpar för överlevnad när ett zombieutbrott sprider sig genom Korea.', difficulty: 'medel' },
      { title: 'Hacksaw Ridge', definition: 'En soldat vägrar bära vapen men räddar liv som medic på slagfältet.', difficulty: 'medel' },
      { title: 'Anatomy of a Fall', definition: 'En författare anklagas efter ett dödsfall och ett äktenskap dissekeras i rättssal.', difficulty: 'medel' },
      { title: 'Coach Carter', definition: 'En basketcoach ställer hårda krav på sina spelare för att få dem att lyckas både på och utanför planen.', difficulty: 'medel' },
      { title: 'Godzilla Minus One', definition: 'En traumatisk efterkrigshistoria följer människor som försöker överleva samtidigt som ett monster hotar Japan.', difficulty: 'medel' },
      { title: 'War of the Worlds', definition: 'En vanlig man måste skydda sin familj när jorden invaderas av utomjordiska maskiner.', difficulty: 'medel' },
      { title: 'Mission: Impossible', definition: 'En agent blir falskt anklagad och måste avslöja en förrädare i en högteknologisk spionthriller.', difficulty: 'medel' },
      { title: 'Jarhead', definition: 'En marinsoldat upplever krigets monotoni, frustration och psykologiska tryck under Gulfkriget.', difficulty: 'medel' },
      { title: 'A Fistful of Dollars', definition: 'En vandrande revolverman manipulerar två rivaliserande gäng i en våldsam gränsstad.', difficulty: 'medel' },
      { title: 'Die Hard', definition: 'En ensam polis måste rädda gisslan i en skyskrapa under ett brutalt julaftonsdrama.', difficulty: 'medel' },
      { title: 'Indiana Jones and the Temple of Doom', definition: 'Indiana Jones kastas in i ett mörkt äventyr som handlar om kult, skatter och räddningsaktioner.', difficulty: 'medel' },
      { title: 'Pixels', definition: 'Videospelsfigurer blir verkliga och en grupp udda hjältar måste rädda världen.', difficulty: 'medel' },
      { title: 'Black Panther: Wakanda Forever', definition: 'Wakanda sörjer sin kung och försöker skydda sin framtid från nya hot.', difficulty: 'medel' },
      { title: 'World War Z', definition: 'En före detta FN-utredare reser världen runt för att stoppa en zombiepandemi.', difficulty: 'medel' },
      { title: 'Chernobyl', definition: 'En katastrofal reaktorolycka leder till en kamp om sanning, ansvar och överlevnad.', difficulty: 'medel' },
      { title: 'Pacific Rim', definition: 'Människor styr enorma robotar för att bekämpa monster som stiger upp ur havet.', difficulty: 'medel' },
      { title: 'I Am Legend', definition: 'En ensam man överlever i ett öde New York medan han försöker hitta botemedel och mening.', difficulty: 'medel' },
      { title: 'Shang-Chi and the Legend of the Ten Rings', definition: 'En man konfronterar sin familjs förflutna och kämpar mot sin fars organisation.', difficulty: 'medel' },
      { title: 'Back to the Future Part II', definition: 'Marty och Doc reser till framtiden för att reparera tidslinjen men skapar nya problem.', difficulty: 'medel' },
      { title: 'Men in Black', definition: 'Två agenter skyddar jorden från utomjordiska hot i hemlighet.', difficulty: 'medel' },
      { title: 'Rocky', definition: 'En underskattad boxare får chansen att slåss om titeln och bevisa sitt värde.', difficulty: 'medel' },
      { title: 'Terminator 2: Judgment Day', definition: 'En robot från framtiden måste skydda en pojke som kan avgöra mänsklighetens öde.', difficulty: 'medel' },
      { title: 'Fury', definition: 'En stridshärdad stridsvagnsbesättning kämpar sig genom krigets brutalitet mot slutet av andra världskriget.', difficulty: 'medel' },
      { title: 'The Sound of Music', definition: 'En kvinna förändrar en familjs liv genom musik, kärlek och mod inför krigshot.', difficulty: 'medel' },
      { title: 'Raiders of the Lost Ark', definition: 'Indiana Jones söker arken innan nazisterna får tag på dess kraft.', difficulty: 'medel' },
      { title: 'Saw', definition: 'Två män vaknar fastkedjade i ett rum och måste lösa brutala gåtor för att överleva.', difficulty: 'medel' },
      { title: 'Ocean\'s Eleven', definition: 'En grupp skickliga tjuvar planerar ett sofistikerat kasino-rån i Las Vegas.', difficulty: 'medel' },
      { title: 'Rush Hour', definition: 'Två mycket olika poliser tvingas samarbeta för att rädda en kidnappad flicka.', difficulty: 'medel' },
      { title: 'Civil War', definition: 'Under ett framtida inbördeskrig reser journalister genom ett splittrat USA.', difficulty: 'medel' },
    ],
    'Citat': [
      { title: 'The Seat', definition: '"Sometimes the seat tells the whole story."', difficulty: 'lätt' },
      { title: 'Torrente: The Dumb Arm of the Law', definition: '"Soy la ley."', difficulty: 'lätt' },
      { title: 'Johnny English Strikes Again', definition: '"The important thing is to keep calm and carry on."', difficulty: 'lätt' },
      { title: 'Johnny English Reborn', definition: '"You cannot expect me to accept such a mission."', difficulty: 'lätt' },
      { title: 'Johnny English', definition: '"It\'s not a question of being clever. It\'s a question of being brave."', difficulty: 'lätt' },
      { title: 'Robin Hood: Men in Tights', definition: '"Unlike some other Robin Hoods, I can speak with an English accent."', difficulty: 'lätt' },
      { title: 'Wolfs', definition: '"Every job has a cleanup."', difficulty: 'lätt' },
      { title: 'The Man with the Iron Fists 2', definition: '"Strength is not enough."', difficulty: 'lätt' },
      { title: 'The Man with the Iron Fists', definition: '"A man with a hammer can change the world."', difficulty: 'lätt' },
      { title: 'Piece By Piece', definition: '"Build the life you imagine."', difficulty: 'lätt' },
      { title: 'Kiss the Girls', definition: '"A detective\'s job is to look where others don\'t."', difficulty: 'lätt' },
      { title: 'Nikita', definition: '"The system made me, but it cannot own me."', difficulty: 'lätt' },
      { title: 'The Ridiculous 6', definition: '"We ride at dawn."', difficulty: 'lätt' },
      { title: 'You Don\'t Mess with the Zohan', definition: '"I\'m here to cut hair, not heads."', difficulty: 'lätt' },
      { title: 'Home Alone 2: Lost in New York', definition: '"Merry Christmas, ya filthy animal!"', difficulty: 'lätt' },
      { title: 'Night at the Museum: Battle of the Smithsonian', definition: '"At night, history comes alive."', difficulty: 'lätt' },
      { title: 'Ricky Stanicky', definition: '"Sometimes lies become the whole life."', difficulty: 'lätt' },
      { title: 'Grown Ups 2', definition: '"Some people never grow up."', difficulty: 'lätt' },
      { title: 'How to Train Your Dragon 2', definition: '"We have dragons."', difficulty: 'lätt' },
      { title: 'Kung Fu Panda 2', definition: '"There is no secret ingredient."', difficulty: 'lätt' },
      { title: 'Smile', definition: '"You have to believe me."', difficulty: 'lätt' },
      { title: 'Pirates of the Caribbean: At World\'s End', definition: '"Savvy?"', difficulty: 'lätt' },
      { title: 'Toy Story 2', definition: '"You\'ve got a friend in me."', difficulty: 'lätt' },
      { title: 'Encanto', definition: '"We don\'t talk about Bruno."', difficulty: 'lätt' },
      { title: 'Creep', definition: '"I just want to record some memories."', difficulty: 'lätt' },
      { title: 'Big Hero 6', definition: '"On a scale of 1 to 10, how would you rate your pain?"', difficulty: 'lätt' },
      { title: 'Diary of a Wimpy Kid: Rodrick Rules', definition: '"Rodrick rules."', difficulty: 'lätt' },
      { title: 'Guardians of the Galaxy Vol. 3', definition: '"We are Groot."', difficulty: 'lätt' },
      { title: 'Blink Twice', definition: '"Just blink."', difficulty: 'lätt' },
      { title: 'Hercules', definition: '"A true hero isn\'t measured by the size of his strength."', difficulty: 'lätt' },
      { title: 'Night at the Museum', definition: '"At night, history comes alive."', difficulty: 'lätt' },
      { title: 'Ford v Ferrari', definition: '"You build a car for Ford, and Ford builds a car for Ford."', difficulty: 'lätt' },
      { title: 'Thor', definition: '"Whosoever holds this hammer, if he be worthy."', difficulty: 'lätt' },
      { title: 'Madagascar', definition: '"I like to move it, move it."', difficulty: 'lätt' },
      { title: 'The Incredibles', definition: '"If everyone is super, then no one is."', difficulty: 'lätt' },
      { title: 'Guardians of the Galaxy Vol. 2', definition: '"I\'m Mary Poppins, y\'all!"', difficulty: 'lätt' },
      { title: 'Romeo + Juliet', definition: '"A rose by any other name would smell as sweet."', difficulty: 'lätt' },
      { title: 'The Parent Trap', definition: '"Twin powers!"', difficulty: 'lätt' },
      { title: 'Pirates of the Caribbean: Dead Man\'s Chest', definition: '"Why is the rum always gone?"', difficulty: 'lätt' },
      { title: 'The Ritual', definition: '"It was in the woods."', difficulty: 'lätt' },
      { title: 'Doctor Strange in the Multiverse of Madness', definition: '"Things just got out of hand."', difficulty: 'lätt' },
      { title: 'Grown Ups', definition: '"Some people never grow up."', difficulty: 'lätt' },
      { title: 'Rogue One: A Star Wars Story', definition: '"Rebellions are built on hope."', difficulty: 'lätt' },
      { title: 'Scooby-Doo', definition: '"Scooby-Doo, where are you?"', difficulty: 'lätt' },
      { title: 'Thor: The Dark World', definition: '"For Asgard."', difficulty: 'lätt' },
      { title: '2012', definition: '"When they tell you not to panic, that\'s when you panic."', difficulty: 'lätt' },
      { title: 'Magazine Dreams', definition: '"I just want to be seen."', difficulty: 'lätt' },
      { title: 'Carry-On', definition: '"One mistake can change everything."', difficulty: 'lätt' },
      { title: 'Creep 2', definition: '"You are not going to believe this."', difficulty: 'lätt' },
      { title: 'The Girl Next Door', definition: '"Sometimes the girl next door changes everything."', difficulty: 'lätt' },
      { title: 'Thor: Love and Thunder', definition: '"The only way forward is love."', difficulty: 'lätt' },
      { title: 'Billy Elliot', definition: '"I want to dance."', difficulty: 'lätt' },
      { title: 'Brothers', definition: '"No one comes back unchanged."', difficulty: 'lätt' },
      { title: 'Kung Fu Panda 4', definition: '"There is no secret ingredient."', difficulty: 'lätt' },
      { title: 'Rise of the Guardians', definition: '"Believe."', difficulty: 'lätt' },
      { title: 'Robots', definition: '"You can shine no matter what you\'re made of."', difficulty: 'lätt' },
      { title: 'Epic', definition: '"Some worlds are too small to see."', difficulty: 'lätt' },
      { title: 'Dr. No', definition: '"Bond, James Bond."', difficulty: 'lätt' },
      { title: 'The Creator', definition: '"The future is alive."', difficulty: 'lätt' },
      { title: 'Star Wars: The Last Jedi', definition: '"Let the past die. Kill it if you have to."', difficulty: 'lätt' },
      { title: 'Hoodwinked!', definition: '"You\'d be surprised how often the obvious is true."', difficulty: 'lätt' },
      { title: 'Open Season', definition: '"The wild is calling."', difficulty: 'lätt' },
      { title: 'Despicable Me 2', definition: '"It\'s so fluffy!"', difficulty: 'lätt' },
      { title: 'Aladdin', definition: '"A whole new world."', difficulty: 'lätt' },
      { title: 'The Game', definition: '"What the hell is going on?"', difficulty: 'lätt' },
      { title: 'The Iron Giant', definition: '"You are who you choose to be."', difficulty: 'lätt' },
      { title: 'The Incredible Hulk', definition: '"Don\'t make me angry."', difficulty: 'lätt' },
      { title: 'Sinister', definition: '"Once you see him, there\'s no going back."', difficulty: 'lätt' },
      { title: 'Star Wars: The Force Awakens', definition: '"The Force will be with you. Always."', difficulty: 'lätt' },
      { title: 'Rango', definition: '"You\'ve got to ask yourself one question: who are you?"', difficulty: 'lätt' },
      { title: 'Transformers', definition: '"Freedom is the right of all sentient beings."', difficulty: 'lätt' },
      { title: 'The Shawshank Redemption', definition: '"Get busy living, or get busy dying."', difficulty: 'lätt' },
      { title: 'Moonlight', definition: '"In moonlight, black boys look blue."', difficulty: 'lätt' },
      { title: 'Harakiri', definition: '"Honorable men are a lot of nonsense."', difficulty: 'lätt' },
      { title: 'Limitless', definition: '"This is your life on NZT."', difficulty: 'lätt' },
      { title: 'Interstellar', definition: '"Love is the one thing that transcends time and space."', difficulty: 'lätt' },
      { title: 'The Death of Stalin', definition: '"What is a committee? A committee is a suicide pact."', difficulty: 'lätt' },
      { title: 'Doctor Glas', definition: '"A human life is a labyrinth of secrets."', difficulty: 'lätt' },
      { title: 'Two Prosecutors', definition: '"Justice is only real when it survives power."', difficulty: 'lätt' },
      { title: 'GoodFellas', definition: '"As far back as I can remember, I always wanted to be a gangster."', difficulty: 'lätt' },
      { title: 'Snatch', definition: '"Do you know what nemesis means?"', difficulty: 'lätt' },
      { title: 'A Different Man', definition: '"Who are you when the mask is gone?"', difficulty: 'lätt' },
      { title: 'The Lord of the Rings: The Fellowship of the Ring', definition: '"One does not simply walk into Mordor."', difficulty: 'lätt' },
      { title: '1917', definition: '"This is not a game."', difficulty: 'lätt' },
      { title: 'Hamnet', definition: '"Grief is the price of love."', difficulty: 'lätt' },
      { title: 'Inglourious Basterds', definition: '"This is a bingo!"', difficulty: 'lätt' },
      { title: 'First Cow', definition: '"Friendship is a kind of survival."', difficulty: 'lätt' },
      { title: 'Holy Spider', definition: '"The city is full of hidden violence."', difficulty: 'lätt' },
      { title: 'Inside Man', definition: '"It\'s a perfect robbery."', difficulty: 'lätt' },
      { title: 'Society of the Snow', definition: '"We are still here."', difficulty: 'lätt' },
      { title: 'Nocturnal Animals', definition: '"You don\'t know what a man is capable of until he\'s hurt."', difficulty: 'lätt' },
      { title: 'Shogun', definition: '"A different world demands a different self."', difficulty: 'lätt' },
      { title: 'A Fish Called Wanda', definition: '"Don\'t call me stupid."', difficulty: 'lätt' },
      { title: 'The Basketball Diaries', definition: '"This is a diary of a teenager\'s descent."', difficulty: 'lätt' },
      { title: 'The Fighter', definition: '"It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving."', difficulty: 'lätt' },
      { title: 'The Dirt', definition: '"Sex, drugs, and rock and roll."', difficulty: 'lätt' },
      { title: 'Hereditary', definition: '"We suffer what our family suffers."', difficulty: 'lätt' },
      { title: 'Mississippi Burning', definition: '"The law is coming."', difficulty: 'lätt' },
      { title: 'War Dogs', definition: '"There\'s always a deal to be made."', difficulty: 'lätt' },
      { title: 'All of Us Are Dead', definition: '"Survive together."', difficulty: 'lätt' },
      { title: 'Project Hail Mary', definition: '"Science is the answer."', difficulty: 'lätt' },
      { title: 'The Goonies', definition: '"Goonies never say die!"', difficulty: 'lätt' },
      { title: 'Come and See', definition: '"War changes everything."', difficulty: 'lätt' },
      { title: 'Entergalactic', definition: '"Fall in love with the moment."', difficulty: 'lätt' },
      { title: 'Moana', definition: '"The ocean chose you."', difficulty: 'lätt' },
      { title: 'Captain Marvel', definition: '"Higher, further, faster, baby."', difficulty: 'lätt' },
      { title: 'The Hateful Eight', definition: '"There ain\'t no bigger crime than not turning the wagon around."', difficulty: 'lätt' },
      { title: 'The Terminator', definition: '"I\'ll be back."', difficulty: 'lätt' },
      { title: 'Despicable Me', definition: '"It\'s so fluffy!"', difficulty: 'lätt' },
      { title: 'Dunkirk', definition: '"Home."', difficulty: 'lätt' },
      { title: 'Home Alone', definition: '"Keep the change, ya filthy animal!"', difficulty: 'lätt' },
      { title: 'The Boy in the Striped Pyjamas', definition: '"Some things are better left unseen."', difficulty: 'lätt' },
      { title: 'Doctor Strange', definition: '"Dormammu, I\'ve come to bargain."', difficulty: 'lätt' },
      { title: 'Skyfall', definition: '"For England, James?"', difficulty: 'lätt' },
      { title: 'Tenet', definition: '"Don\'t try to understand it. Feel it."', difficulty: 'lätt' },
      { title: 'John Wick', definition: '"Yeah, I\'m thinking I\'m back."', difficulty: 'lätt' },
      { title: 'Saving Private Ryan', definition: '"Earn this."', difficulty: 'lätt' },
      { title: 'The Pianist', definition: '"I can play."', difficulty: 'lätt' },
      { title: 'Train to Busan', definition: '"Don\'t open that door!"', difficulty: 'lätt' },
      { title: 'Hacksaw Ridge', definition: '"Lord, please help me get one more."', difficulty: 'lätt' },
      { title: 'Anatomy of a Fall', definition: '"The truth is a matter of perspective."', difficulty: 'lätt' },
      { title: 'Coach Carter', definition: '"Our deepest fear is that we are powerful beyond measure."', difficulty: 'lätt' },
      { title: 'Godzilla Minus One', definition: '"We have to live."', difficulty: 'lätt' },
      { title: 'War of the Worlds', definition: '"This is not a war any of us started."', difficulty: 'lätt' },
      { title: 'Mission: Impossible', definition: '"Your mission, should you choose to accept it..."', difficulty: 'lätt' },
      { title: 'Jarhead', definition: '"Welcome to the suck."', difficulty: 'lätt' },
      { title: 'A Fistful of Dollars', definition: '"My mistake. Four coffins."', difficulty: 'lätt' },
      { title: 'Die Hard', definition: '"Yippee-ki-yay."', difficulty: 'lätt' },
      { title: 'Indiana Jones and the Temple of Doom', definition: '"Fortune and glory, kid."', difficulty: 'lätt' },
      { title: 'Pixels', definition: '"Game on."', difficulty: 'lätt' },
      { title: 'Black Panther: Wakanda Forever', definition: '"Show them who we are."', difficulty: 'lätt' },
      { title: 'World War Z', definition: '"Be safe. Be strong. Be human."', difficulty: 'lätt' },
      { title: 'Chernobyl', definition: '"What is the cost of lies?"', difficulty: 'lätt' },
      { title: 'Pacific Rim', definition: '"Today, we are cancelling the apocalypse."', difficulty: 'lätt' },
      { title: 'I Am Legend', definition: '"I can save everybody."', difficulty: 'lätt' },
      { title: 'Shang-Chi and the Legend of the Ten Rings', definition: '"You are a product of all who came before you."', difficulty: 'lätt' },
      { title: 'Back to the Future Part II', definition: '"Great Scott!"', difficulty: 'lätt' },
      { title: 'Men in Black', definition: '"The universe is big, but you don\'t have to be."', difficulty: 'lätt' },
      { title: 'Rocky', definition: '"Yo, Adrian!"', difficulty: 'lätt' },
      { title: 'Terminator 2: Judgment Day', definition: '"Hasta la vista, baby."', difficulty: 'lätt' },
      { title: 'Fury', definition: '"Ideals are peaceful. History is violent."', difficulty: 'lätt' },
      { title: 'The Sound of Music', definition: '"The hills are alive with the sound of music."', difficulty: 'lätt' },
      { title: 'Raiders of the Lost Ark', definition: '"Snakes. Why did it have to be snakes?"', difficulty: 'lätt' },
      { title: 'Saw', definition: '"Game over."', difficulty: 'lätt' },
      { title: 'Ocean\'s Eleven', definition: '"You gonna do something or stand there and bleed?"', difficulty: 'lätt' },
      { title: 'Rush Hour', definition: '"Do you understand the words coming out of my mouth?"', difficulty: 'lätt' },
      { title: 'Civil War', definition: '"Stay alive."', difficulty: 'lätt' },
    ],
    'Karaktärer': [
      { title: 'The Seat', definition: 'beroende på filmversionen, ofta få rollfigurer centrerade kring huvudpersonen', difficulty: 'lätt' },
      { title: 'Torrente: The Dumb Arm of the Law', definition: 'Torrente, Rafi, Amparito, Sebas, housemates/criminals', difficulty: 'lätt' },
      { title: 'Johnny English Strikes Again', definition: 'Johnny English, Bough, Ophelia, Pegasus, Fiona', difficulty: 'lätt' },
      { title: 'Johnny English Reborn', definition: 'Johnny English, Bough, Tong, Ambrose, Kate Sumner', difficulty: 'lätt' },
      { title: 'Johnny English', definition: 'Johnny English, Bough, Pascal Sauvage, Lorna Campbell, Pegasus', difficulty: 'lätt' },
      { title: 'Robin Hood: Men in Tights', definition: 'Robin Hood, Little John, Marian, Friar Tuck, Sheriff of Rottingham', difficulty: 'lätt' },
      { title: 'Wolfs', definition: 'Jack, Nick, Margaret, the client, the police contact', difficulty: 'lätt' },
      { title: 'The Man with the Iron Fists 2', definition: 'Thaddeus, Li Kung, Master Ho, Lady Silk, Lord Pi', difficulty: 'lätt' },
      { title: 'The Man with the Iron Fists', definition: 'Blacksmith, Brass Body, Lady Silk, Jack Knife, Silver Lion', difficulty: 'lätt' },
      { title: 'Piece By Piece', definition: 'Pharrell Williams, family, collaborators, mentors, industry figures', difficulty: 'lätt' },
      { title: 'Kiss the Girls', definition: 'Alex Cross, Kate McTiernan, Casanova, The Spider, Naomi', difficulty: 'lätt' },
      { title: 'Nikita', definition: 'Nikita, Bob, Marco, Amande, Victor', difficulty: 'lätt' },
      { title: 'The Ridiculous 6', definition: 'Tommy, Clem, Chico, Lil Pete, Herm', difficulty: 'lätt' },
      { title: 'You Don\'t Mess with the Zohan', definition: 'Zohan, Dalia, Phyllis, Salim, Phantom', difficulty: 'lätt' },
      { title: 'Home Alone 2: Lost in New York', definition: 'Kevin McCallister, Harry, Marv, Peter McCallister, Kate McCallister', difficulty: 'lätt' },
      { title: 'Night at the Museum: Battle of the Smithsonian', definition: 'Larry, Amelia, Kahmunrah, Jedediah, Octavius', difficulty: 'lätt' },
      { title: 'Ricky Stanicky', definition: 'Dean, JT, Wes, Ricky Stanicky, gig workers', difficulty: 'lätt' },
      { title: 'Grown Ups 2', definition: 'Lenny, Eric, Kurt, Marcus, Roxanne', difficulty: 'lätt' },
      { title: 'How to Train Your Dragon 2', definition: 'Hiccup, Toothless, Astrid, Stoick, Valka', difficulty: 'lätt' },
      { title: 'Kung Fu Panda 2', definition: 'Po, Shifu, Tigress, Lord Shen, Monkey', difficulty: 'lätt' },
      { title: 'Smile', definition: 'Rose, Joel, Trevor, Dr. Northcott, Laura', difficulty: 'lätt' },
      { title: 'Pirates of the Caribbean: At World\'s End', definition: 'Jack Sparrow, Elizabeth Swann, Will Turner, Barbossa, Davy Jones', difficulty: 'lätt' },
      { title: 'Toy Story 2', definition: 'Woody, Buzz Lightyear, Jessie, Prospector, Rex', difficulty: 'lätt' },
      { title: 'Encanto', definition: 'Mirabel, Abuela Alma, Bruno, Isabela, Luisa', difficulty: 'lätt' },
      { title: 'Creep', definition: 'Aaron, Josef, Peachfuzz, Sarah, the camera', difficulty: 'lätt' },
      { title: 'Big Hero 6', definition: 'Hiro, Baymax, Tadashi, GoGo, Wasabi', difficulty: 'lätt' },
      { title: 'Diary of a Wimpy Kid: Rodrick Rules', definition: 'Greg, Rodrick, Manny, Susan, Frank', difficulty: 'lätt' },
      { title: 'Guardians of the Galaxy Vol. 3', definition: 'Peter Quill, Rocket, Gamora, Nebula, Groot', difficulty: 'lätt' },
      { title: 'Blink Twice', definition: 'Frida, Slater, Sarah, Jess, Cody', difficulty: 'lätt' },
      { title: 'Hercules', definition: 'Hercules, Megara, Hades, Phil, Zeus', difficulty: 'lätt' },
      { title: 'Night at the Museum', definition: 'Larry, Teddy Roosevelt, Sacagawea, Jedediah, Octavius', difficulty: 'lätt' },
      { title: 'Ford v Ferrari', definition: 'Carroll Shelby, Ken Miles, Lee Iacocca, Mollie Miles, Leo Beebe', difficulty: 'lätt' },
      { title: 'Thor', definition: 'Thor, Loki, Jane Foster, Odin, Erik Selvig', difficulty: 'lätt' },
      { title: 'Madagascar', definition: 'Alex, Marty, Melman, Gloria, the penguins', difficulty: 'lätt' },
      { title: 'The Incredibles', definition: 'Mr. Incredible, Elastigirl, Violet, Dash, Jack-Jack', difficulty: 'lätt' },
      { title: 'Guardians of the Galaxy Vol. 2', definition: 'Peter Quill, Rocket, Gamora, Drax, Yondu', difficulty: 'lätt' },
      { title: 'Romeo + Juliet', definition: 'Romeo, Juliet, Tybalt, Mercutio, Friar Laurence', difficulty: 'lätt' },
      { title: 'The Parent Trap', definition: 'Hallie, Annie, Nick, Elizabeth, Meredith', difficulty: 'lätt' },
      { title: 'Pirates of the Caribbean: Dead Man\'s Chest', definition: 'Jack Sparrow, Will Turner, Elizabeth Swann, Davy Jones, Bootstrap Bill', difficulty: 'lätt' },
      { title: 'The Ritual', definition: 'Luke, Phil, Hutch, Dom, Rob', difficulty: 'lätt' },
      { title: 'Doctor Strange in the Multiverse of Madness', definition: 'Doctor Strange, Wanda Maximoff, America Chavez, Wong, Christine Palmer', difficulty: 'lätt' },
      { title: 'Grown Ups', definition: 'Lenny, Eric, Kurt, Marcus, Rob', difficulty: 'lätt' },
      { title: 'Rogue One: A Star Wars Story', definition: 'Jyn Erso, Cassian Andor, K-2SO, Chirrut Îmwe, Baze Malbus', difficulty: 'lätt' },
      { title: 'Scooby-Doo', definition: 'Fred, Daphne, Velma, Shaggy, Scooby-Doo', difficulty: 'lätt' },
      { title: 'Thor: The Dark World', definition: 'Thor, Jane Foster, Loki, Malekith, Odin', difficulty: 'lätt' },
      { title: '2012', definition: 'Jackson Curtis, Kate Curtis, Charlie Frost, Adrian Helmsley, Yuri Karpov', difficulty: 'lätt' },
      { title: 'Magazine Dreams', definition: 'Killian Maddox, Jessie, Jim, his grandfather, gym rivals', difficulty: 'lätt' },
      { title: 'Carry-On', definition: 'Ethan Kopek, Nora Parisi, the Traveler, Jason Noble, airport staff', difficulty: 'lätt' },
      { title: 'Creep 2', definition: 'Sara, Josef, Dave, Angela, the podcast audience', difficulty: 'lätt' },
      { title: 'The Girl Next Door', definition: 'Matthew Kidman, Danielle, Eli, Klitz, Kelly', difficulty: 'lätt' },
      { title: 'Thor: Love and Thunder', definition: 'Thor, Jane Foster, Gorr, Valkyrie, Korg', difficulty: 'lätt' },
      { title: 'Billy Elliot', definition: 'Billy Elliot, Jackie, Tony, Mrs. Wilkinson, Michael', difficulty: 'lätt' },
      { title: 'Brothers', definition: 'Sam Cahill, Grace Cahill, Tommy Cahill, Isabel, the children', difficulty: 'lätt' },
      { title: 'Kung Fu Panda 4', definition: 'Po, Zhen, The Chameleon, Master Shifu, Furious Five', difficulty: 'lätt' },
      { title: 'Rise of the Guardians', definition: 'Jack Frost, North, Tooth, Bunnymund, Sandman', difficulty: 'lätt' },
      { title: 'Robots', definition: 'Rodney Copperbottom, Fender, Piper, Bigweld, Ratchet', difficulty: 'lätt' },
      { title: 'Epic', definition: 'M.K., Ronin, Nod, Queen Tara, Bomba', difficulty: 'lätt' },
      { title: 'Dr. No', definition: 'James Bond, Honey Ryder, Dr. No, Felix Leiter, Miss Moneypenny', difficulty: 'lätt' },
      { title: 'The Creator', definition: 'Joshua, Alfie, Maya, Colonel Howell, Harun', difficulty: 'lätt' },
      { title: 'Star Wars: The Last Jedi', definition: 'Rey, Luke Skywalker, Kylo Ren, Leia Organa, Finn', difficulty: 'lätt' },
      { title: 'Hoodwinked!', definition: 'Red, Wolf, Grandma, Woodsman, Nicky Flippers', difficulty: 'lätt' },
      { title: 'Open Season', definition: 'Boog, Elliot, Beth, Shaw, McSquizzy', difficulty: 'lätt' },
      { title: 'Despicable Me 2', definition: 'Gru, Lucy, Margo, Edith, Agnes', difficulty: 'lätt' },
      { title: 'Aladdin', definition: 'Aladdin, Jasmine, Genie, Jafar, Abu', difficulty: 'lätt' },
      { title: 'The Game', definition: 'Nicholas Van Orton, Conrad, Christine, Jim Feingold, Anna', difficulty: 'lätt' },
      { title: 'The Iron Giant', definition: 'Hogarth Hughes, The Iron Giant, Annie Hughes, Dean McCoppin, Kent Mansley', difficulty: 'lätt' },
      { title: 'The Incredible Hulk', definition: 'Bruce Banner, Betty Ross, Thunderbolt Ross, Emil Blonsky, Samuel Sterns', difficulty: 'lätt' },
      { title: 'Sinister', definition: 'Ellison Oswalt, Tracy Oswalt, Ashley Oswalt, the deputy, Bughuul', difficulty: 'lätt' },
      { title: 'Star Wars: The Force Awakens', definition: 'Rey, Finn, Poe Dameron, Kylo Ren, Han Solo', difficulty: 'lätt' },
      { title: 'Rango', definition: 'Rango, Beans, Jake, Spirit of the West, Priscilla', difficulty: 'lätt' },
      { title: 'Transformers', definition: 'Sam Witwicky, Mikaela Banes, Optimus Prime, Bumblebee, Megatron', difficulty: 'lätt' },
      { title: 'The Shawshank Redemption', definition: 'Andy Dufresne, Red, Warden Norton, Brooks Hatlen, Captain Hadley', difficulty: 'lätt' },
      { title: 'Moonlight', definition: 'Chiron, Paula, Juan, Kevin, Teresa', difficulty: 'lätt' },
      { title: 'Harakiri', definition: 'Hanshiro Tsugumo, Motome Chijiiwa, Saito, Hikokuro, Ii', difficulty: 'lätt' },
      { title: 'Limitless', definition: 'Eddie Morra, Vernon, Lindy, Carl Van Loon, Melissa', difficulty: 'lätt' },
      { title: 'Interstellar', definition: 'Cooper, Murph, Brand, Dr. Mann, TARS', difficulty: 'lätt' },
      { title: 'The Death of Stalin', definition: 'Nikita Khrushchev, Lavrentiy Beria, Georgy Malenkov, Vasily Stalin, Molotov', difficulty: 'lätt' },
      { title: 'Doctor Glas', definition: 'Doctor Glas, Helga Gregorius, Pastor Gregorius, Markel, Mrs. Glas', difficulty: 'lätt' },
      { title: 'Two Prosecutors', definition: 'Alexander Kornyev, prison officials, party agents, family members, local authorities', difficulty: 'lätt' },
      { title: 'GoodFellas', definition: 'Henry Hill, Jimmy Conway, Tommy DeVito, Karen Hill, Paulie Cicero', difficulty: 'lätt' },
      { title: 'Snatch', definition: 'Turkish, Tommy, Brick Top, Mickey O\'Neil, Franky Four Fingers', difficulty: 'lätt' },
      { title: 'A Different Man', definition: 'Edward, Ingrid, Oswald, Guy, Rebecca', difficulty: 'lätt' },
      { title: 'The Lord of the Rings: The Fellowship of the Ring', definition: 'Frodo, Sam, Gandalf, Aragorn, Boromir', difficulty: 'lätt' },
      { title: '1917', definition: 'Schofield, Blake, Lieutenant Blake, Colonel Mackenzie, Blake\'s brother', difficulty: 'lätt' },
      { title: 'Hamnet', definition: 'Agnes, William, Hamnet, Judith, Susanna', difficulty: 'lätt' },
      { title: 'Inglourious Basterds', definition: 'Shosanna, Aldo Raine, Hans Landa, Bridget von Hammersmark, Hugo Stiglitz', difficulty: 'lätt' },
      { title: 'First Cow', definition: 'Cookie, King-Lu, Chief Factor, local trappers, the cow owner', difficulty: 'lätt' },
      { title: 'Holy Spider', definition: 'Rahimi, Saeed Hanaei, journalist network, police investigators, victims\' families', difficulty: 'lätt' },
      { title: 'Inside Man', definition: 'Detective Frazier, Dalton Russell, Madeleine White, Captain John Darius, Bank Chairman', difficulty: 'lätt' },
      { title: 'Society of the Snow', definition: 'Numa, Canessa, Paez, Roberto, Antonio', difficulty: 'lätt' },
      { title: 'Nocturnal Animals', definition: 'Susan, Edward, Tony, Helen, Bobby Andes', difficulty: 'lätt' },
      { title: 'Shogun', definition: 'John Blackthorne, Lord Toranaga, Lady Mariko, Ishido, Yabushige', difficulty: 'lätt' },
      { title: 'A Fish Called Wanda', definition: 'Wanda, Archie Leach, Otto, Ken, George', difficulty: 'lätt' },
      { title: 'The Basketball Diaries', definition: 'Jim Carroll, Mickey, Neutron, Pedro, Reggie', difficulty: 'lätt' },
      { title: 'The Fighter', definition: 'Micky Ward, Dicky Eklund, Charlene Fleming, Alice Ward, Arthur', difficulty: 'lätt' },
      { title: 'The Dirt', definition: 'Vince Neil, Nikki Sixx, Tommy Lee, Mick Mars, Pamela', difficulty: 'lätt' },
      { title: 'Hereditary', definition: 'Annie, Peter, Charlie, Steve, Joan', difficulty: 'lätt' },
      { title: 'Mississippi Burning', definition: 'Agent Ward, Agent Anderson, Deputy Pell, Mrs. Pell, Klansmen', difficulty: 'lätt' },
      { title: 'War Dogs', definition: 'Efraim, David, Iz, Henry, Marlboro', difficulty: 'lätt' },
      { title: 'All of Us Are Dead', definition: 'Nam On-jo, Lee Cheong-san, Yoon Gwi-nam, Lee Su-hyeok, Choi Nam-ra', difficulty: 'lätt' },
      { title: 'Project Hail Mary', definition: 'Ryland Grace, Rocky, Eva Stratt, Yao, Dmitri', difficulty: 'lätt' },
      { title: 'The Goonies', definition: 'Mikey, Mouth, Data, Chunk, Brand', difficulty: 'lätt' },
      { title: 'Come and See', definition: 'Florya, Glasha, the partisans, German officers, villagers', difficulty: 'lätt' },
      { title: 'Entergalactic', definition: 'Jabari, Meadow, Karina, Jimmy, Lenox', difficulty: 'lätt' },
      { title: 'Moana', definition: 'Moana, Maui, Tala, Chief Tui, Te Fiti', difficulty: 'lätt' },
      { title: 'Captain Marvel', definition: 'Carol Danvers, Nick Fury, Talos, Maria Rambeau, Yon-Rogg', difficulty: 'lätt' },
      { title: 'The Hateful Eight', definition: 'John Ruth, Daisy Domergue, Major Warren, Chris Mannix, Oswaldo Mobray', difficulty: 'lätt' },
      { title: 'The Terminator', definition: 'Sarah Connor, The Terminator, Kyle Reese, Detective Vukovich, Ginger', difficulty: 'lätt' },
      { title: 'Despicable Me', definition: 'Gru, Margo, Edith, Agnes, Dr. Nefario', difficulty: 'lätt' },
      { title: 'Dunkirk', definition: 'Tommy, Farrier, Dawson, Alex, Collins', difficulty: 'lätt' },
      { title: 'Home Alone', definition: 'Kevin, Harry, Marv, Kate, Peter', difficulty: 'lätt' },
      { title: 'The Boy in the Striped Pyjamas', definition: 'Bruno, Shmuel, Father, Mother, Gretel', difficulty: 'lätt' },
      { title: 'Doctor Strange', definition: 'Stephen Strange, Wong, Ancient One, Mordo, Christine Palmer', difficulty: 'lätt' },
      { title: 'Skyfall', definition: 'James Bond, M, Silva, Q, Eve Moneypenny', difficulty: 'lätt' },
      { title: 'Tenet', definition: 'The Protagonist, Neil, Kat, Andrei Sator, Priya', difficulty: 'lätt' },
      { title: 'John Wick', definition: 'John Wick, Viggo Tarasov, Winston, Marcus, Daisy', difficulty: 'lätt' },
      { title: 'Saving Private Ryan', definition: 'Captain Miller, Private Ryan, Sergeant Horvath, Private Jackson, Private Reiben', difficulty: 'lätt' },
      { title: 'The Pianist', definition: 'Wladyslaw Szpilman, Dorota, Captain Hosenfeld, Szpilman\'s family, Jurek', difficulty: 'lätt' },
      { title: 'Train to Busan', definition: 'Seok-woo, Su-an, Sang-hwa, Seong-kyeong, Yong-guk', difficulty: 'lätt' },
      { title: 'Hacksaw Ridge', definition: 'Desmond Doss, Dorothy, Smitty, Captain Glover, Sergeant Howell', difficulty: 'lätt' },
      { title: 'Anatomy of a Fall', definition: 'Sandra, Samuel, Daniel, the judge, the lawyer', difficulty: 'lätt' },
      { title: 'Coach Carter', definition: 'Ken Carter, Timo Cruz, Kenyon Stone, Damien Carter, Junior Battle', difficulty: 'lätt' },
      { title: 'Godzilla Minus One', definition: 'Koichi Shikishima, Noriko Oishi, Akiko, Captain Tachibana, Sumiko Ota', difficulty: 'lätt' },
      { title: 'War of the Worlds', definition: 'Ray Ferrier, Rachel Ferrier, Robbie Ferrier, Harlan Ogilvy, Mary Ann', difficulty: 'lätt' },
      { title: 'Mission: Impossible', definition: 'Ethan Hunt, Jim Phelps, Claire Phelps, Luther Stickell, Franz Krieger', difficulty: 'lätt' },
      { title: 'Jarhead', definition: 'Anthony Swofford, Troy, Peter, Fergus, Major Schumann', difficulty: 'lätt' },
      { title: 'A Fistful of Dollars', definition: 'Joe, Ramon Rojo, Esteban Rojo, Marisol, Silvanito', difficulty: 'lätt' },
      { title: 'Die Hard', definition: 'John McClane, Hans Gruber, Holly Gennaro, Al Powell, Karl', difficulty: 'lätt' },
      { title: 'Indiana Jones and the Temple of Doom', definition: 'Indiana Jones, Short Round, Willie Scott, Mola Ram, Chattar Lal', difficulty: 'lätt' },
      { title: 'Pixels', definition: 'Sam Brenner, Cooper, Ludlow, President Cooper, Q*bert', difficulty: 'lätt' },
      { title: 'Black Panther: Wakanda Forever', definition: 'Shuri, Ramonda, Nakia, Okoye, Namor', difficulty: 'lätt' },
      { title: 'World War Z', definition: 'Gerry Lane, Karin Lane, Rachel Lane, Thierry Umutoni, Seger', difficulty: 'lätt' },
      { title: 'Chernobyl', definition: 'Valery Legasov, Boris Shcherbina, Ulana Khomyuk, Anatoly Dyatlov, Lyudmilla Ignatenko', difficulty: 'lätt' },
      { title: 'Pacific Rim', definition: 'Raleigh Becket, Mako Mori, Stacker Pentecost, Newton Geiszler, Hermann Gottlieb', difficulty: 'lätt' },
      { title: 'I Am Legend', definition: 'Robert Neville, Sam, Anna, Ethan, infected humans', difficulty: 'lätt' },
      { title: 'Shang-Chi and the Legend of the Ten Rings', definition: 'Shang-Chi, Katy, Wenwu, Xialing, Morris', difficulty: 'lätt' },
      { title: 'Back to the Future Part II', definition: 'Marty McFly, Doc Brown, Jennifer Parker, Biff Tannen, Lorraine McFly', difficulty: 'lätt' },
      { title: 'Men in Black', definition: 'Agent J, Agent K, Edgar, Zed, Dr. Laurel Weaver', difficulty: 'lätt' },
      { title: 'Rocky', definition: 'Rocky Balboa, Adrian, Mickey, Apollo Creed, Paulie', difficulty: 'lätt' },
      { title: 'Terminator 2: Judgment Day', definition: 'Sarah Connor, John Connor, T-800, T-1000, Dyson', difficulty: 'lätt' },
      { title: 'Fury', definition: 'Wardaddy, Bible, Coon-Ass, Gordo, Norman', difficulty: 'lätt' },
      { title: 'The Sound of Music', definition: 'Maria, Captain von Trapp, Liesl, Rolf, Max', difficulty: 'lätt' },
      { title: 'Raiders of the Lost Ark', definition: 'Indiana Jones, Marion Ravenwood, Sallah, Belloq, Toht', difficulty: 'lätt' },
      { title: 'Saw', definition: 'Adam, Lawrence Gordon, Jigsaw, Tapp, Amanda', difficulty: 'lätt' },
      { title: 'Ocean\'s Eleven', definition: 'Danny Ocean, Rusty Ryan, Linus Caldwell, Terry Benedict, Tess Ocean', difficulty: 'lätt' },
      { title: 'Rush Hour', definition: 'Detective Lee, Detective Carter, Juntao, Solon Han, Consul Han', difficulty: 'lätt' },
      { title: 'Civil War', definition: 'Lee, Jessie, Joel, Sammy, the President', difficulty: 'lätt' },
    ],
    'Skådespelare': [
      { title: 'Ayo Edebiri', definition: 'Amerikansk skådespelerska – The Bear, Bottoms, Abbott Elementary.', difficulty: 'lätt' },
      { title: 'Mikey Madison', definition: 'Amerikansk skådespelerska – Anora, Scream, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Riley Keough', definition: 'Amerikansk skådespelerska – Daisy Jones & The Six, Mad Max: Fury Road.', difficulty: 'lätt' },
      { title: 'Stephanie Hsu', definition: 'Amerikansk skådespelerska – Everything Everywhere All at Once, Mrs. Maisel.', difficulty: 'lätt' },
      { title: 'LaKeith Stanfield', definition: 'Amerikansk skådespelare – Judas and the Black Messiah, Atlanta.', difficulty: 'lätt' },
      { title: 'Jharrel Jerome', definition: 'Amerikansk skådespelare – Moonlight, When They See Us.', difficulty: 'lätt' },
      { title: 'Danielle Deadwyler', definition: 'Amerikansk skådespelerska – Till, The Piano Lesson.', difficulty: 'lätt' },
      { title: 'Juno Temple', definition: 'Engelsk skådespelerska – Ted Lasso, Fargo.', difficulty: 'lätt' },
      { title: 'Rebecca Ferguson', definition: 'Svensk skådespelerska – Dune, Mission: Impossible, Silo.', difficulty: 'lätt' },
      { title: 'Harris Dickinson', definition: 'Engelsk skådespelare – Triangle of Sadness, The Iron Claw.', difficulty: 'lätt' },
      { title: 'Lily James', definition: 'Engelsk skådespelerska – Pam & Tommy, Cinderella, Baby Driver.', difficulty: 'lätt' },
      { title: 'Himesh Patel', definition: 'Engelsk skådespelare – Tenet, Yesterday, Station Eleven.', difficulty: 'lätt' },
      { title: 'Wunmi Mosaku', definition: 'Brittisk skådespelerska – Lovecraft Country, Loki, His House.', difficulty: 'lätt' },
      { title: 'Kerry Condon', definition: 'Irländsk skådespelerska – The Banshees of Inisherin, Better Call Saul.', difficulty: 'lätt' },
      { title: 'Tom Blyth', definition: 'Engelsk skådespelare – The Hunger Games: Ballad of Songbirds & Snakes.', difficulty: 'lätt' },
      { title: 'Jeremy Allen White', definition: 'Amerikansk skådespelare – The Bear, Shameless, The Iron Claw.', difficulty: 'lätt' },
      { title: 'Dacre Montgomery', definition: 'Australisk skådespelare – Stranger Things, Elvis.', difficulty: 'lätt' },
      { title: 'Hunter Schafer', definition: 'Amerikansk skådespelerska – Euphoria, Hunger Games-prequel.', difficulty: 'lätt' },
      { title: 'Dominic Sessa', definition: 'Amerikansk skådespelare – The Holdovers.', difficulty: 'lätt' },
      { title: 'Ariana DeBose', definition: 'Amerikansk skådespelerska – West Side Story, Argylle.', difficulty: 'lätt' },
      { title: 'Maya Hawke', definition: 'Amerikansk skådespelerska – Stranger Things, Asteroid City.', difficulty: 'lätt' },
      { title: 'Seth Rogen', definition: 'Kanadensisk skådespelare – Superbad, Pineapple Express, The Fabelmans.', difficulty: 'lätt' },
      { title: 'Maya Rudolph', definition: 'Amerikansk skådespelerska – Bridesmaids, Loot, SNL.', difficulty: 'lätt' },
      { title: 'Donald Glover', definition: 'Amerikansk skådespelare – Atlanta, The Lion King, Community.', difficulty: 'lätt' },
      { title: 'Christopher Walken', definition: 'Amerikansk skådespelare – The Deer Hunter, Catch Me If You Can.', difficulty: 'lätt' },
      { title: 'Gene Hackman', definition: 'Amerikansk skådespelare – The French Connection, Unforgiven.', difficulty: 'lätt' },
      { title: 'Robert Duvall', definition: 'Amerikansk skådespelare – The Godfather, Apocalypse Now.', difficulty: 'lätt' },
      { title: 'Diane Keaton', definition: 'Amerikansk skådespelerska – Annie Hall, The Godfather.', difficulty: 'lätt' },
      { title: 'Jessica Lange', definition: 'Amerikansk skådespelerska – Tootsie, American Horror Story.', difficulty: 'lätt' },
      { title: 'Faye Dunaway', definition: 'Amerikansk skådespelerska – Network, Chinatown, Bonnie and Clyde.', difficulty: 'lätt' },
      { title: 'Sissy Spacek', definition: 'Amerikansk skådespelerska – Carrie, Coal Miner\'s Daughter.', difficulty: 'lätt' },
      { title: 'Ellen Burstyn', definition: 'Amerikansk skådespelerska – The Exorcist, Requiem for a Dream.', difficulty: 'lätt' },
      { title: 'Kim Go-eun', definition: 'Sydkoreansk skådespelerska – The King: Eternal Monarch, Exhuma.', difficulty: 'lätt' },
      { title: 'Fahadh Faasil', definition: 'Indisk skådespelare – Pushpa, Kumbalangi Nights.', difficulty: 'lätt' },
      { title: 'Vijay Sethupathi', definition: 'Indisk skådespelare – 96, Vikram Vedha.', difficulty: 'lätt' },
      { title: 'Dhanush', definition: 'Indisk skådespelare – Asuran, Raanjhanaa.', difficulty: 'lätt' },
      { title: 'Ayushmann Khurrana', definition: 'Indisk skådespelare – Andhadhun, Article 15.', difficulty: 'lätt' },
      { title: 'Jesse Eisenberg', definition: 'Amerikansk skådespelare – The Social Network, A Real Pain.', difficulty: 'lätt' },
      { title: 'Michael Stuhlbarg', definition: 'Amerikansk skådespelare – Call Me by Your Name, A Serious Man.', difficulty: 'lätt' },
      { title: 'Ben Mendelsohn', definition: 'Australisk skådespelare – Rogue One, Bloodline.', difficulty: 'lätt' },
      { title: 'Tessa Thompson', definition: 'Amerikansk skådespelerska – Creed, Thor: Ragnarok.', difficulty: 'lätt' },
      { title: 'Rosamund Pike', definition: 'Engelsk skådespelerska – Gone Girl, Saltburn.', difficulty: 'lätt' },
      { title: 'Janelle Monáe', definition: 'Amerikansk skådespelerska – Glass Onion, Hidden Figures.', difficulty: 'lätt' },
      { title: 'Yahya Abdul-Mateen II', definition: 'Amerikansk skådespelare – Watchmen, Aquaman, Candyman.', difficulty: 'lätt' },
      { title: 'Winona Ryder', definition: 'Amerikansk skådespelerska – Beetlejuice, Stranger Things.', difficulty: 'lätt' },
      { title: 'Marisa Tomei', definition: 'Amerikansk skådespelerska – My Cousin Vinny, The Wrestler.', difficulty: 'lätt' },
      { title: 'Maggie Gyllenhaal', definition: 'Amerikansk skådespelerska – The Dark Knight, The Lost Daughter.', difficulty: 'lätt' },
      { title: 'Rosario Dawson', definition: 'Amerikansk skådespelerska – Sin City, Ahsoka.', difficulty: 'lätt' },
      { title: 'Keke Palmer', definition: 'Amerikansk skådespelerska – Nope, Hustlers.', difficulty: 'lätt' },
      { title: 'Sophie Turner', definition: 'Engelsk skådespelerska – Game of Thrones, X-Men: Apocalypse.', difficulty: 'lätt' },
      { title: 'Maisie Williams', definition: 'Engelsk skådespelerska – Game of Thrones.', difficulty: 'lätt' },
      { title: 'Mia Goth', definition: 'Engelsk skådespelerska – Pearl, X, Suspiria.', difficulty: 'lätt' },
      { title: 'Gwendoline Christie', definition: 'Engelsk skådespelerska – Game of Thrones, Wednesday.', difficulty: 'lätt' },
      { title: 'Hailee Steinfeld', definition: 'Amerikansk skådespelerska – True Grit, Hawkeye, Dickinson.', difficulty: 'lätt' },
      { title: 'Amandla Stenberg', definition: 'Amerikansk skådespelerska – The Hate U Give, The Acolyte.', difficulty: 'lätt' },
      { title: 'Storm Reid', definition: 'Amerikansk skådespelerska – Euphoria, The Last of Us.', difficulty: 'lätt' },
      { title: 'Jessie Buckley', definition: 'Irländsk skådespelerska – The Lost Daughter, Fargo.', difficulty: 'lätt' },
      { title: 'Emily Watson', definition: 'Engelsk skådespelerska – Chernobyl, Breaking the Waves.', difficulty: 'lätt' },
      { title: 'Samantha Morton', definition: 'Engelsk skådespelerska – Minority Report, The Walking Dead.', difficulty: 'lätt' },
      { title: 'Yvonne Strahovski', definition: 'Australisk skådespelerska – The Handmaid\'s Tale, Dexter.', difficulty: 'lätt' },
      { title: 'Octavia Spencer', definition: 'Amerikansk skådespelerska – The Help, Hidden Figures.', difficulty: 'lätt' },
      { title: 'Angela Bassett', definition: 'Amerikansk skådespelerska – Black Panther, 9-1-1.', difficulty: 'lätt' },
      { title: 'Taraji P. Henson', definition: 'Amerikansk skådespelerska – Hidden Figures, Empire.', difficulty: 'lätt' },
      { title: 'Gabrielle Union', definition: 'Amerikansk skådespelerska – Bring It On, Bad Boys II.', difficulty: 'lätt' },
      { title: 'Regina Hall', definition: 'Amerikansk skådespelerska – Girls Trip, Support the Girls.', difficulty: 'lätt' },
      { title: 'Naomie Harris', definition: 'Brittisk skådespelerska – Moonlight, Skyfall.', difficulty: 'lätt' },
      { title: 'Thandiwe Newton', definition: 'Engelsk skådespelerska – Westworld, Crash.', difficulty: 'lätt' },
      { title: 'Sophie Okonedo', definition: 'Engelsk skådespelerska – Hotel Rwanda, Slow Horses.', difficulty: 'lätt' },
      { title: 'Kathryn Bigelow', definition: 'Oscarsbelönad regissör – The Hurt Locker, Zero Dark Thirty.', difficulty: 'lätt' },
      { title: 'Keanu Reeves', definition: 'Kanadensisk skådespelare – The Matrix, John Wick. Global actionstjärna.', difficulty: 'lätt' },
      { title: 'Leonardo DiCaprio', definition: 'Amerikansk skådespelare – Titanic, Inception, The Revenant.', difficulty: 'lätt' },
      { title: 'Denzel Washington', definition: 'Amerikansk skådespelare – Training Day, Malcolm X, Fences.', difficulty: 'lätt' },
      { title: 'Meryl Streep', definition: 'Amerikansk skådespelerska – rekordmånga Oscar-nomineringar.', difficulty: 'lätt' },
      { title: 'Tom Hanks', definition: 'Amerikansk skådespelare – Forrest Gump, Saving Private Ryan, Cast Away.', difficulty: 'lätt' },
      { title: 'Robert De Niro', definition: 'Amerikansk skådespelare – Taxi Driver, Raging Bull, The Godfather Part II.', difficulty: 'lätt' },
      { title: 'Al Pacino', definition: 'Amerikansk skådespelare – The Godfather, Scarface, Scent of a Woman.', difficulty: 'lätt' },
      { title: 'Brad Pitt', definition: 'Amerikansk skådespelare och producent – Fight Club, Seven, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Scarlett Johansson', definition: 'Amerikansk skådespelerska – Black Widow, Lost in Translation, Marriage Story.', difficulty: 'lätt' },
      { title: 'Johnny Depp', definition: 'Amerikansk skådespelare – Pirates of the Caribbean, Edward Scissorhands.', difficulty: 'lätt' },
      { title: 'Christian Bale', definition: 'Brittisk skådespelare – The Dark Knight-trilogin, The Machinist.', difficulty: 'lätt' },
      { title: 'Cate Blanchett', definition: 'Australisk skådespelerska – Blue Jasmine, Carol, The Lord of the Rings.', difficulty: 'lätt' },
      { title: 'Morgan Freeman', definition: 'Amerikansk skådespelare – The Shawshank Redemption, Seven, Million Dollar Baby.', difficulty: 'lätt' },
      { title: 'Matt Damon', definition: 'Amerikansk skådespelare – Good Will Hunting, The Martian, Bourne-serien.', difficulty: 'lätt' },
      { title: 'Will Smith', definition: 'Amerikansk skådespelare – Men in Black, Independence Day, The Pursuit of Happyness.', difficulty: 'lätt' },
      { title: 'Joaquin Phoenix', definition: 'Amerikansk skådespelare – Joker, Her, Walk the Line.', difficulty: 'lätt' },
      { title: 'Natalie Portman', definition: 'Israelisk-amerikansk skådespelerska – Black Swan, V for Vendetta, Star Wars.', difficulty: 'lätt' },
      { title: 'Ryan Gosling', definition: 'Kanadensisk skådespelare – La La Land, Drive, Blade Runner 2049.', difficulty: 'lätt' },
      { title: 'Emma Stone', definition: 'Amerikansk skådespelerska – La La Land, Easy A, The Favourite.', difficulty: 'lätt' },
      { title: 'Hugh Jackman', definition: 'Australisk skådespelare – Wolverine i X-Men, Les Misérables, The Greatest Showman.', difficulty: 'lätt' },
      { title: 'Samuel L. Jackson', definition: 'Amerikansk skådespelare – Pulp Fiction, Nick Fury i Marvel.', difficulty: 'lätt' },
      { title: 'Sandra Bullock', definition: 'Amerikansk skådespelerska – Speed, Gravity, The Blind Side.', difficulty: 'lätt' },
      { title: 'Anne Hathaway', definition: 'Amerikansk skådespelerska – The Devil Wears Prada, Les Misérables, The Dark Knight Rises.', difficulty: 'lätt' },
      { title: 'Chris Hemsworth', definition: 'Australisk skådespelare – Thor i Marvel Cinematic Universe.', difficulty: 'lätt' },
      { title: 'Robert Downey Jr.', definition: 'Amerikansk skådespelare – Iron Man, Sherlock Holmes.', difficulty: 'lätt' },
      { title: 'Chris Evans', definition: 'Amerikansk skådespelare – Captain America, Knives Out, Snowpiercer.', difficulty: 'lätt' },
      { title: 'Benedict Cumberbatch', definition: 'Brittisk skådespelare – Sherlock, Doctor Strange, The Imitation Game.', difficulty: 'lätt' },
      { title: 'Tom Cruise', definition: 'Amerikansk skådespelare – Mission: Impossible, Top Gun, Jerry Maguire.', difficulty: 'lätt' },
      { title: 'Nicole Kidman', definition: 'Australisk skådespelerska – Moulin Rouge!, The Hours, Big Little Lies.', difficulty: 'lätt' },
      { title: 'Charlize Theron', definition: 'Sydafrikansk-amerikansk skådespelerska – Monster, Mad Max: Fury Road, Atomic Blonde.', difficulty: 'lätt' },
      { title: 'George Clooney', definition: 'Amerikansk skådespelare och regissör – Ocean\'s Eleven, Gravity, Up in the Air.', difficulty: 'lätt' },
      { title: 'Harrison Ford', definition: 'Amerikansk skådespelare – Han Solo i Star Wars och Indiana Jones.', difficulty: 'lätt' },
      { title: 'Mark Ruffalo', definition: 'Amerikansk skådespelare – Hulk i Marvel, Spotlight, Foxcatcher.', difficulty: 'lätt' },
      { title: 'Jeremy Renner', definition: 'Amerikansk skådespelare – The Hurt Locker, The Town, Hawkeye.', difficulty: 'lätt' },
      { title: 'Anthony Hopkins', definition: 'Walesisk skådespelare – The Silence of the Lambs, The Father, Thor.', difficulty: 'lätt' },
      { title: 'Ian McKellen', definition: 'Engelsk skådespelare – Gandalf i The Lord of the Rings, Magneto i X-Men.', difficulty: 'lätt' },
      { title: 'Patrick Stewart', definition: 'Engelsk skådespelare – Captain Picard i Star Trek, Professor X i X-Men.', difficulty: 'lätt' },
      { title: 'Kate Winslet', definition: 'Engelsk skådespelerska – Titanic, Eternal Sunshine, Mare of Easttown.', difficulty: 'lätt' },
      { title: 'Julia Roberts', definition: 'Amerikansk skådespelerska – Pretty Woman, Erin Brockovich, Ocean\'s Eleven.', difficulty: 'lätt' },
      { title: 'Reese Witherspoon', definition: 'Amerikansk skådespelerska – Legally Blonde, Walk the Line, Big Little Lies.', difficulty: 'lätt' },
      { title: 'Jennifer Lawrence', definition: 'Amerikansk skådespelerska – The Hunger Games, Silver Linings Playbook, American Hustle.', difficulty: 'lätt' },
      { title: 'Brie Larson', definition: 'Amerikansk skådespelerska – Room, Captain Marvel, Short Term 12.', difficulty: 'lätt' },
      { title: 'Gal Gadot', definition: 'Israelisk skådespelerska – Wonder Woman i DC-filmerna.', difficulty: 'lätt' },
      { title: 'Zoe Saldana', definition: 'Amerikansk skådespelerska – Avatar, Guardians of the Galaxy, Star Trek.', difficulty: 'lätt' },
      { title: 'Millie Bobby Brown', definition: 'Brittisk skådespelerska – Stranger Things, Enola Holmes, Godzilla.', difficulty: 'lätt' },
      { title: 'Michael B. Jordan', definition: 'Amerikansk skådespelare – Creed, Black Panther, Fruitvale Station.', difficulty: 'lätt' },
      { title: 'Chadwick Boseman', definition: 'Amerikansk skådespelare – Black Panther, 42, Get on Up.', difficulty: 'lätt' },
      { title: 'Idris Elba', definition: 'Brittisk skådespelare – Luther, The Wire, Thor, Pacific Rim.', difficulty: 'lätt' },
      { title: 'Daniel Craig', definition: 'Engelsk skådespelare – James Bond i bl.a. Skyfall.', difficulty: 'lätt' },
      { title: 'Rami Malek', definition: 'Amerikansk skådespelare – Bohemian Rhapsody, Mr. Robot.', difficulty: 'lätt' },
      { title: 'Dev Patel', definition: 'Brittisk skådespelare – Slumdog Millionaire, Lion, The Green Knight.', difficulty: 'lätt' },
      { title: 'Pedro Pascal', definition: 'Chilensk-amerikansk skådespelare – The Mandalorian, Narcos, The Last of Us.', difficulty: 'lätt' },
      { title: 'Oscar Isaac', definition: 'Guatemalansk-amerikansk skådespelare – Ex Machina, Dune, Star Wars.', difficulty: 'lätt' },
      { title: 'Adam Driver', definition: 'Amerikansk skådespelare – Marriage Story, Star Wars, BlacKkKlansman.', difficulty: 'lätt' },
      { title: 'Tilda Swinton', definition: 'Skotsk skådespelerska – Michael Clayton, We Need to Talk About Kevin, Doctor Strange.', difficulty: 'lätt' },
      { title: 'Frances McDormand', definition: 'Amerikansk skådespelerska – Fargo, Three Billboards, Nomadland.', difficulty: 'lätt' },
      { title: 'Viola Davis', definition: 'Amerikansk skådespelerska – Fences, The Help, How to Get Away with Murder.', difficulty: 'lätt' },
      { title: 'Lupita Nyong\'o', definition: 'Kenyansk-mexikansk skådespelerska – 12 Years a Slave, Black Panther, Us.', difficulty: 'lätt' },
      { title: 'Mahershala Ali', definition: 'Amerikansk skådespelare – Moonlight, Green Book, True Detective.', difficulty: 'lätt' },
      { title: 'Javier Bardem', definition: 'Spansk skådespelare – No Country for Old Men, Biutiful, Skyfall.', difficulty: 'lätt' },
      { title: 'Penélope Cruz', definition: 'Spansk skådespelerska – Vicky Cristina Barcelona, Volver, Parallel Mothers.', difficulty: 'lätt' },
      { title: 'Antonio Banderas', definition: 'Spansk skådespelare – Desperado, The Mask of Zorro, rösten till Puss in Boots.', difficulty: 'lätt' },
      { title: 'Gael García Bernal', definition: 'Mexikansk skådespelare – Y Tu Mamá También, The Motorcycle Diaries, Mozart in the Jungle.', difficulty: 'lätt' },
      { title: 'Diego Luna', definition: 'Mexikansk skådespelare – Rogue One, Andor, Y Tu Mamá También.', difficulty: 'lätt' },
      { title: 'Salma Hayek', definition: 'Mexikansk-amerikansk skådespelerska – Frida, Desperado, Eternals.', difficulty: 'lätt' },
      { title: 'Wagner Moura', definition: 'Brasiliansk skådespelare – Narcos, Elite Squad.', difficulty: 'lätt' },
      { title: 'Ricardo Darín', definition: 'Argentinsk skådespelare – The Secret in Their Eyes, Wild Tales, Nine Queens.', difficulty: 'lätt' },
      { title: 'Tony Leung Chiu-wai', definition: 'Skådespelare från Hongkong – In the Mood for Love, Infernal Affairs, Shang-Chi.', difficulty: 'lätt' },
      { title: 'Andy Lau', definition: 'Skådespelare och sångare från Hongkong – Infernal Affairs, Running Out of Time.', difficulty: 'lätt' },
      { title: 'Donnie Yen', definition: 'Skådespelare och kampsportare från Hongkong – Ip Man, Rogue One.', difficulty: 'lätt' },
      { title: 'Maggie Cheung', definition: 'Skådespelerska från Hongkong – In the Mood for Love, Hero, Center Stage.', difficulty: 'lätt' },
      { title: 'Jackie Chan', definition: 'Skådespelare och stuntlegend från Hongkong – Rush Hour, Police Story.', difficulty: 'lätt' },
      { title: 'Jet Li', definition: 'Kinesisk skådespelare och kampsportare – Hero, Once Upon a Time in China, Lethal Weapon 4.', difficulty: 'lätt' },
      { title: 'Zhang Ziyi', definition: 'Kinesisk skådespelerska – Crouching Tiger Hidden Dragon, Hero, Memoirs of a Geisha.', difficulty: 'lätt' },
      { title: 'Gong Li', definition: 'Kinesisk skådespelerska – Raise the Red Lantern, Memoirs of a Geisha.', difficulty: 'lätt' },
      { title: 'Takeshi Kitano', definition: 'Japansk skådespelare och regissör – Hana-bi, Sonatine.', difficulty: 'lätt' },
      { title: 'Ken Watanabe', definition: 'Japansk skådespelare – The Last Samurai, Inception, Letters from Iwo Jima.', difficulty: 'lätt' },
      { title: 'Song Kang-ho', definition: 'Sydkoreansk skådespelare – Parasite, Memories of Murder, The Host.', difficulty: 'lätt' },
      { title: 'Lee Byung-hun', definition: 'Sydkoreansk skådespelare – Joint Security Area, I Saw the Devil.', difficulty: 'lätt' },
      { title: 'Bae Doona', definition: 'Sydkoreansk skådespelerska – Cloud Atlas, Sense8, Kingdom.', difficulty: 'lätt' },
      { title: 'Heath Ledger', definition: 'Australisk skådespelare – The Dark Knight, Brokeback Mountain.', difficulty: 'lätt' },
      { title: 'Russell Crowe', definition: 'Nyzeeländsk-född skådespelare – Gladiator, A Beautiful Mind, L.A. Confidential.', difficulty: 'lätt' },
      { title: 'Hugo Weaving', definition: 'Engelsk-australisk skådespelare – The Matrix, The Lord of the Rings, V for Vendetta.', difficulty: 'lätt' },
      { title: 'Sam Neill', definition: 'Nyzeeländsk skådespelare – Jurassic Park, The Piano, Peaky Blinders.', difficulty: 'lätt' },
      { title: 'Mel Gibson', definition: 'Amerikansk-australisk skådespelare – Mad Max, Lethal Weapon, Braveheart.', difficulty: 'lätt' },
      { title: 'Liam Neeson', definition: 'Irländsk skådespelare – Schindler\'s List, Taken, Batman Begins.', difficulty: 'lätt' },
      { title: 'Colin Farrell', definition: 'Irländsk skådespelare – In Bruges, The Banshees of Inisherin, The Lobster.', difficulty: 'lätt' },
      { title: 'Cillian Murphy', definition: 'Irländsk skådespelare – Peaky Blinders, Oppenheimer, 28 Days Later.', difficulty: 'lätt' },
      { title: 'Daniel Day-Lewis', definition: 'Engelsk-irländsk skådespelare – There Will Be Blood, Lincoln, Gangs of New York.', difficulty: 'lätt' },
      { title: 'Helena Bonham Carter', definition: 'Engelsk skådespelerska – Fight Club, The King\'s Speech, Harry Potter.', difficulty: 'lätt' },
      { title: 'Emma Thompson', definition: 'Engelsk skådespelerska – Sense and Sensibility, Love Actually, Saving Mr. Banks.', difficulty: 'lätt' },
      { title: 'Gary Oldman', definition: 'Engelsk skådespelare – Darkest Hour, The Dark Knight, Tinker Tailor Soldier Spy.', difficulty: 'lätt' },
      { title: 'Ralph Fiennes', definition: 'Engelsk skådespelare – The English Patient, Schindler\'s List, Voldemort i Harry Potter.', difficulty: 'lätt' },
      { title: 'Jude Law', definition: 'Engelsk skådespelare – The Talented Mr. Ripley, Sherlock Holmes, The New Pope.', difficulty: 'lätt' },
      { title: 'Keira Knightley', definition: 'Engelsk skådespelerska – Pirates of the Caribbean, Pride & Prejudice, Atonement.', difficulty: 'lätt' },
      { title: 'Naomi Watts', definition: 'Brittisk-australisk skådespelerska – Mulholland Drive, The Ring, King Kong.', difficulty: 'lätt' },
      { title: 'Monica Bellucci', definition: 'Italiensk skådespelerska – Malèna, The Matrix-uppföljarna, Spectre.', difficulty: 'lätt' },
      { title: 'Sophia Loren', definition: 'Italiensk skådespelerska – klassisk stjärna känd för Two Women.', difficulty: 'lätt' },
      { title: 'Jean Reno', definition: 'Fransk skådespelare – Léon: The Professional, Ronin, The Da Vinci Code.', difficulty: 'lätt' },
      { title: 'Marion Cotillard', definition: 'Fransk skådespelerska – La Vie en Rose, Inception, Rust and Bone.', difficulty: 'lätt' },
      { title: 'Vincent Cassel', definition: 'Fransk skådespelare – Black Swan, La Haine, Eastern Promises.', difficulty: 'lätt' },
      { title: 'Gérard Depardieu', definition: 'Fransk skådespelare – Cyrano de Bergerac, Green Card.', difficulty: 'lätt' },
      { title: 'Max von Sydow', definition: 'Svensk skådespelare – Det sjunde inseglet, The Exorcist.', difficulty: 'lätt' },
      { title: 'Alicia Vikander', definition: 'Svensk skådespelerska – Ex Machina, The Danish Girl, Tomb Raider.', difficulty: 'lätt' },
      { title: 'Mads Mikkelsen', definition: 'Dansk skådespelare – Another Round, Casino Royale, Hannibal.', difficulty: 'lätt' },
      { title: 'Viggo Mortensen', definition: 'Dansk-amerikansk skådespelare – The Lord of the Rings, Green Book, Eastern Promises.', difficulty: 'lätt' },
      { title: 'Michael Fassbender', definition: 'Irländsk-tysk skådespelare – X-Men, Shame, 12 Years a Slave.', difficulty: 'lätt' },
      { title: 'Timothée Chalamet', definition: 'Amerikansk skådespelare – Call Me by Your Name, Dune, Wonka.', difficulty: 'lätt' },
      { title: 'Austin Butler', definition: 'Amerikansk skådespelare – Elvis, Dune: Part Two, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Barry Keoghan', definition: 'Irländsk skådespelare – Saltburn, The Banshees of Inisherin.', difficulty: 'lätt' },
      { title: 'Paul Mescal', definition: 'Irländsk skådespelare – Aftersun, Normal People, Gladiator II.', difficulty: 'lätt' },
      { title: 'Jacob Elordi', definition: 'Australisk skådespelare – Euphoria, Saltburn, Priscilla.', difficulty: 'lätt' },
      { title: 'Anya Taylor-Joy', definition: 'Argentinsk-brittisk skådespelerska – The Queen\'s Gambit, Furiosa, The Witch.', difficulty: 'lätt' },
      { title: 'Jodie Comer', definition: 'Engelsk skådespelerska – Killing Eve, The Last Duel, Free Guy.', difficulty: 'lätt' },
      { title: 'Nicholas Hoult', definition: 'Engelsk skådespelare – Mad Max: Fury Road, The Great, X-Men.', difficulty: 'lätt' },
      { title: 'Riz Ahmed', definition: 'Brittisk skådespelare – Sound of Metal, Nightcrawler, The Night Of.', difficulty: 'lätt' },
      { title: 'Jesse Plemons', definition: 'Amerikansk skådespelare – The Power of the Dog, Fargo, Civil War.', difficulty: 'lätt' },
      { title: 'Michelle Yeoh', definition: 'Malaysisk skådespelerska – Everything Everywhere All at Once, Crouching Tiger Hidden Dragon.', difficulty: 'lätt' },
      { title: 'Ke Huy Quan', definition: 'Amerikansk skådespelare – Everything Everywhere All at Once, Indiana Jones and the Temple of Doom.', difficulty: 'lätt' },
      { title: 'Brendan Fraser', definition: 'Kanadensisk-amerikansk skådespelare – The Whale, The Mummy.', difficulty: 'lätt' },
      { title: 'Adrien Brody', definition: 'Amerikansk skådespelare – The Pianist, The Brutalist, The Grand Budapest Hotel.', difficulty: 'lätt' },
      { title: 'Toni Collette', definition: 'Australisk skådespelerska – Hereditary, The Sixth Sense.', difficulty: 'lätt' },
      { title: 'Isabelle Huppert', definition: 'Fransk skådespelerska – Elle, The Piano Teacher, Amour.', difficulty: 'lätt' },
      { title: 'Léa Seydoux', definition: 'Fransk skådespelerska – Blue Is the Warmest Colour, No Time to Die, Dune: Part Two.', difficulty: 'lätt' },
      { title: 'Juliette Binoche', definition: 'Fransk skådespelerska – The English Patient, Certified Copy, Chocolat.', difficulty: 'lätt' },
      { title: 'Halle Berry', definition: 'Amerikansk skådespelerska – Monster\'s Ball, X-Men, John Wick: Chapter 3.', difficulty: 'lätt' },
      { title: 'Jennifer Connelly', definition: 'Amerikansk skådespelerska – A Beautiful Mind, Top Gun: Maverick, Requiem for a Dream.', difficulty: 'lätt' },
      { title: 'Elizabeth Olsen', definition: 'Amerikansk skådespelerska – WandaVision, Martha Marcy May Marlene.', difficulty: 'lätt' },
      { title: 'Dakota Johnson', definition: 'Amerikansk skådespelerska – Fifty Shades, Suspiria.', difficulty: 'lätt' },
      { title: 'Amy Adams', definition: 'Amerikansk skådespelerska – Arrival, American Hustle, Enchanted.', difficulty: 'lätt' },
      { title: 'Aubrey Plaza', definition: 'Amerikansk skådespelerska – Parks and Recreation, Emily the Criminal, The White Lotus.', difficulty: 'lätt' },
      { title: 'Rachel Zegler', definition: 'Amerikansk skådespelerska – West Side Story, The Hunger Games-prequel.', difficulty: 'lätt' },
      { title: 'Sydney Sweeney', definition: 'Amerikansk skådespelerska – Euphoria, Reality, Anyone But You.', difficulty: 'lätt' },
      { title: 'Jenna Ortega', definition: 'Amerikansk skådespelerska – Wednesday, Scream, Beetlejuice Beetlejuice.', difficulty: 'lätt' },
      { title: 'Steven Spielberg', definition: 'Oscarsbelönad regissör – Jaws, E.T., Schindler\'s List.', difficulty: 'lätt' },
      { title: 'Martin Scorsese', definition: 'Oscarsbelönad regissör – The Godfather Part II, The Deer Hunter, Raging Bull (Goodfellas, The Irishman).', difficulty: 'lätt' },
      { title: 'Quentin Tarantino', definition: 'Regissör (Palme d\'Or) – Pulp Fiction, Kill Bill, Once Upon a Time in Hollywood.', difficulty: 'lätt' },
      { title: 'Christopher Nolan', definition: 'Oscarsbelönad regissör – Inception, The Dark Knight, Oppenheimer.', difficulty: 'lätt' },
      { title: 'Francis Ford Coppola', definition: 'Regissör – The Godfather, Apocalypse Now, The Conversation.', difficulty: 'lätt' },
      { title: 'Peter Jackson', definition: 'Oscarsbelönad regissör – The Lord of the Rings-trilogin, The Hobbit.', difficulty: 'lätt' },
      { title: 'Bong Joon-ho', definition: 'Oscarsbelönad regissör – Parasite, Memories of Murder, Snowpiercer.', difficulty: 'lätt' },
      { title: 'Clint Eastwood', definition: 'Oscarsbelönad regissör – Unforgiven, Million Dollar Baby, Gran Torino.', difficulty: 'lätt' },
      { title: 'Alfred Hitchcock', definition: 'Regissör – Rear Window, Psycho, Vertigo.', difficulty: 'lätt' },
      { title: 'Guillermo del Toro', definition: 'Oscarsbelönad regissör – The Shape of Water, Pan\'s Labyrinth.', difficulty: 'lätt' },
      { title: 'Alfonso Cuarón', definition: 'Oscarsbelönad regissör – Roma, Children of Men, Gravity.', difficulty: 'lätt' },
      { title: 'Akira Kurosawa', definition: 'Regissör – Seven Samurai, Rashomon, Ran.', difficulty: 'lätt' },
      { title: 'Ingmar Bergman', definition: 'Svensk regissör – Det sjunde inseglet, Persona.', difficulty: 'lätt' },
      { title: 'Denis Villeneuve', definition: 'Regissör – Dune, Blade Runner 2049, Arrival.', difficulty: 'lätt' },
      { title: 'Paul Thomas Anderson', definition: 'Regissör – There Will Be Blood, Magnolia, Boogie Nights.', difficulty: 'lätt' },
      { title: 'James Cameron', definition: 'Oscarsbelönad regissör – Titanic, Avatar, The Terminator.', difficulty: 'lätt' },
      { title: 'Spike Lee', definition: 'Oscarsbelönad regissör – Do the Right Thing, Malcolm X, BlacKkKlansman.', difficulty: 'lätt' },
    ],
};
