// Fotboll: positioner (kärna), stjärnspelare (färskvara) och lag per liga.
export const fotboll = {
  'Positioner': [
    { title: 'Målvakt (GK)', definition: 'Sista försvarslinjen. Förhindrar mål genom att rädda skott, enda spelaren som får använda händerna inom straffområdet, och styr ofta försvaret.', difficulty: 'medel', noFill: true },
    { title: 'Mittback (CB)', definition: 'Spelar centralt i försvaret. Bryter motståndarnas anfall, markerar anfallare och rensar bollar.', difficulty: 'medel', noFill: true },
    { title: 'Ytterback (RB/LB)', definition: 'Spelar på kanten av försvarslinjen. Försvarar mot motståndarnas yttrar och följer ofta med upp i anfall längs kanten.', difficulty: 'medel', noFill: true },
    { title: 'Vingback (RWB/LWB)', definition: 'En offensivare ytterback i en 3- eller 5-backslinje, med stort ansvar för både försvar och anfall på sin kant.', difficulty: 'medel', noFill: true },
    { title: 'Defensiv mittfältare (CDM)', definition: 'Ligger strax framför backlinjen. Bryter motståndarnas spel, vinner boll och fördelar passningar för att starta egna anfall.', difficulty: 'medel', noFill: true },
    { title: 'Central mittfältare (CM)', definition: 'Lagets motor. Länkar ihop försvar och anfall och styr spelet både offensivt och defensivt.', difficulty: 'medel', noFill: true },
    { title: 'Offensiv mittfältare (CAM / "Tia")', definition: 'Spelar bakom anfallarna som playmaker. Skapar målchanser med avgörande passningar eller egna skott.', difficulty: 'medel', noFill: true },
    { title: 'Yttermittfältare (RM/LM)', definition: 'Spelar på mittfältets kanter. Slår inlägg, utmanar ytterbackar och ger bredd åt anfallet.', difficulty: 'medel', noFill: true },
    { title: 'Centerforward / Nia (ST/CF)', definition: 'Lagets primära målskytt. Ligger högst upp, rör sig i straffområdet och avslutar anfallen.', difficulty: 'medel', noFill: true },
    { title: 'Falsk nia (False Nine)', definition: 'En anfallare som droppar ner i banan för att hämta boll och skapa ytor för medspelare istället för att ligga still mot backlinjen.', difficulty: 'medel', noFill: true },
    { title: 'Ytter (RW/LW)', definition: 'Offensiva kantspelare som söker sig inåt för att avsluta eller utmanar på utsidan för att slå inlägg.', difficulty: 'medel', noFill: true },
  ],
  'Stjärnspelare (färskvara)': [
    { title: 'Gianluigi Donnarumma', definition: 'Målvakt i italienska landslaget. En av världens främsta målvakter.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Thibaut Courtois', definition: 'Målvakt i Real Madrid och belgiska landslaget. Känd för räddningar i avgörande matcher.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Alisson Becker', definition: 'Målvakt i Liverpool och brasilianska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Jan Oblak', definition: 'Målvakt i Atlético Madrid och slovenska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'William Saliba', definition: 'Mittback i Arsenal och franska landslaget. Lugn och stark uppspelsförsvarare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Joshua Kimmich', definition: 'Defensiv mittfältare/högerback i Bayern München och tyska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Federico Valverde', definition: 'Central mittfältare i Real Madrid och uruguayanska landslaget. Box-to-box-motor.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Trent Alexander-Arnold', definition: 'Högerback/mittfältare i Real Madrid och engelska landslaget. Känd för passningar och frisparkar.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Ousmane Dembélé', definition: 'Ytter i Paris Saint-Germain och franska landslaget. Tvåfotad dribbler.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Cole Palmer', definition: 'Offensiv mittfältare/ytter i Chelsea och engelska landslaget. Kreativ och målfarlig.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Gabriel Magalhães', definition: 'Mittback i Arsenal och brasilianska landslaget. Stark i båda straffområdena.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Jules Koundé', definition: 'Högerback/mittback i FC Barcelona och franska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Nuno Mendes', definition: 'Vänsterback i Paris Saint-Germain och portugisiska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Alessandro Bastoni', definition: 'Mittback i Inter och italienska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Kylian Mbappé', definition: 'Centerforward i Real Madrid och franska landslaget. En av världens snabbaste och mest målfarliga anfallare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Erling Haaland', definition: 'Anfallare i Manchester City och norska landslaget. Extrem målmaskin känd för fysik och avslut.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Vinícius Júnior', definition: 'Vänsterytter i Real Madrid och brasilianska landslaget. Teknisk dribbler och målfarlig på kanten.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Jude Bellingham', definition: 'Mittfältare i Real Madrid och engelska landslaget. Box-to-box-spelare med målsinne.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Harry Kane', definition: 'Centerforward i Bayern München och engelska landslaget. Komplett målskytt och spelfördelare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Mohamed Salah', definition: 'Högerytter i Liverpool och egyptiska landslaget. En av Premier Leagues mest produktiva spelare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Lautaro Martínez', definition: 'Centerforward i Inter och argentinska landslaget. Lagkapten och målskytt.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Florian Wirtz', definition: 'Offensiv mittfältare, tysk landslagsspelare. Kreativ playmaker.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Jamal Musiala', definition: 'Offensiv mittfältare i Bayern München och tyska landslaget. Teknisk och bolltrygg.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Pedri', definition: 'Central mittfältare i FC Barcelona och spanska landslaget. Passningssäker spelmotor.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Rodri', definition: 'Defensiv mittfältare i Manchester City och spanska landslaget. Ballon d\'Or-vinnare 2024.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Virgil van Dijk', definition: 'Mittback och kapten i Liverpool och nederländska landslaget. Dominant försvarsspelare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Lamine Yamal', definition: 'Högerytter i FC Barcelona och spanska landslaget. Ungt supertalang-fenomen.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Robert Lewandowski', definition: 'Centerforward i FC Barcelona och polska landslaget. En av historiens främsta målskyttar.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Alexander Isak', definition: 'Anfallare i svenska landslaget. Teknisk och kylig avslutare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Bukayo Saka', definition: 'Högerytter i Arsenal och engelska landslaget. Snabb och målfarlig kantspelare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Bruno Fernandes', definition: 'Offensiv mittfältare och kapten i Manchester United och portugisiska landslaget.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Kevin De Bruyne', definition: 'Offensiv mittfältare, belgiska landslaget. En av sin generations bästa passningsspelare.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Achraf Hakimi', definition: 'Högerback i Paris Saint-Germain och marockanska landslaget. Offensiv och snabb.', difficulty: 'lätt', noFill: true, stale: true },
    { title: 'Declan Rice', definition: 'Defensiv mittfältare i Arsenal och engelska landslaget. Bollvinnare med räckvidd.', difficulty: 'lätt', noFill: true, stale: true },
  ],
  'Allsvenskan': [
    { title: 'IF Brommapojkarna', definition: 'Stockholmsklubb grundad 1942, känd som en av Europas största ungdomsakademier. Fostrat Kulusevski, Guidetti, Ekdal.', difficulty: 'medel', noFill: true },
    { title: 'GAIS', definition: 'Göteborgsklubb grundad 1894, med från ligastarten 1924. 4 SM-guld. Klassisk arbetarstadsidentitet.', difficulty: 'medel', noFill: true },
    { title: 'BK Häcken', definition: 'Göteborgsklubb grundad 1940, spelar på Bravida Arena. 1 SM-guld (2022).', difficulty: 'medel', noFill: true },
    { title: 'Örgryte IS', definition: 'En av landets äldsta klubbar, grundad 1887. 12 SM-guld. Göteborgsklassiker.', difficulty: 'medel', noFill: true },
    { title: 'IK Sirius', definition: 'Uppsalaklubb grundad 1907, spelar på Studenternas IP.', difficulty: 'medel', noFill: true },
    { title: 'Kalmar FF', definition: 'Smålandsklubb grundad 1910. 1 SM-guld (2008).', difficulty: 'medel', noFill: true },
    { title: 'Halmstads BK', definition: 'Hallandsklubb grundad 1914. 4 SM-guld. Känd för fostran och toppfotboll.', difficulty: 'medel', noFill: true },
    { title: 'Degerfors IF', definition: 'Klassisk bruksklubb grundad 1931. Fostrat Gunnar Nordahl och Olof Mellberg.', difficulty: 'medel', noFill: true },
    { title: 'Västerås SK', definition: 'Klubb från Västmanland grundad 1904. Fostrat Victor Nilsson Lindelöf.', difficulty: 'medel', noFill: true },
    { title: 'Mjällby AIF', definition: 'Kustklubb grundad 1939 från Hällevik. SM-guld 2025. Modern framgångssaga.', difficulty: 'medel', noFill: true },
    { title: 'Malmö FF', definition: 'Sveriges mest meriterade klubb, grundad 1910, hemma på Eleda Stadion. 25 SM-guld. Stjärnor genom åren: Zlatan Ibrahimović, Bosse Larsson.', difficulty: 'medel', noFill: true },
    { title: 'AIK', definition: 'Stockholmsklubb grundad 1891, spelar på Strawberry Arena. 12 SM-guld. Stark tradition och stor supporterskara.', difficulty: 'medel', noFill: true },
    { title: 'IFK Göteborg', definition: 'Göteborgsklubb grundad 1904 med stark europeisk meritlista (UEFA-cupen). 18 SM-guld. "Blåvitt".', difficulty: 'medel', noFill: true },
    { title: 'Djurgårdens IF', definition: 'Stockholmsklubb grundad 1891, spelar på 3Arena. 8 SM-guld. Bred supporterbas.', difficulty: 'medel', noFill: true },
    { title: 'Hammarby IF', definition: 'Stockholmsklubb grundad 1897, känd för stark supporterkultur. 1 SM-guld (2001). "Bajen".', difficulty: 'medel', noFill: true },
    { title: 'IF Elfsborg', definition: 'Boråsklubb grundad 1904, spelar på Borås Arena. 6 SM-guld.', difficulty: 'medel', noFill: true },
  ],
  'Premier League': [
    { title: 'Aston Villa', definition: 'Grundad 1874 i Birmingham. Vann Europacupen 1982, en av de klassiska storklubbarna.', difficulty: 'medel', noFill: true },
    { title: 'Newcastle United', definition: 'Grundad 1892, klassisk nordengelsk klubb med stark lokal förankring.', difficulty: 'medel', noFill: true },
    { title: 'Nottingham Forest', definition: 'Grundad 1865. Vann Europacupen två år i rad 1979 och 1980.', difficulty: 'medel', noFill: true },
    { title: 'Everton', definition: 'Grundad 1878 i Liverpool, en av Englands mest historiska klubbar och grundare av Football League.', difficulty: 'medel', noFill: true },
    { title: 'West Ham United', definition: 'Grundad 1895 i östra London, berömd för sin starka ungdomsakademi.', difficulty: 'medel', noFill: true },
    { title: 'Brighton & Hove Albion', definition: 'Grundad 1901, respekterad för stark scouting och offensiv fotboll.', difficulty: 'medel', noFill: true },
    { title: 'Crystal Palace', definition: 'Grundad 1905 i södra London, känd för passionerade supportrar på Selhurst Park.', difficulty: 'medel', noFill: true },
    { title: 'Brentford', definition: 'Grundad 1889 i västra London, känd för modern dataanalys.', difficulty: 'medel', noFill: true },
    { title: 'Fulham', definition: 'Grundad 1879, Londons äldsta professionella fotbollsklubb.', difficulty: 'medel', noFill: true },
    { title: 'Leeds United', definition: 'Grundad 1919, historiskt framgångsrik, vann ligan senast 1992.', difficulty: 'medel', noFill: true },
    { title: 'Manchester City', definition: 'Grundad 1880, har dominerat engelsk fotboll under 2010- och 2020-talet med flera ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Liverpool', definition: 'Grundad 1892, en av världens mest framgångsrika klubbar med många ligatitlar och sex Champions League-titlar.', difficulty: 'medel', noFill: true },
    { title: 'Manchester United', definition: 'Grundad 1878, Englands mest framgångsrika klubb sett till antal ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Arsenal', definition: 'Grundad 1886 i London, känd för "The Invincibles"-säsongen 2003/04 utan en enda förlust.', difficulty: 'medel', noFill: true },
    { title: 'Chelsea', definition: 'Grundad 1905 i London, har vunnit flera Premier League-titlar och Champions League två gånger.', difficulty: 'medel', noFill: true },
    { title: 'Tottenham Hotspur', definition: 'Grundad 1882 i London, känd för offensiv fotboll och många landslagsspelare.', difficulty: 'medel', noFill: true },
  ],
  'La Liga': [
    { title: 'Valencia CF', definition: 'Grundad 1919, en av de mest framgångsrika utanför de tre stora. 6 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Sevilla FC', definition: 'Grundad 1890, "kungen av Europa League". Stjärnor: Jesús Navas, Kanouté.', difficulty: 'medel', noFill: true },
    { title: 'Real Sociedad', definition: 'Baskisk klubb grundad 1909, stark ungdomsfostran. 2 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Real Betis', definition: 'Grundad 1907, hängivna supportrar i Sevilla. 1 ligatitel. Stjärna: Joaquín.', difficulty: 'medel', noFill: true },
    { title: 'Villarreal CF', definition: 'Grundad 1923, "den gula ubåten". Stjärnor: Riquelme, Cazorla.', difficulty: 'medel', noFill: true },
    { title: 'Girona FC', definition: 'Grundad 1930, sensation i spansk fotboll på kort tid.', difficulty: 'medel', noFill: true },
    { title: 'Real Madrid', definition: 'Grundad 1902, världens mest framgångsrika klubb i internationella turneringar. 36 ligatitlar. Stjärnor: Di Stéfano, Zidane, Ronaldo.', difficulty: 'medel', noFill: true },
    { title: 'FC Barcelona', definition: 'Grundad 1899, känd för sin filosofi och akademi La Masia. 27 ligatitlar. Stjärnor: Cruyff, Xavi, Messi.', difficulty: 'medel', noFill: true },
    { title: 'Atlético Madrid', definition: 'Grundad 1903, känd för krigisk inställning och disciplinerad defensiv. 11 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Athletic Bilbao', definition: 'Grundad 1898, unik klubb som endast använder spelare med baskiska rötter. 8 ligatitlar.', difficulty: 'medel', noFill: true },
  ],
  'Serie A': [
    { title: 'AS Roma', definition: 'Grundad 1927, huvudstadsklubb med fanatisk supporterkultur. 3 ligatitlar. Stjärna: Totti.', difficulty: 'medel', noFill: true },
    { title: 'SS Lazio', definition: 'Grundad 1900, Rom-rivalerna. 2 ligatitlar. Stjärna: Immobile.', difficulty: 'medel', noFill: true },
    { title: 'Atalanta BC', definition: 'Grundad 1907, fantastisk ungdomsakademi och offensiv fotboll. Stjärna: Lookman.', difficulty: 'medel', noFill: true },
    { title: 'ACF Fiorentina', definition: 'Grundad 1926, Florens-klubben känd för elegans. 2 ligatitlar. Stjärna: Batistuta.', difficulty: 'medel', noFill: true },
    { title: 'Napoli (historik)', definition: 'Syditaliensk klubb; nådde stora framgångar med Maradona på 80-talet och i modern tid med Osimhen.', difficulty: 'medel', noFill: true },
    { title: 'Torino FC', definition: 'Grundad 1906, förlorade nästan hela laget i Superga-katastrofen 1949. 7 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Juventus', definition: 'Grundad 1897, Italiens mest titelvinnande klubb. 36 ligatitlar. Stjärnor: Del Piero, Buffon, Platini.', difficulty: 'medel', noFill: true },
    { title: 'Inter Milan', definition: 'Grundad 1908, enda italienska laget som aldrig åkt ur Serie A. 20 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'AC Milan', definition: 'Grundad 1899, känd för rik europeisk historia. 19 ligatitlar. Stjärnor: Maldini, Baresi, van Basten.', difficulty: 'medel', noFill: true },
    { title: 'SSC Napoli', definition: 'Grundad 1926, syditaliensk stolthet. 3 ligatitlar. Stjärnor: Maradona, Hamšík, Osimhen.', difficulty: 'medel', noFill: true },
  ],
  'Bundesliga': [
    { title: 'RB Leipzig', definition: 'Grundad 2009, modern klubb med snabb utveckling till toppskiktet. Stjärnor: Forsberg, Werner.', difficulty: 'medel', noFill: true },
    { title: 'VfB Stuttgart', definition: 'Grundad 1893, klassisk klubb med flera titlar. 5 titlar. Stjärna: Klinsmann.', difficulty: 'medel', noFill: true },
    { title: 'Eintracht Frankfurt', definition: 'Grundad 1899, stark europeisk historia och fanatisk supporterbas.', difficulty: 'medel', noFill: true },
    { title: 'SV Werder Bremen', definition: 'Grundad 1899, klassisk nordtysk klubb. 4 titlar. Stjärnor: Klose, Pizarro.', difficulty: 'medel', noFill: true },
    { title: 'Borussia Mönchengladbach', definition: 'Klassisk tysk klubb med stark historia, känd för 70-talets storhetstid.', difficulty: 'medel', noFill: true },
    { title: 'FC Bayern München', definition: 'Grundad 1900, Tysklands mest framgångsrika klubb. 34 titlar. Stjärnor: Beckenbauer, Gerd Müller.', difficulty: 'medel', noFill: true },
    { title: 'Borussia Dortmund', definition: 'Grundad 1909, känd för passionerad publik (Gula väggen) och ungdomsakademi. 8 titlar.', difficulty: 'medel', noFill: true },
    { title: 'Bayer Leverkusen', definition: 'Grundad 1904, vann sin första Bundesliga-titel obesegrade 2024. Stjärna: Florian Wirtz.', difficulty: 'medel', noFill: true },
  ],
  'Ligue 1': [
    { title: 'Lyon', definition: 'Grundad 1950, dominant under 2000-talet med 7 raka ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Lille OSC', definition: 'Stabil toppklubb. 4 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Nice', definition: 'Klubb från franska Rivieran. 4 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Lens', definition: 'Traditionsrik klubb från norra Frankrike med stark lokal förankring. 1 ligatitel.', difficulty: 'medel', noFill: true },
    { title: 'Rennes', definition: 'Stabil klubb från Bretagne med lång historia.', difficulty: 'medel', noFill: true },
    { title: 'Paris Saint-Germain', definition: 'Största klubben i modern fransk fotboll, baserad i Paris. 12 ligatitlar.', difficulty: 'medel', noFill: true },
    { title: 'Marseille', definition: 'En av Frankrikes största klubbar med stark supporterkultur. 9 ligatitlar. Enda franska CL-vinnaren (1993).', difficulty: 'medel', noFill: true },
    { title: 'AS Monaco', definition: 'Klubb från furstendömet Monaco, känd för talangutveckling. 8 ligatitlar.', difficulty: 'medel', noFill: true },
  ],
  'Hammarby (trupp)': [
    { title: 'Warner Hahn', definition: '#1 Målvakt — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Hampus Skoglund', definition: '#2 Högerback — Ordinarie ytterback, Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Frederik Winther', definition: '#3 Mittback — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Victor Eriksson', definition: '#4 Mittback — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Tesfaldet Tekie', definition: '#5 Central mittfältare — Bolltrygg passningsspelare, Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Pavle Vagic', definition: '#6 Defensiv mittfältare/mittback — Fysisk bollvinnare, Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Paulos Abraham', definition: '#7 Vänsterytter — Hammarby IF och svenska U21-landslaget.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Markus Karlsson', definition: '#8 Central mittfältare — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Victor Lind', definition: '#9 Vänsterytter — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Nahir Besara', definition: '#20 Offensiv mittfältare — Lagkapten, Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Oscar Johansson Schellhas', definition: '#11 Högermittfältare — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Noah Persson', definition: '#16 Vänsterback — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Sebastian Tounekti', definition: '#18 Ytterforward — Teknisk dribbler, Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Jusef Erabi', definition: '#99 Anfallare — Genombrottsspelare och målskytt, Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Kalle Karlsson', definition: 'Huvudtränare — Hammarby IF.', difficulty: 'svår', noFill: true, stale: true },
  ],
};
