export const lvid = {
  'AI Fundamentals': [
    { title: 'Artificial Intelligence (AI)', definition: 'Maskiner och program designade för att utföra uppgifter som normalt kräver mänsklig intelligens.', difficulty: 'lätt' },
    { title: 'Machine Learning (ML)', definition: 'Delmängd av AI där system lär sig från data utan att bli explicit programmerade.', difficulty: 'lätt' },
    { title: 'Deep Learning (DL)', definition: 'ML-teknik baserad på artificiella neurala nätverk med flera lager för att identifiera komplexa mönster.', difficulty: 'medel' },
    { title: 'Neural Network', definition: 'Datormodell inspirerad av hjärnans struktur med sammankopplade noder (neuroner) som bearbetar information.', difficulty: 'medel' },
    { title: 'Artificial Neural Network (ANN)', definition: 'Nätverkstopologi med input-, dolda och output-lager som simulerar biologiska neuroner.', difficulty: 'medel' },
    { title: 'Neuron', definition: 'Grundenhet i ett neuralt nätverk som tar input, tillämpar en vikt och en aktiveringsfunktion.', difficulty: 'lätt' },
  ],
  
  'Supervised Learning': [
    { title: 'Supervised Learning', definition: 'ML-teknik där modellen tränas på märkta data (input-output par) för att förutsäga outputen.', difficulty: 'lätt' },
    { title: 'Training Data', definition: 'Märkad dataset använd för att träna en ML-modell och justera dess parametrar.', difficulty: 'lätt' },
    { title: 'Test Data', definition: 'Separat dataset använt för att utvärdera modellens prestanda på osedd data.', difficulty: 'lätt' },
    { title: 'Validation Data', definition: 'Dataset använt under träning för att tuning hyperparametrar och förhindra överanpassning.', difficulty: 'medel' },
    { title: 'Classification', definition: 'Övervakad inlärningsuppgift för att förutsäga diskreta kategorier (t.ex. spam/inte-spam).', difficulty: 'lätt' },
    { title: 'Regression', definition: 'Övervakad inlärningsuppgift för att förutsäga kontinuerliga numeriska värden (t.ex. huspriser).', difficulty: 'lätt' },
    { title: 'Logistic Regression', definition: 'Regressionsalgoritm för binär klassificering som använder sigmoidfunktionen.', difficulty: 'medel' },
    { title: 'Linear Regression', definition: 'Modell som förutsäger output som en linjär kombination av input-variabler.', difficulty: 'lätt' },
    { title: 'Decision Tree', definition: 'Algoritm som skapar ett träd av binära beslut för klassificering eller regression.', difficulty: 'medel' },
    { title: 'Random Forest', definition: 'Ensemble-metod som kombinerar flera beslutträd för bättre prediktiv kraft.', difficulty: 'medel' },
    { title: 'Support Vector Machine (SVM)', definition: 'Algoritm som hittar det optimala hyperplanet för att klassificera data i höga dimensioner.', difficulty: 'svår' },
  ],
  
  'Unsupervised Learning': [
    { title: 'Unsupervised Learning', definition: 'ML-teknik där modellen lär sig från omärkt data för att hitta dolda mönster eller struktur.', difficulty: 'lätt' },
    { title: 'Clustering', definition: 'Oövervakad teknik för att gruppera liknande datapunkter tillsammans utan märkningar.', difficulty: 'lätt' },
    { title: 'K-Means Clustering', definition: 'Algoritm som partitionerar data i K kluster genom att minimera variansen inom kluster.', difficulty: 'medel' },
    { title: 'Hierarchical Clustering', definition: 'Teknik som bygger ett träd av kluster (dendrogram) genom agglomerativ eller divisiv metod.', difficulty: 'medel' },
    { title: 'DBSCAN', definition: 'Densitetsbaserad klustringsalgoritm som identifierar kluster av godtycklig form.', difficulty: 'svår' },
    { title: 'Dimensionality Reduction', definition: 'Teknik för att minska antal features genom PCA, t-SNE eller andra metoder.', difficulty: 'medel' },
    { title: 'Principal Component Analysis (PCA)', definition: 'Algoritm som transformerar data till ett lägre-dimensionellt rum samtidigt som variationen bevaras.', difficulty: 'svår' },
    { title: 'Anomaly Detection', definition: 'Teknik för att identifiera avvikande datapunkter som inte följer normala mönster.', difficulty: 'medel' },
  ],
  
  'Reinforcement Learning': [
    { title: 'Reinforcement Learning (RL)', definition: 'ML-paradigm där en agent lär sig genom interaktion med miljö och belöningar.', difficulty: 'medel' },
    { title: 'Agent', definition: 'Entitet i RL som tar beslut och åtgärder för att maximera kumulativ belöning.', difficulty: 'lätt' },
    { title: 'Environment', definition: 'Systemet som agenten interagerar med, tillhandahåller states och belöningar.', difficulty: 'lätt' },
    { title: 'State', definition: 'Aktuell situation eller konfiguration som agenten observerar i miljön.', difficulty: 'lätt' },
    { title: 'Action', definition: 'Beslut eller rörelse som agenten gör för att påverka miljön.', difficulty: 'lätt' },
    { title: 'Reward', definition: 'Numerisk feedback från miljön som indikerar kvaliteten på agentens åtgärd.', difficulty: 'lätt' },
    { title: 'Q-Learning', definition: 'RL-algoritm som lär sig en policy genom att uppskatta Q-värdena för state-action par.', difficulty: 'svår' },
    { title: 'Policy', definition: 'Strategi eller regel som agenten följer för att välja åtgärder baserat på states.', difficulty: 'medel' },
    { title: 'Value Function', definition: 'Funktion som uppskattar långsiktig belöning från ett givet state eller state-action par.', difficulty: 'svår' },
  ],
  
  'Neural Network Architectures': [
    { title: 'Convolutional Neural Network (CNN)', definition: 'Arkitektur specialiserad för att bearbeta spatialdata (bilder) med konvolutionsoperationer.', difficulty: 'medel' },
    { title: 'Convolution', definition: 'Operation som applicerar en filterkärna på inmatningsdatan för att extrahera lokala features.', difficulty: 'medel' },
    { title: 'Pooling', definition: 'Operation som reducerar dimensionaliteten genom att ta max eller genomsnitt över regioner.', difficulty: 'medel' },
    { title: 'Recurrent Neural Network (RNN)', definition: 'Arkitektur med återkoppling för att bearbeta sekventiell data där tidigare outputs påverkar framtida inputs.', difficulty: 'svår' },
    { title: 'Long Short-Term Memory (LSTM)', definition: 'RNN-variant med minnesceller för att undvika försvinnande gradienter över långa sekvenser.', difficulty: 'svår' },
    { title: 'Gated Recurrent Unit (GRU)', definition: 'Förenklad version av LSTM med färre parametrar men liknande kapacitet.', difficulty: 'svår' },
    { title: 'Transformer', definition: 'Arkitektur baserad på self-attention mekanismer för effektiv parallell behandling av sekvenser.', difficulty: 'svår' },
    { title: 'Attention Mechanism', definition: 'Teknik som gör att modellen fokuserar på relevanta delar av inmatningen.', difficulty: 'svår' },
    { title: 'Self-Attention', definition: 'Mekanisme där varje element i en sekvens beräknar relationer till alla andra element.', difficulty: 'svår' },
    { title: 'Encoder-Decoder', definition: 'Arkitektur med två komponenter: encoder komprimerar input, decoder genererar output.', difficulty: 'medel' },
    { title: 'Autoencoder', definition: 'Nätverk som lär sig att komprimera och rekonstruera data för representation learning.', difficulty: 'medel' },
    { title: 'Generative Adversarial Network (GAN)', definition: 'System med två nätverk: generator skapar fake data, discriminator upptäcker fusk.', difficulty: 'svår' },
  ],
  
  'Large Language Models': [
    { title: 'Large Language Model (LLM)', definition: 'Transformerbaserad modell tränad på enorma textmängder för att generera och förstå språk.', difficulty: 'medel' },
    { title: 'GPT (Generative Pre-trained Transformer)', definition: 'Arkitektur för autoregressiv språkmodellering utvecklad av OpenAI.', difficulty: 'medel' },
    { title: 'BERT (Bidirectional Encoder Representations from Transformers)', definition: 'Modell från Google som använder bidirektionella transformers för språkförståelse.', difficulty: 'medel' },
    { title: 'Tokenization', definition: 'Process att dela upp text i tokens (ord, subord eller tecken) för modellbehandling.', difficulty: 'lätt' },
    { title: 'Embedding', definition: 'Representation av ord/token som vektorer i ett kontinuerligt vektorrum.', difficulty: 'medel' },
    { title: 'Word2Vec', definition: 'Teknik för att lära sig ordvektorrepresentationer från stor textmängd (Skip-gram, CBOW).', difficulty: 'medel' },
    { title: 'Prompt Engineering', definition: 'Konst att formulera instruktioner för LLM:er för att få önskat resultat.', difficulty: 'lätt' },
    { title: 'Few-Shot Learning', definition: 'Förmåga att lösa uppgifter med endast några få exempel istället för stor träningsdata.', difficulty: 'medel' },
    { title: 'Zero-Shot Learning', definition: 'Modellens förmåga att lösa uppgifter utan explicit träning på den uppgiften.', difficulty: 'medel' },
    { title: 'Fine-tuning', definition: 'Process att träna en redan tränad modell på ny data för specifik uppgift.', difficulty: 'medel' },
  ],
  
  'Training & Optimization': [
    { title: 'Backpropagation', definition: 'Algoritm för att beräkna gradienter genom kedjeregler för att uppdatera vikter.', difficulty: 'svår' },
    { title: 'Gradient Descent', definition: 'Optimeringsalgoritm som uppdaterar parametrar i riktningen av negativ gradient.', difficulty: 'medel' },
    { title: 'Stochastic Gradient Descent (SGD)', definition: 'Variant av gradient descent som uppdaterar parametrar baserat på mini-batches.', difficulty: 'medel' },
    { title: 'Momentum', definition: 'Teknik som accelererar gradient descent genom att ackumulera gradient-historia.', difficulty: 'medel' },
    { title: 'Adam Optimizer', definition: 'Adaptiv optimeringsalgoritm som kombinerar momentum och RMSprop för snabbare konvergens.', difficulty: 'medel' },
    { title: 'Learning Rate', definition: 'Hyperparameter som kontrollerar storleken på steget i gradient descent.', difficulty: 'lätt' },
    { title: 'Batch Size', definition: 'Antal träningsexempel som bearbetas innan parametrar uppdateras.', difficulty: 'lätt' },
    { title: 'Epoch', definition: 'Fullständig genomgång av hela träningsdatasetet under träning.', difficulty: 'lätt' },
    { title: 'Loss Function', definition: 'Matematisk funktion som mäter skillnaden mellan förutsägelseor och faktiska värden.', difficulty: 'lätt' },
    { title: 'Cross-Entropy Loss', definition: 'Loss-funktion vanligt använd för klassificering som mäter skillnad mellan sannolikhetsfördelningar.', difficulty: 'medel' },
    { title: 'Mean Squared Error (MSE)', definition: 'Loss-funktion för regression som beräknar medelvärdet av kvadrerade fel.', difficulty: 'lätt' },
  ],
  
  'Regularization & Overfitting': [
    { title: 'Overfitting', definition: 'Problem där modellen lär sig träningsdata för väl och presterar dåligt på ny data.', difficulty: 'lätt' },
    { title: 'Underfitting', definition: 'Problem där modellen är för enkel och inte kan fånga datasetes grundläggande mönster.', difficulty: 'lätt' },
    { title: 'Regularization', definition: 'Teknik för att förhindra överanpassning genom att lägga till begränsningar på modellen.', difficulty: 'medel' },
    { title: 'L1 Regularization (Lasso)', definition: 'Teknik som adderar summan av absolutvärden av vikter till loss-funktionen.', difficulty: 'medel' },
    { title: 'L2 Regularization (Ridge)', definition: 'Teknik som adderar summan av kvadrerade vikter till loss-funktionen.', difficulty: 'medel' },
    { title: 'Dropout', definition: 'Regulariseringsteknik som slumpmässigt inaktiverar neuroner under träning.', difficulty: 'medel' },
    { title: 'Early Stopping', definition: 'Teknik för att stoppa träning när valideringsfel slutar förbättras.', difficulty: 'lätt' },
    { title: 'Cross-Validation', definition: 'Teknik för att dela data i flera folds för robust modellbedömning.', difficulty: 'medel' },
    { title: 'K-Fold Cross-Validation', definition: 'Metod som delar data i K delar och tränar modellen K gånger med olika valideringssatser.', difficulty: 'medel' },
  ],
  
  'Evaluation Metrics': [
    { title: 'Accuracy', definition: 'Andel av korrekta förutsägelser av totalt antal fall för klassificering.', difficulty: 'lätt' },
    { title: 'Precision', definition: 'Andel av korrekt identifierade positiva fall av alla förutsagda positiva fall.', difficulty: 'medel' },
    { title: 'Recall (Sensitivity)', definition: 'Andel av korrekt identifierade positiva fall av alla faktiska positiva fall.', difficulty: 'medel' },
    { title: 'F1-Score', definition: 'Harmoniskt medelvärde av precision och recall för balanserad klassificeringsmått.', difficulty: 'medel' },
    { title: 'Confusion Matrix', definition: 'Tabell som visar förutsägelser mot faktiska värden för klassificering.', difficulty: 'medel' },
    { title: 'ROC Curve', definition: 'Kurva som plottar true positive rate mot false positive rate vid olika trösklar.', difficulty: 'svår' },
    { title: 'AUC (Area Under Curve)', definition: 'Metrisk som representerar modellens förmåga att diskriminera mellan klasser.', difficulty: 'svår' },
    { title: 'Mean Absolute Error (MAE)', definition: 'Genomsnittlig absolut skillnad mellan förutsagda och faktiska värden för regression.', difficulty: 'lätt' },
    { title: 'Root Mean Squared Error (RMSE)', definition: 'Kvadratroten av medelvärdet av kvadrerade fel mellan förutsägelser och aktual.', difficulty: 'medel' },
    { title: 'Perplexity', definition: 'Metrisk för språkmodeller som mäter hur väl modellen förutsäger testdata.', difficulty: 'svår' },
  ],
  
  'Computer Vision': [
    { title: 'Image Classification', definition: 'Uppgift att klassificera en bild i en av flera fördefinierade kategorier.', difficulty: 'lätt' },
    { title: 'Object Detection', definition: 'Uppgift att identifiera och lokalisera objekt i en bild med begränsningsrutor.', difficulty: 'medel' },
    { title: 'Semantic Segmentation', definition: 'Uppgift att klassificera varje pixel i en bild till en semantisk klass.', difficulty: 'svår' },
    { title: 'Instance Segmentation', definition: 'Uppgift att detektera och segmentera individer av samma objektklass separat.', difficulty: 'svår' },
    { title: 'Feature Extraction', definition: 'Process att identifiera och extrahera relevanta egenskaper från bilder.', difficulty: 'medel' },
    { title: 'Edge Detection', definition: 'Teknik för att identifiera gränser mellan objekt eller regioner i en bild.', difficulty: 'medel' },
    { title: 'Bounding Box', definition: 'Rektangel som omger ett detekterat objekt i en bild för lokalisering.', difficulty: 'lätt' },
    { title: 'Transfer Learning', definition: 'Teknik att använda en modell tränad på en uppgift som startpunkt för en annan uppgift.', difficulty: 'medel' },
    { title: 'ResNet', definition: 'Djup konvolutionsnätarkitektur med residuala anslutningar för att träna väldigt djupa nätverk.', difficulty: 'medel' },
    { title: 'VGG', definition: 'Konvolutionsarkitektur känd för dess enkla design med små 3x3 filter.', difficulty: 'medel' },
  ],
  
  'Natural Language Processing': [
    { title: 'Natural Language Processing (NLP)', definition: 'Fält inom AI som fokuserar på att få datorer att förstå och generera mänskligt språk.', difficulty: 'lätt' },
    { title: 'Sentiment Analysis', definition: 'NLP-uppgift att bestämma om en text uttrycker positiv, negativ eller neutral känsla.', difficulty: 'lätt' },
    { title: 'Named Entity Recognition (NER)', definition: 'Uppgift att identifiera och klassificera namngivna entiteter (personer, orter, organisationer).', difficulty: 'medel' },
    { title: 'Machine Translation', definition: 'Uppgift att automatiskt översätta text från ett språk till ett annat.', difficulty: 'svår' },
    { title: 'Question Answering (QA)', definition: 'Uppgift att automatiskt hitta svar på frågor från en textsamling eller kunskap.', difficulty: 'medel' },
    { title: 'Text Summarization', definition: 'Uppgift att generera en kort sammanfattning av en längre text.', difficulty: 'medel' },
    { title: 'Part-of-Speech (POS) Tagging', definition: 'Uppgift att märka varje ord i en text med dess grammatiska funktion.', difficulty: 'medel' },
    { title: 'Dependency Parsing', definition: 'Uppgift att identifiera grammatiska relationer mellan ord i en mening.', difficulty: 'svår' },
    { title: 'Information Extraction', definition: 'Processagen att extrahera strukturerad information från ostrukturerad text.', difficulty: 'medel' },
    { title: 'Semantic Similarity', definition: 'Mätning av hur semantiskt likna två texter är baserat på deras betydelse.', difficulty: 'medel' },
  ],
  
  'Advanced Concepts': [
    { title: 'Transfer Learning', definition: 'Teknik för att överföra kunskap från en uppgift till en annan relaterad uppgift.', difficulty: 'medel' },
    { title: 'Meta-Learning', definition: 'Område som fokuserar på att träna modeller som kan lära sig att lära sig snabbt.', difficulty: 'svår' },
    { title: 'Few-Shot Learning', definition: 'Förmåga att lära sig från få exempel genom meta-learning eller semmantiska likheter.', difficulty: 'medel' },
    { title: 'Data Augmentation', definition: 'Teknik för att öka träningsdatastorleken genom att skapa variationer av befintliga data.', difficulty: 'medel' },
    { title: 'Ensemble Methods', definition: 'Teknik som kombinerar flera modeller för att förbättra prediktiv prestanda.', difficulty: 'medel' },
    { title: 'Boosting', definition: 'Ensemble-teknik som tränar modeller sekventiellt, viktade efter tidigare fel.', difficulty: 'svår' },
    { title: 'Bagging', definition: 'Ensemble-teknik som tränar modeller parallellt på bootstrap-sampel av träningsdata.', difficulty: 'medel' },
    { title: 'Stacking', definition: 'Ensemble-metod som använder en meta-modell för att kombinera prediktioner från flera modeller.', difficulty: 'svår' },
    { title: 'Explainability (XAI)', definition: 'Område fokuserat på att göra AI-modeller transparent och tolkbara för människor.', difficulty: 'medel' },
    { title: 'Feature Importance', definition: 'Metrisk för att mäta hur mycket varje feature bidrar till modellens förutsägelser.', difficulty: 'medel' },
  ],
  
  'Production & MLOps': [
    { title: 'Machine Learning Pipeline', definition: 'Automatiserad workflow från datasamling, preprocessing, träning till deployment.', difficulty: 'medel' },
    { title: 'MLOps', definition: 'Praktiker för att operationalisera ML-system inklusive CI/CD, monitoring och versioning.', difficulty: 'medel' },
    { title: 'Model Deployment', definition: 'Process att flytta en tränad modell till produktion för att göra förutsägelser på ny data.', difficulty: 'medel' },
    { title: 'Model Serving', definition: 'System för att betjäna ML-modeller som API-endpoints i produktion.', difficulty: 'medel' },
    { title: 'Model Monitoring', definition: 'Praktiker för att övervaka modellprestanda och datadrift i produktion.', difficulty: 'medel' },
    { title: 'Data Drift', definition: 'Fenomen när fördelningen av produktionsdata avviker från träningsdata.', difficulty: 'medel' },
    { title: 'Model Versioning', definition: 'Praktik att hålla reda på och hantera olika versioner av ML-modeller.', difficulty: 'lätt' },
    { title: 'A/B Testing', definition: 'Experimentell metod för att jämföra två versioner av en modell eller feature.', difficulty: 'lätt' },
    { title: 'Hyperparameter Tuning', definition: 'Process att optimera hyperparametrar för att förbättra modellprestanda.', difficulty: 'medel' },
    { title: 'Grid Search', definition: 'Brute-force metod för hyperparameter tuning som testar alla kombinationer.', difficulty: 'medel' },
    { title: 'Random Search', definition: 'Teknik för hyperparameter tuning som testar slumpmässiga kombinationer.', difficulty: 'medel' },
    { title: 'Bayesian Optimization', definition: 'Intelligent hyperparameter tuning-metod baserad på Bayes teorem.', difficulty: 'svår' },
  ],
  
  'Ethics & Safety': [
    { title: 'AI Ethics', definition: 'Område som adresserar etiska frågor i AI-utveckling och deployment.', difficulty: 'lätt' },
    { title: 'Bias in AI', definition: 'Fenomen där AI-system diskriminerar vissa grupper på grund av förspänd träningsdata.', difficulty: 'medel' },
    { title: 'Fairness', definition: 'Egenskap att AI-system behandlar alla individer eller grupper rättvist.', difficulty: 'medel' },
    { title: 'Transparency', definition: 'Grad av förståelse för hur en AI-modell gör sina beslut.', difficulty: 'lätt' },
    { title: 'Privacy', definition: 'Skydd av känslig användardata i AI-system genom teknik som federated learning.', difficulty: 'medel' },
    { title: 'Differential Privacy', definition: 'Teknik för att träna modeller på känslig data utan att avslöja individuell information.', difficulty: 'svår' },
    { title: 'Adversarial Examples', definition: 'Omärkligt modifierade inmatningar designade för att lura ML-modeller.', difficulty: 'svår' },
    { title: 'Robustness', definition: 'Förmågan för en AI-modell att prestera väl även under onormala eller antagonistiska förhållanden.', difficulty: 'medel' },
  ],
  
  'Emerging Trends': [
    { title: 'Multimodal AI', definition: 'AI-system som kan bearbeta och integrera flera modaliteter (text, bild, ljud) tillsammans.', difficulty: 'medel' },
    { title: 'Vision Transformers (ViT)', definition: 'Arkitektur som applicerar transformer-mekanismer direkt på bildpatcher.', difficulty: 'svår' },
    { title: 'Federated Learning', definition: 'Teknik för att träna modeller på decentraliserad data utan att samla dem centralt.', difficulty: 'svår' },
    { title: 'Quantum Machine Learning', definition: 'Område som kombinerar quantum computing med ML för att lösa klassiska ML-problem snabbare.', difficulty: 'svår' },
    { title: 'Continual Learning', definition: 'Förmågan för AI att lära sig från nya uppgifter utan att glömma tidigare kunskap (undvika catastrophic forgetting).', difficulty: 'svår' },
    { title: 'Neuro-Symbolic AI', definition: 'Kombination av neurala nätverk med symbolisk AI för bättre tolkning och resonemang.', difficulty: 'svår' },
    { title: 'Graph Neural Networks (GNN)', definition: 'Arkitektur designad för att bearbeta grafstrukterad data.', difficulty: 'svår' },
  ],
};
