// Länder/politik – uppdelat per fält. Stabila fält (huvudstad, valuta, språk, sevärdheter, statsskick).
// OBS: regeringschefer/partier är medvetet uteslutna här – de är färskvara och kräver verifiering.
export const politik = {
  'Huvudstäder': [
    { title: 'Afghanistan', definition: 'Kabul', difficulty: 'medel' },
    { title: 'Albanien', definition: 'Tirana', difficulty: 'medel' },
    { title: 'Algeriet', definition: 'Alger', difficulty: 'medel' },
    { title: 'Andorra', definition: 'Andorra la Vella', difficulty: 'medel' },
    { title: 'Angola', definition: 'Luanda', difficulty: 'medel' },
    { title: 'Antigua och Barbuda', definition: 'Saint John\'s', difficulty: 'medel' },
    { title: 'Argentina', definition: 'Buenos Aires', difficulty: 'medel' },
    { title: 'Armenien', definition: 'Jerevan', difficulty: 'medel' },
    { title: 'Australien', definition: 'Canberra', difficulty: 'medel' },
    { title: 'Österrike', definition: 'Wien', difficulty: 'medel' },
    { title: 'Azerbajdzjan', definition: 'Baku', difficulty: 'medel' },
    { title: 'Bahamas', definition: 'Nassau', difficulty: 'medel' },
    { title: 'Bahrain', definition: 'Manama', difficulty: 'medel' },
    { title: 'Bangladesh', definition: 'Dhaka', difficulty: 'medel' },
    { title: 'Barbados', definition: 'Bridgetown', difficulty: 'medel' },
    { title: 'Belgien', definition: 'Bryssel', difficulty: 'medel' },
    { title: 'Belize', definition: 'Belmopan', difficulty: 'medel' },
    { title: 'Benin', definition: 'Porto-Novo', difficulty: 'medel' },
    { title: 'Bhutan', definition: 'Thimphu', difficulty: 'medel' },
    { title: 'Bolivia', definition: 'Sucre', difficulty: 'medel' },
    { title: 'Bosnien och Hercegovina', definition: 'Sarajevo', difficulty: 'medel' },
    { title: 'Botswana', definition: 'Gaborone', difficulty: 'medel' },
    { title: 'Brasilien', definition: 'Brasília', difficulty: 'medel' },
    { title: 'Brunei', definition: 'Bandar Seri Begawan', difficulty: 'medel' },
    { title: 'Bulgarien', definition: 'Sofia', difficulty: 'medel' },
    { title: 'Burkina Faso', definition: 'Ouagadougou', difficulty: 'medel' },
    { title: 'Burundi', definition: 'Gitega', difficulty: 'medel' },
    { title: 'Kap Verde', definition: 'Praia', difficulty: 'medel' },
    { title: 'Centralafrikanska republiken', definition: 'Bangui', difficulty: 'medel' },
    { title: 'Tchad', definition: 'N\'Djamena', difficulty: 'medel' },
    { title: 'Chile', definition: 'Santiago', difficulty: 'medel' },
    { title: 'Kina', definition: 'Peking', difficulty: 'medel' },
    { title: 'Komorerna', definition: 'Moroni', difficulty: 'medel' },
    { title: 'Kongo (DR)', definition: 'Kinshasa', difficulty: 'medel' },
    { title: 'Kongo (Rep.)', definition: 'Brazzaville', difficulty: 'medel' },
    { title: 'Costa Rica', definition: 'San José', difficulty: 'medel' },
    { title: 'Kroatien', definition: 'Zagreb', difficulty: 'medel' },
    { title: 'Kuba', definition: 'Havanna', difficulty: 'medel' },
    { title: 'Cypern', definition: 'Nicosia', difficulty: 'medel' },
    { title: 'Tjeckien', definition: 'Prag', difficulty: 'medel' },
    { title: 'Danmark', definition: 'Köpenhamn', difficulty: 'medel' },
    { title: 'Djibouti', definition: 'Djibouti', difficulty: 'medel' },
    { title: 'Dominica', definition: 'Roseau', difficulty: 'medel' },
    { title: 'Dominikanska republiken', definition: 'Santo Domingo', difficulty: 'medel' },
    { title: 'Ecuador', definition: 'Quito', difficulty: 'medel' },
    { title: 'Egypten', definition: 'Kairo', difficulty: 'medel' },
    { title: 'El Salvador', definition: 'San Salvador', difficulty: 'medel' },
    { title: 'Ekvatorialguinea', definition: 'Malabo', difficulty: 'medel' },
    { title: 'Eritrea', definition: 'Asmara', difficulty: 'medel' },
    { title: 'Estland', definition: 'Tallinn', difficulty: 'medel' },
    { title: 'Eswatini', definition: 'Mbabane', difficulty: 'medel' },
    { title: 'Etiopien', definition: 'Addis Abeba', difficulty: 'medel' },
    { title: 'Fiji', definition: 'Suva', difficulty: 'medel' },
    { title: 'Finland', definition: 'Helsingfors', difficulty: 'medel' },
    { title: 'Frankrike', definition: 'Paris', difficulty: 'medel' },
    { title: 'Gabon', definition: 'Libreville', difficulty: 'medel' },
    { title: 'Gambia', definition: 'Banjul', difficulty: 'medel' },
    { title: 'Georgien', definition: 'Tbilisi', difficulty: 'medel' },
    { title: 'Tyskland', definition: 'Berlin', difficulty: 'medel' },
    { title: 'Ghana', definition: 'Accra', difficulty: 'medel' },
    { title: 'Grekland', definition: 'Aten', difficulty: 'medel' },
    { title: 'Grenada', definition: 'Saint George\'s', difficulty: 'medel' },
    { title: 'Guatemala', definition: 'Guatemala City', difficulty: 'medel' },
    { title: 'Guinea', definition: 'Conakry', difficulty: 'medel' },
    { title: 'Guinea-Bissau', definition: 'Bissau', difficulty: 'medel' },
    { title: 'Guyana', definition: 'Georgetown', difficulty: 'medel' },
    { title: 'Haiti', definition: 'Port-au-Prince', difficulty: 'medel' },
    { title: 'Honduras', definition: 'Tegucigalpa', difficulty: 'medel' },
    { title: 'Ungern', definition: 'Budapest', difficulty: 'medel' },
    { title: 'Island', definition: 'Reykjavik', difficulty: 'medel' },
    { title: 'Indien', definition: 'New Delhi', difficulty: 'medel' },
    { title: 'Indonesien', definition: 'Jakarta', difficulty: 'medel' },
    { title: 'Iran', definition: 'Teheran', difficulty: 'medel' },
    { title: 'Irak', definition: 'Bagdad', difficulty: 'medel' },
    { title: 'Irland', definition: 'Dublin', difficulty: 'medel' },
    { title: 'Israel', definition: 'Jerusalem', difficulty: 'medel' },
    { title: 'Italien', definition: 'Rom', difficulty: 'medel' },
    { title: 'Jamaica', definition: 'Kingston', difficulty: 'medel' },
    { title: 'Japan', definition: 'Tokyo', difficulty: 'medel' },
    { title: 'Jordanien', definition: 'Amman', difficulty: 'medel' },
    { title: 'Kazakstan', definition: 'Astana', difficulty: 'medel' },
    { title: 'Kenya', definition: 'Nairobi', difficulty: 'medel' },
    { title: 'Kiribati', definition: 'South Tarawa', difficulty: 'medel' },
    { title: 'Nordkorea', definition: 'Pyongyang', difficulty: 'medel' },
    { title: 'Sydkorea', definition: 'Seoul', difficulty: 'medel' },
    { title: 'Kuwait', definition: 'Kuwait City', difficulty: 'medel' },
    { title: 'Kirgizistan', definition: 'Bisjkek', difficulty: 'medel' },
    { title: 'Laos', definition: 'Vientiane', difficulty: 'medel' },
    { title: 'Lettland', definition: 'Riga', difficulty: 'medel' },
    { title: 'Libanon', definition: 'Beirut', difficulty: 'medel' },
    { title: 'Lesotho', definition: 'Maseru', difficulty: 'medel' },
    { title: 'Liberia', definition: 'Monrovia', difficulty: 'medel' },
    { title: 'Libyen', definition: 'Tripoli', difficulty: 'medel' },
    { title: 'Liechtenstein', definition: 'Vaduz', difficulty: 'medel' },
    { title: 'Litauen', definition: 'Vilnius', difficulty: 'medel' },
    { title: 'Luxemburg', definition: 'Luxemburg', difficulty: 'medel' },
    { title: 'Madagaskar', definition: 'Antananarivo', difficulty: 'medel' },
    { title: 'Malawi', definition: 'Lilongwe', difficulty: 'medel' },
    { title: 'Malaysia', definition: 'Kuala Lumpur', difficulty: 'medel' },
    { title: 'Östtimor', definition: 'Dili', difficulty: 'medel' },
    { title: 'Maldiverna', definition: 'Malé', difficulty: 'medel' },
    { title: 'Mali', definition: 'Bamako', difficulty: 'medel' },
    { title: 'Malta', definition: 'Valletta', difficulty: 'medel' },
    { title: 'Marshallöarna', definition: 'Majuro', difficulty: 'medel' },
    { title: 'Mauretanien', definition: 'Nouakchott', difficulty: 'medel' },
    { title: 'Mauritius', definition: 'Port Louis', difficulty: 'medel' },
    { title: 'Mexiko', definition: 'Mexico City', difficulty: 'medel' },
    { title: 'Mikronesien', definition: 'Palikir', difficulty: 'medel' },
    { title: 'Moldavien', definition: 'Chișinău', difficulty: 'medel' },
    { title: 'Monaco', definition: 'Monaco', difficulty: 'medel' },
    { title: 'Mongoliet', definition: 'Ulaanbaatar', difficulty: 'medel' },
    { title: 'Montenegro', definition: 'Podgorica', difficulty: 'medel' },
    { title: 'Marocko', definition: 'Rabat', difficulty: 'medel' },
    { title: 'Moçambique', definition: 'Maputo', difficulty: 'medel' },
    { title: 'Myanmar', definition: 'Naypyidaw', difficulty: 'medel' },
    { title: 'Namibia', definition: 'Windhoek', difficulty: 'medel' },
    { title: 'Nauru', definition: 'Yaren', difficulty: 'medel' },
    { title: 'Nepal', definition: 'Katmandu', difficulty: 'medel' },
    { title: 'Nederländerna', definition: 'Amsterdam', difficulty: 'medel' },
    { title: 'Nya Zeeland', definition: 'Wellington', difficulty: 'medel' },
    { title: 'Nicaragua', definition: 'Managua', difficulty: 'medel' },
    { title: 'Niger', definition: 'Niamey', difficulty: 'medel' },
    { title: 'Nigeria', definition: 'Abuja', difficulty: 'medel' },
    { title: 'Nordmakedonien', definition: 'Skopje', difficulty: 'medel' },
    { title: 'Norge', definition: 'Oslo', difficulty: 'medel' },
    { title: 'Oman', definition: 'Muscat', difficulty: 'medel' },
    { title: 'Pakistan', definition: 'Islamabad', difficulty: 'medel' },
    { title: 'Palau', definition: 'Ngerulmud', difficulty: 'medel' },
    { title: 'Panama', definition: 'Panama City', difficulty: 'medel' },
    { title: 'Papua Nya Guinea', definition: 'Port Moresby', difficulty: 'medel' },
    { title: 'Paraguay', definition: 'Asunción', difficulty: 'medel' },
    { title: 'Peru', definition: 'Lima', difficulty: 'medel' },
    { title: 'Filippinerna', definition: 'Manila', difficulty: 'medel' },
    { title: 'Polen', definition: 'Warszawa', difficulty: 'medel' },
    { title: 'Portugal', definition: 'Lissabon', difficulty: 'medel' },
    { title: 'Qatar', definition: 'Doha', difficulty: 'medel' },
    { title: 'Rumänien', definition: 'Bukarest', difficulty: 'medel' },
    { title: 'Ryssland', definition: 'Moskva', difficulty: 'medel' },
    { title: 'Rwanda', definition: 'Kigali', difficulty: 'medel' },
    { title: 'Saint Kitts och Nevis', definition: 'Basseterre', difficulty: 'medel' },
    { title: 'Saint Lucia', definition: 'Castries', difficulty: 'medel' },
    { title: 'Saint Vincent och Grenadinerna', definition: 'Kingstown', difficulty: 'medel' },
    { title: 'Samoa', definition: 'Apia', difficulty: 'medel' },
    { title: 'San Marino', definition: 'San Marino', difficulty: 'medel' },
    { title: 'São Tomé och Príncipe', definition: 'São Tomé', difficulty: 'medel' },
    { title: 'Saudiarabien', definition: 'Riyadh', difficulty: 'medel' },
    { title: 'Senegal', definition: 'Dakar', difficulty: 'medel' },
    { title: 'Serbien', definition: 'Belgrad', difficulty: 'medel' },
    { title: 'Seychellerna', definition: 'Victoria', difficulty: 'medel' },
    { title: 'Sierra Leone', definition: 'Freetown', difficulty: 'medel' },
    { title: 'Singapore', definition: 'Singapore', difficulty: 'medel' },
    { title: 'Slovakien', definition: 'Bratislava', difficulty: 'medel' },
    { title: 'Slovenien', definition: 'Ljubljana', difficulty: 'medel' },
    { title: 'Salomonöarna', definition: 'Honiara', difficulty: 'medel' },
    { title: 'Somalia', definition: 'Mogadishu', difficulty: 'medel' },
    { title: 'Sydafrika', definition: 'Pretoria', difficulty: 'medel' },
    { title: 'Sydsudan', definition: 'Juba', difficulty: 'medel' },
    { title: 'Spanien', definition: 'Madrid', difficulty: 'medel' },
    { title: 'Sri Lanka', definition: 'Kotte', difficulty: 'medel' },
    { title: 'Sudan', definition: 'Khartoum', difficulty: 'medel' },
    { title: 'Surinam', definition: 'Paramaribo', difficulty: 'medel' },
    { title: 'Sverige', definition: 'Stockholm', difficulty: 'medel' },
    { title: 'Schweiz', definition: 'Bern', difficulty: 'medel' },
    { title: 'Syrien', definition: 'Damaskus', difficulty: 'medel' },
  ],
  'Valutor': [
    { title: 'Afghanistan', definition: 'Afghansk afghani', difficulty: 'medel' },
    { title: 'Albanien', definition: 'Albansk lek', difficulty: 'medel' },
    { title: 'Algeriet', definition: 'Algerisk dinar', difficulty: 'medel' },
    { title: 'Andorra', definition: 'Euro', difficulty: 'medel' },
    { title: 'Angola', definition: 'Angolansk kwanza', difficulty: 'medel' },
    { title: 'Antigua och Barbuda', definition: 'Östkaribisk dollar', difficulty: 'medel' },
    { title: 'Argentina', definition: 'Argentinsk peso', difficulty: 'medel' },
    { title: 'Armenien', definition: 'Armenisk dram', difficulty: 'medel' },
    { title: 'Australien', definition: 'Australisk dollar', difficulty: 'medel' },
    { title: 'Österrike', definition: 'Euro', difficulty: 'medel' },
    { title: 'Azerbajdzjan', definition: 'Azerbajdzjansk manat', difficulty: 'medel' },
    { title: 'Bahamas', definition: 'Bahamansk dollar', difficulty: 'medel' },
    { title: 'Bahrain', definition: 'Bahrainsk dinar', difficulty: 'medel' },
    { title: 'Bangladesh', definition: 'Bangladeshisk taka', difficulty: 'medel' },
    { title: 'Barbados', definition: 'Barbadisk dollar', difficulty: 'medel' },
    { title: 'Belgien', definition: 'Euro', difficulty: 'medel' },
    { title: 'Belize', definition: 'Belizisk dollar', difficulty: 'medel' },
    { title: 'Benin', definition: 'Västafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Bhutan', definition: 'Bhutanesisk ngultrum', difficulty: 'medel' },
    { title: 'Bolivia', definition: 'Boliviansk boliviano', difficulty: 'medel' },
    { title: 'Bosnien och Hercegovina', definition: 'Konvertibel mark', difficulty: 'medel' },
    { title: 'Botswana', definition: 'Botswansk pula', difficulty: 'medel' },
    { title: 'Brasilien', definition: 'Brasiliansk real', difficulty: 'medel' },
    { title: 'Brunei', definition: 'Bruneisk dollar', difficulty: 'medel' },
    { title: 'Bulgarien', definition: 'Bulgarisk lev', difficulty: 'medel' },
    { title: 'Burkina Faso', definition: 'Västafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Burundi', definition: 'Burundisk franc', difficulty: 'medel' },
    { title: 'Kap Verde', definition: 'Kapverdisk escudo', difficulty: 'medel' },
    { title: 'Centralafrikanska republiken', definition: 'Centralafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Tchad', definition: 'Centralafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Chile', definition: 'Chilensk peso', difficulty: 'medel' },
    { title: 'Kina', definition: 'Kinesisk yuan', difficulty: 'medel' },
    { title: 'Komorerna', definition: 'Komorisk franc', difficulty: 'medel' },
    { title: 'Kongo (DR)', definition: 'Kongolesisk franc', difficulty: 'medel' },
    { title: 'Kongo (Rep.)', definition: 'Centralafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Costa Rica', definition: 'Costaricansk colón', difficulty: 'medel' },
    { title: 'Kroatien', definition: 'Euro', difficulty: 'medel' },
    { title: 'Kuba', definition: 'Kubansk peso', difficulty: 'medel' },
    { title: 'Cypern', definition: 'Euro', difficulty: 'medel' },
    { title: 'Tjeckien', definition: 'Tjeckisk koruna', difficulty: 'medel' },
    { title: 'Danmark', definition: 'Dansk krona', difficulty: 'medel' },
    { title: 'Djibouti', definition: 'Djiboutisk franc', difficulty: 'medel' },
    { title: 'Dominica', definition: 'Östkaribisk dollar', difficulty: 'medel' },
    { title: 'Dominikanska republiken', definition: 'Dominikansk peso', difficulty: 'medel' },
    { title: 'Ecuador', definition: 'USA-dollar', difficulty: 'medel' },
    { title: 'Egypten', definition: 'Egyptiskt pund', difficulty: 'medel' },
    { title: 'El Salvador', definition: 'USA-dollar', difficulty: 'medel' },
    { title: 'Ekvatorialguinea', definition: 'Centralafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Eritrea', definition: 'Eritreansk nakfa', difficulty: 'medel' },
    { title: 'Estland', definition: 'Euro', difficulty: 'medel' },
    { title: 'Eswatini', definition: 'Lilangeni', difficulty: 'medel' },
    { title: 'Etiopien', definition: 'Etiopisk birr', difficulty: 'medel' },
    { title: 'Fiji', definition: 'Fijiansk dollar', difficulty: 'medel' },
    { title: 'Finland', definition: 'Euro', difficulty: 'medel' },
    { title: 'Frankrike', definition: 'Euro', difficulty: 'medel' },
    { title: 'Gabon', definition: 'Centralafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Gambia', definition: 'Gambisk dalasi', difficulty: 'medel' },
    { title: 'Georgien', definition: 'Georgisk lari', difficulty: 'medel' },
    { title: 'Tyskland', definition: 'Euro', difficulty: 'medel' },
    { title: 'Ghana', definition: 'Ghanansk cedi', difficulty: 'medel' },
    { title: 'Grekland', definition: 'Euro', difficulty: 'medel' },
    { title: 'Grenada', definition: 'Östkaribisk dollar', difficulty: 'medel' },
    { title: 'Guatemala', definition: 'Guatemalansk quetzal', difficulty: 'medel' },
    { title: 'Guinea', definition: 'Guineansk franc', difficulty: 'medel' },
    { title: 'Guinea-Bissau', definition: 'Västafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Guyana', definition: 'Guyansk dollar', difficulty: 'medel' },
    { title: 'Haiti', definition: 'Haitisk gourde', difficulty: 'medel' },
    { title: 'Honduras', definition: 'Honduransk lempira', difficulty: 'medel' },
    { title: 'Ungern', definition: 'Ungersk forint', difficulty: 'medel' },
    { title: 'Island', definition: 'Isländsk krona', difficulty: 'medel' },
    { title: 'Indien', definition: 'Indisk rupie', difficulty: 'medel' },
    { title: 'Indonesien', definition: 'Indonesisk rupiah', difficulty: 'medel' },
    { title: 'Iran', definition: 'Iransk rial', difficulty: 'medel' },
    { title: 'Irak', definition: 'Irakisk dinar', difficulty: 'medel' },
    { title: 'Irland', definition: 'Euro', difficulty: 'medel' },
    { title: 'Israel', definition: 'Israelisk shekel', difficulty: 'medel' },
    { title: 'Italien', definition: 'Euro', difficulty: 'medel' },
    { title: 'Jamaica', definition: 'Jamaicansk dollar', difficulty: 'medel' },
    { title: 'Japan', definition: 'Japansk yen', difficulty: 'medel' },
    { title: 'Jordanien', definition: 'Jordansk dinar', difficulty: 'medel' },
    { title: 'Kazakstan', definition: 'Kazakisk tenge', difficulty: 'medel' },
    { title: 'Kenya', definition: 'Kenyansk shilling', difficulty: 'medel' },
    { title: 'Kiribati', definition: 'Australisk dollar', difficulty: 'medel' },
    { title: 'Nordkorea', definition: 'Nordkoreansk won', difficulty: 'medel' },
    { title: 'Sydkorea', definition: 'Sydkoreansk won', difficulty: 'medel' },
    { title: 'Kuwait', definition: 'Kuwaitisk dinar', difficulty: 'medel' },
    { title: 'Kirgizistan', definition: 'Kirgizisk som', difficulty: 'medel' },
    { title: 'Laos', definition: 'Laotisk kip', difficulty: 'medel' },
    { title: 'Lettland', definition: 'Euro', difficulty: 'medel' },
    { title: 'Libanon', definition: 'Libanesiskt pund', difficulty: 'medel' },
    { title: 'Lesotho', definition: 'Loti', difficulty: 'medel' },
    { title: 'Liberia', definition: 'Liberiansk dollar', difficulty: 'medel' },
    { title: 'Libyen', definition: 'Libysk dinar', difficulty: 'medel' },
    { title: 'Liechtenstein', definition: 'Schweizisk franc', difficulty: 'medel' },
    { title: 'Litauen', definition: 'Euro', difficulty: 'medel' },
    { title: 'Luxemburg', definition: 'Euro', difficulty: 'medel' },
    { title: 'Madagaskar', definition: 'Ariary', difficulty: 'medel' },
    { title: 'Malawi', definition: 'Malawisk kwacha', difficulty: 'medel' },
    { title: 'Malaysia', definition: 'Malaysisk ringgit', difficulty: 'medel' },
    { title: 'Östtimor', definition: 'USA-dollar', difficulty: 'medel' },
    { title: 'Maldiverna', definition: 'Maldivisk rufiyaa', difficulty: 'medel' },
    { title: 'Mali', definition: 'Västafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Malta', definition: 'Euro', difficulty: 'medel' },
    { title: 'Marshallöarna', definition: 'USA-dollar', difficulty: 'medel' },
    { title: 'Mauretanien', definition: 'Mauretansk ouguiya', difficulty: 'medel' },
    { title: 'Mauritius', definition: 'Mauritisk rupie', difficulty: 'medel' },
    { title: 'Mexiko', definition: 'Mexikansk peso', difficulty: 'medel' },
    { title: 'Mikronesien', definition: 'USA-dollar', difficulty: 'medel' },
    { title: 'Moldavien', definition: 'Moldavisk leu', difficulty: 'medel' },
    { title: 'Monaco', definition: 'Euro', difficulty: 'medel' },
    { title: 'Mongoliet', definition: 'Mongolisk tögrög', difficulty: 'medel' },
    { title: 'Montenegro', definition: 'Euro', difficulty: 'medel' },
    { title: 'Marocko', definition: 'Marockansk dirham', difficulty: 'medel' },
    { title: 'Moçambique', definition: 'Metical', difficulty: 'medel' },
    { title: 'Myanmar', definition: 'Myanmar kyat', difficulty: 'medel' },
    { title: 'Namibia', definition: 'Namibisk dollar', difficulty: 'medel' },
    { title: 'Nauru', definition: 'Australisk dollar', difficulty: 'medel' },
    { title: 'Nepal', definition: 'Nepalesisk rupie', difficulty: 'medel' },
    { title: 'Nederländerna', definition: 'Euro', difficulty: 'medel' },
    { title: 'Nya Zeeland', definition: 'Nyzeeländsk dollar', difficulty: 'medel' },
    { title: 'Nicaragua', definition: 'Nicaraguansk córdoba', difficulty: 'medel' },
    { title: 'Niger', definition: 'Västafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Nigeria', definition: 'Nigeriansk naira', difficulty: 'medel' },
    { title: 'Nordmakedonien', definition: 'Makedonsk denar', difficulty: 'medel' },
    { title: 'Norge', definition: 'Norsk krona', difficulty: 'medel' },
    { title: 'Oman', definition: 'Omansk rial', difficulty: 'medel' },
    { title: 'Pakistan', definition: 'Pakistansk rupie', difficulty: 'medel' },
    { title: 'Palau', definition: 'USA-dollar', difficulty: 'medel' },
    { title: 'Panama', definition: 'Panamansk balboa', difficulty: 'medel' },
    { title: 'Papua Nya Guinea', definition: 'Papua nyguineansk kina', difficulty: 'medel' },
    { title: 'Paraguay', definition: 'Paraguayansk guaraní', difficulty: 'medel' },
    { title: 'Peru', definition: 'Peruansk sol', difficulty: 'medel' },
    { title: 'Filippinerna', definition: 'Filippinsk peso', difficulty: 'medel' },
    { title: 'Polen', definition: 'Polsk zloty', difficulty: 'medel' },
    { title: 'Portugal', definition: 'Euro', difficulty: 'medel' },
    { title: 'Qatar', definition: 'Qatarisk rial', difficulty: 'medel' },
    { title: 'Rumänien', definition: 'Rumänsk leu', difficulty: 'medel' },
    { title: 'Ryssland', definition: 'Rysk rubel', difficulty: 'medel' },
    { title: 'Rwanda', definition: 'Rwandisk franc', difficulty: 'medel' },
    { title: 'Saint Kitts och Nevis', definition: 'Östkaribisk dollar', difficulty: 'medel' },
    { title: 'Saint Lucia', definition: 'Östkaribisk dollar', difficulty: 'medel' },
    { title: 'Saint Vincent och Grenadinerna', definition: 'Östkaribisk dollar', difficulty: 'medel' },
    { title: 'Samoa', definition: 'Samoansk tālā', difficulty: 'medel' },
    { title: 'San Marino', definition: 'Euro', difficulty: 'medel' },
    { title: 'São Tomé och Príncipe', definition: 'Dobra', difficulty: 'medel' },
    { title: 'Saudiarabien', definition: 'Saudisk riyal', difficulty: 'medel' },
    { title: 'Senegal', definition: 'Västafrikansk CFA-franc', difficulty: 'medel' },
    { title: 'Serbien', definition: 'Serbisk dinar', difficulty: 'medel' },
    { title: 'Seychellerna', definition: 'Seychellisk rupie', difficulty: 'medel' },
    { title: 'Sierra Leone', definition: 'Leone', difficulty: 'medel' },
    { title: 'Singapore', definition: 'Singaporiansk dollar', difficulty: 'medel' },
    { title: 'Slovakien', definition: 'Euro', difficulty: 'medel' },
    { title: 'Slovenien', definition: 'Euro', difficulty: 'medel' },
    { title: 'Salomonöarna', definition: 'Salomonisk dollar', difficulty: 'medel' },
    { title: 'Somalia', definition: 'Somalisk shilling', difficulty: 'medel' },
    { title: 'Sydafrika', definition: 'Rand', difficulty: 'medel' },
    { title: 'Sydsudan', definition: 'Sydsudanesiskt pund', difficulty: 'medel' },
    { title: 'Spanien', definition: 'Euro', difficulty: 'medel' },
    { title: 'Sri Lanka', definition: 'Srilankesisk rupie', difficulty: 'medel' },
    { title: 'Sudan', definition: 'Sudanesiskt pund', difficulty: 'medel' },
    { title: 'Surinam', definition: 'Surinamesisk dollar', difficulty: 'medel' },
    { title: 'Sverige', definition: 'Svensk krona', difficulty: 'medel' },
    { title: 'Schweiz', definition: 'Schweizisk franc', difficulty: 'medel' },
    { title: 'Syrien', definition: 'Syriskt pund', difficulty: 'medel' },
  ],
  'Språk': [
    { title: 'Afghanistan', definition: 'Pashto och Dari', difficulty: 'medel' },
    { title: 'Albanien', definition: 'Albanska', difficulty: 'medel' },
    { title: 'Algeriet', definition: 'Arabiska och Berber', difficulty: 'medel' },
    { title: 'Andorra', definition: 'Katalanska', difficulty: 'medel' },
    { title: 'Angola', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Antigua och Barbuda', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Argentina', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Armenien', definition: 'Armeniska', difficulty: 'medel' },
    { title: 'Australien', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Österrike', definition: 'Tyska', difficulty: 'medel' },
    { title: 'Azerbajdzjan', definition: 'Azerbajdzjanska', difficulty: 'medel' },
    { title: 'Bahamas', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Bahrain', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Bangladesh', definition: 'Bangla', difficulty: 'medel' },
    { title: 'Barbados', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Belgien', definition: 'Nederländska, Franska, Tyska', difficulty: 'medel' },
    { title: 'Belize', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Benin', definition: 'Franska', difficulty: 'medel' },
    { title: 'Bhutan', definition: 'Dzongkha', difficulty: 'medel' },
    { title: 'Bolivia', definition: 'Spanska, Aymara, Quechua', difficulty: 'medel' },
    { title: 'Bosnien och Hercegovina', definition: 'Bosniska, Kroatiska, Serbiska', difficulty: 'medel' },
    { title: 'Botswana', definition: 'Engelska, Tswana', difficulty: 'medel' },
    { title: 'Brasilien', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Brunei', definition: 'Malajiska', difficulty: 'medel' },
    { title: 'Bulgarien', definition: 'Bulgariska', difficulty: 'medel' },
    { title: 'Burkina Faso', definition: 'Franska', difficulty: 'medel' },
    { title: 'Burundi', definition: 'Kirundi och Franska', difficulty: 'medel' },
    { title: 'Kap Verde', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Centralafrikanska republiken', definition: 'Franska och Sango', difficulty: 'medel' },
    { title: 'Tchad', definition: 'Franska och Arabiska', difficulty: 'medel' },
    { title: 'Chile', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Kina', definition: 'Mandarin', difficulty: 'medel' },
    { title: 'Komorerna', definition: 'Arabiska och Franska', difficulty: 'medel' },
    { title: 'Kongo (DR)', definition: 'Franska, Swahili och Lingala', difficulty: 'medel' },
    { title: 'Kongo (Rep.)', definition: 'Franska', difficulty: 'medel' },
    { title: 'Costa Rica', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Kroatien', definition: 'Kroatiska', difficulty: 'medel' },
    { title: 'Kuba', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Cypern', definition: 'Grekiska och Turkiska', difficulty: 'medel' },
    { title: 'Tjeckien', definition: 'Tjeckiska', difficulty: 'medel' },
    { title: 'Danmark', definition: 'Danska', difficulty: 'medel' },
    { title: 'Djibouti', definition: 'Franska och Arabiska', difficulty: 'medel' },
    { title: 'Dominica', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Dominikanska republiken', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Ecuador', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Egypten', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'El Salvador', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Ekvatorialguinea', definition: 'Spanska, Franska', difficulty: 'medel' },
    { title: 'Eritrea', definition: 'Tigrinja, Arabiska', difficulty: 'medel' },
    { title: 'Estland', definition: 'Estniska', difficulty: 'medel' },
    { title: 'Eswatini', definition: 'Swati och Engelska', difficulty: 'medel' },
    { title: 'Etiopien', definition: 'Amhariska', difficulty: 'medel' },
    { title: 'Fiji', definition: 'Engelska och Fijianska', difficulty: 'medel' },
    { title: 'Finland', definition: 'Finska och Svenska', difficulty: 'medel' },
    { title: 'Frankrike', definition: 'Franska', difficulty: 'medel' },
    { title: 'Gabon', definition: 'Franska', difficulty: 'medel' },
    { title: 'Gambia', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Georgien', definition: 'Georgiska', difficulty: 'medel' },
    { title: 'Tyskland', definition: 'Tyska', difficulty: 'medel' },
    { title: 'Ghana', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Grekland', definition: 'Grekiska', difficulty: 'medel' },
    { title: 'Grenada', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Guatemala', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Guinea', definition: 'Franska', difficulty: 'medel' },
    { title: 'Guinea-Bissau', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Guyana', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Haiti', definition: 'Franska och Haitisk kreol', difficulty: 'medel' },
    { title: 'Honduras', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Ungern', definition: 'Ungerska', difficulty: 'medel' },
    { title: 'Island', definition: 'Isländska', difficulty: 'medel' },
    { title: 'Indien', definition: 'Hindi och Engelska', difficulty: 'medel' },
    { title: 'Indonesien', definition: 'Indonesiska', difficulty: 'medel' },
    { title: 'Iran', definition: 'Persiska', difficulty: 'medel' },
    { title: 'Irak', definition: 'Arabiska och Kurdiska', difficulty: 'medel' },
    { title: 'Irland', definition: 'Irländska och Engelska', difficulty: 'medel' },
    { title: 'Israel', definition: 'Hebreiska', difficulty: 'medel' },
    { title: 'Italien', definition: 'Italienska', difficulty: 'medel' },
    { title: 'Jamaica', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Japan', definition: 'Japanska', difficulty: 'medel' },
    { title: 'Jordanien', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Kazakstan', definition: 'Kazakiska och Ryska', difficulty: 'medel' },
    { title: 'Kenya', definition: 'Swahili och Engelska', difficulty: 'medel' },
    { title: 'Kiribati', definition: 'Gilbertesiska och Engelska', difficulty: 'medel' },
    { title: 'Nordkorea', definition: 'Koreanska', difficulty: 'medel' },
    { title: 'Sydkorea', definition: 'Koreanska', difficulty: 'medel' },
    { title: 'Kuwait', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Kirgizistan', definition: 'Kirgiziska och Ryska', difficulty: 'medel' },
    { title: 'Laos', definition: 'Lao', difficulty: 'medel' },
    { title: 'Lettland', definition: 'Lettiska', difficulty: 'medel' },
    { title: 'Libanon', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Lesotho', definition: 'Sesotho och Engelska', difficulty: 'medel' },
    { title: 'Liberia', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Libyen', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Liechtenstein', definition: 'Tyska', difficulty: 'medel' },
    { title: 'Litauen', definition: 'Litauiska', difficulty: 'medel' },
    { title: 'Luxemburg', definition: 'Luxemburgska, Franska, Tyska', difficulty: 'medel' },
    { title: 'Madagaskar', definition: 'Madagaskiska och Franska', difficulty: 'medel' },
    { title: 'Malawi', definition: 'Chichewa och Engelska', difficulty: 'medel' },
    { title: 'Malaysia', definition: 'Malajiska', difficulty: 'medel' },
    { title: 'Östtimor', definition: 'Tetum och Portugisiska', difficulty: 'medel' },
    { title: 'Maldiverna', definition: 'Dhivehi', difficulty: 'medel' },
    { title: 'Mali', definition: 'Franska', difficulty: 'medel' },
    { title: 'Malta', definition: 'Maltesiska och Engelska', difficulty: 'medel' },
    { title: 'Marshallöarna', definition: 'Marshallesiska och Engelska', difficulty: 'medel' },
    { title: 'Mauretanien', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Mauritius', definition: 'Mauritisk kreol, Franska, Engelska', difficulty: 'medel' },
    { title: 'Mexiko', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Mikronesien', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Moldavien', definition: 'Rumänska', difficulty: 'medel' },
    { title: 'Monaco', definition: 'Franska', difficulty: 'medel' },
    { title: 'Mongoliet', definition: 'Mongoliska', difficulty: 'medel' },
    { title: 'Montenegro', definition: 'Montenegrinska', difficulty: 'medel' },
    { title: 'Marocko', definition: 'Arabiska och Berber', difficulty: 'medel' },
    { title: 'Moçambique', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Myanmar', definition: 'Burmese', difficulty: 'medel' },
    { title: 'Namibia', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Nauru', definition: 'Nauruiska och Engelska', difficulty: 'medel' },
    { title: 'Nepal', definition: 'Nepali', difficulty: 'medel' },
    { title: 'Nederländerna', definition: 'Nederländska', difficulty: 'medel' },
    { title: 'Nya Zeeland', definition: 'Engelska och Maori', difficulty: 'medel' },
    { title: 'Nicaragua', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Niger', definition: 'Franska', difficulty: 'medel' },
    { title: 'Nigeria', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Nordmakedonien', definition: 'Makedonska', difficulty: 'medel' },
    { title: 'Norge', definition: 'Norska', difficulty: 'medel' },
    { title: 'Oman', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Pakistan', definition: 'Urdu och Engelska', difficulty: 'medel' },
    { title: 'Palau', definition: 'Palauiska och Engelska', difficulty: 'medel' },
    { title: 'Panama', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Papua Nya Guinea', definition: 'Engelska, Tok Pisin, Hiri Motu', difficulty: 'medel' },
    { title: 'Paraguay', definition: 'Spanska och Guaraní', difficulty: 'medel' },
    { title: 'Peru', definition: 'Spanska, Quechua, Aymara', difficulty: 'medel' },
    { title: 'Filippinerna', definition: 'Filippinska och Engelska', difficulty: 'medel' },
    { title: 'Polen', definition: 'Polska', difficulty: 'medel' },
    { title: 'Portugal', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Qatar', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Rumänien', definition: 'Rumänska', difficulty: 'medel' },
    { title: 'Ryssland', definition: 'Ryska', difficulty: 'medel' },
    { title: 'Rwanda', definition: 'Kinyarwanda, Franska, Engelska', difficulty: 'medel' },
    { title: 'Saint Kitts och Nevis', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Saint Lucia', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Saint Vincent och Grenadinerna', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Samoa', definition: 'Samoanska och Engelska', difficulty: 'medel' },
    { title: 'San Marino', definition: 'Italienska', difficulty: 'medel' },
    { title: 'São Tomé och Príncipe', definition: 'Portugisiska', difficulty: 'medel' },
    { title: 'Saudiarabien', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Senegal', definition: 'Wolof och Franska', difficulty: 'medel' },
    { title: 'Serbien', definition: 'Serbiska', difficulty: 'medel' },
    { title: 'Seychellerna', definition: 'Kreol', difficulty: 'medel' },
    { title: 'Sierra Leone', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Singapore', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Slovakien', definition: 'Slovakiska', difficulty: 'medel' },
    { title: 'Slovenien', definition: 'Slovenska', difficulty: 'medel' },
    { title: 'Salomonöarna', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Somalia', definition: 'Somali', difficulty: 'medel' },
    { title: 'Sydafrika', definition: 'Engelska och Zulu', difficulty: 'medel' },
    { title: 'Sydsudan', definition: 'Engelska', difficulty: 'medel' },
    { title: 'Spanien', definition: 'Spanska', difficulty: 'medel' },
    { title: 'Sri Lanka', definition: 'Singhalesiska och Tamil', difficulty: 'medel' },
    { title: 'Sudan', definition: 'Arabiska', difficulty: 'medel' },
    { title: 'Surinam', definition: 'Nederländska', difficulty: 'medel' },
    { title: 'Sverige', definition: 'Svenska', difficulty: 'medel' },
    { title: 'Schweiz', definition: 'Tyska och Franska', difficulty: 'medel' },
    { title: 'Syrien', definition: 'Arabiska', difficulty: 'medel' },
  ],
  'Statsskick': [
    { title: 'Afghanistan', definition: 'Ej parlamentariskt', difficulty: 'svår', noFill: true },
    { title: 'Albanien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Algeriet', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Andorra', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Angola', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Antigua och Barbuda', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Argentina', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Armenien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Australien', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Österrike', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Azerbajdzjan', definition: 'President-parlamentarisk', difficulty: 'svår', noFill: true },
    { title: 'Bahamas', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Bahrain', definition: 'Semi-konstitutionell monarki', difficulty: 'svår', noFill: true },
    { title: 'Bangladesh', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Barbados', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Belgien', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Belize', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Benin', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Bhutan', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Bolivia', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Bosnien och Hercegovina', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Botswana', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Brasilien', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Brunei', definition: 'Absolut monarki', difficulty: 'svår', noFill: true },
    { title: 'Bulgarien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Burkina Faso', definition: 'Militärjunta', difficulty: 'svår', noFill: true },
    { title: 'Burundi', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kap Verde', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Centralafrikanska republiken', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Tchad', definition: 'President-parlamentarisk', difficulty: 'svår', noFill: true },
    { title: 'Chile', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kina', definition: 'Enpartistat', difficulty: 'svår', noFill: true },
    { title: 'Komorerna', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kongo (DR)', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kongo (Rep.)', definition: 'President-parlamentarisk', difficulty: 'svår', noFill: true },
    { title: 'Costa Rica', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kroatien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Kuba', definition: 'Enpartistat', difficulty: 'svår', noFill: true },
    { title: 'Cypern', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Tjeckien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Danmark', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Djibouti', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Dominica', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Dominikanska republiken', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Ecuador', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Egypten', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'El Salvador', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Ekvatorialguinea', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Eritrea', definition: 'Enpartistat', difficulty: 'svår', noFill: true },
    { title: 'Estland', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Eswatini', definition: 'Absolut monarki', difficulty: 'svår', noFill: true },
    { title: 'Etiopien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Fiji', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Finland', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Frankrike', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Gabon', definition: 'President-parlamentarisk', difficulty: 'svår', noFill: true },
    { title: 'Gambia', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Georgien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Tyskland', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Ghana', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Grekland', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Grenada', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Guatemala', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Guinea', definition: 'Militärjunta', difficulty: 'svår', noFill: true },
    { title: 'Guinea-Bissau', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Guyana', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Haiti', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Honduras', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Ungern', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Island', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Indien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Indonesien', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Iran', definition: 'Teokrati', difficulty: 'svår', noFill: true },
    { title: 'Irak', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Irland', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Israel', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Italien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Jamaica', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Japan', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Jordanien', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Kazakstan', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kenya', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kiribati', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Nordkorea', definition: 'Enpartistat', difficulty: 'svår', noFill: true },
    { title: 'Sydkorea', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Kuwait', definition: 'Semi-konstitutionell monarki', difficulty: 'svår', noFill: true },
    { title: 'Kirgizistan', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Laos', definition: 'Enpartistat', difficulty: 'svår', noFill: true },
    { title: 'Lettland', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Libanon', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Lesotho', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Liberia', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Libyen', definition: 'President-parlamentarisk', difficulty: 'svår', noFill: true },
    { title: 'Liechtenstein', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Litauen', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Luxemburg', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Madagaskar', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Malawi', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Malaysia', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Östtimor', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Maldiverna', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Mali', definition: 'Militärjunta', difficulty: 'svår', noFill: true },
    { title: 'Malta', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Marshallöarna', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Mauretanien', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Mauritius', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Mexiko', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Mikronesien', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Moldavien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Monaco', definition: 'Konstitutionell monarki', difficulty: 'svår', noFill: true },
    { title: 'Mongoliet', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Montenegro', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Marocko', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Moçambique', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Myanmar', definition: 'Militärjunta', difficulty: 'svår', noFill: true },
    { title: 'Namibia', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Nauru', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Nepal', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Nederländerna', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Nya Zeeland', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Nicaragua', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Niger', definition: 'Militärjunta', difficulty: 'svår', noFill: true },
    { title: 'Nigeria', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Nordmakedonien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Norge', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Oman', definition: 'Absolut monarki', difficulty: 'svår', noFill: true },
    { title: 'Pakistan', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Palau', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Panama', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Papua Nya Guinea', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Paraguay', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Peru', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Filippinerna', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Polen', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Portugal', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Qatar', definition: 'Absolut monarki', difficulty: 'svår', noFill: true },
    { title: 'Rumänien', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Ryssland', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Rwanda', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Saint Kitts och Nevis', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Saint Lucia', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Saint Vincent och Grenadinerna', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Samoa', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'San Marino', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'São Tomé och Príncipe', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Saudiarabien', definition: 'Absolut monarki', difficulty: 'svår', noFill: true },
    { title: 'Senegal', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Serbien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Seychellerna', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Sierra Leone', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Singapore', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Slovakien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Slovenien', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Salomonöarna', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Somalia', definition: 'Parlamentarisk federal republik', difficulty: 'svår', noFill: true },
    { title: 'Sydafrika', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Sydsudan', definition: 'Presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Spanien', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Sri Lanka', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
    { title: 'Sudan', definition: 'Militärstyre', difficulty: 'svår', noFill: true },
    { title: 'Surinam', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Sverige', definition: 'Parlamentarisk monarki', difficulty: 'svår', noFill: true },
    { title: 'Schweiz', definition: 'Parlamentarisk republik', difficulty: 'svår', noFill: true },
    { title: 'Syrien', definition: 'Semi-presidentiell', difficulty: 'svår', noFill: true },
  ],
  'Sevärdheter': [
    { title: 'Afghanistan', definition: 'Bamiyan Buddhor, Blue Mosque, Minaret Jam', difficulty: 'svår', noFill: true },
    { title: 'Albanien', definition: 'Tiranaborgen, Butrint, Ksamilstranden', difficulty: 'svår', noFill: true },
    { title: 'Algeriet', definition: 'Casbah i Alger, Saharaöknen, Romerska ruiner', difficulty: 'svår', noFill: true },
    { title: 'Andorra', definition: 'Pyrenéernas skidorter, Casa de la Vall, Caldea spa', difficulty: 'svår', noFill: true },
    { title: 'Angola', definition: 'Luandas skyline, Kissama nationalpark, Slavrutten', difficulty: 'svår', noFill: true },
    { title: 'Antigua och Barbuda', definition: '365 stränder, Nelsons skeppsvarv, Stingray City', difficulty: 'svår', noFill: true },
    { title: 'Argentina', definition: 'Iguazufallen, Perito Moreno-glaciären, Buenos Aires tangoscen', difficulty: 'svår', noFill: true },
    { title: 'Armenien', definition: 'Sevansjön, Garnitemplet, Tatevklostret', difficulty: 'svår', noFill: true },
    { title: 'Australien', definition: 'Sydneys operahus, Stora barriärrevet, Uluru', difficulty: 'svår', noFill: true },
    { title: 'Österrike', definition: 'Wienoperan, Alpernas skidorter, Salzburg', difficulty: 'svår', noFill: true },
    { title: 'Azerbajdzjan', definition: 'Gamla staden i Baku, Gobustan-klipporna, Flame Towers', difficulty: 'svår', noFill: true },
    { title: 'Bahamas', definition: 'Nassau-stränder, Exuma Cays, Atlantis Resort', difficulty: 'svår', noFill: true },
    { title: 'Bahrain', definition: 'Bahrainfortet, Qal\'at al-Bahrain, Pearl Monument', difficulty: 'svår', noFill: true },
    { title: 'Bangladesh', definition: 'Sundarbans mangrove, Cox\'s Bazar-stranden, Sonargaons ruiner', difficulty: 'svår', noFill: true },
    { title: 'Barbados', definition: 'Harrisons grotta, Bathsheba-stranden, Animal Flower-grottan', difficulty: 'svår', noFill: true },
    { title: 'Belgien', definition: 'Brygges kanaler, Grand Place, Atomium', difficulty: 'svår', noFill: true },
    { title: 'Belize', definition: 'Great Blue Hole, Belize barriärrev, Mayaruiner', difficulty: 'svår', noFill: true },
    { title: 'Benin', definition: 'Pendjari nationalpark, Ouidahs slavrutt, Abomey-palatset', difficulty: 'svår', noFill: true },
    { title: 'Bhutan', definition: 'Paro Taktsang, Punakha Dzong, Tigernästet', difficulty: 'svår', noFill: true },
    { title: 'Bolivia', definition: 'Salar de Uyuni, La Paz linbana, Tiwanaku-ruiner', difficulty: 'svår', noFill: true },
    { title: 'Bosnien och Hercegovina', definition: 'Mostarbron, Sarajevos basar, Jajces vattenfall', difficulty: 'svår', noFill: true },
    { title: 'Botswana', definition: 'Okavangodeltat, Chobe nationalpark, Kalahariöknen', difficulty: 'svår', noFill: true },
    { title: 'Brasilien', definition: 'Kristusåterlösaren, Iguazufallen, Amazonas regnskog', difficulty: 'svår', noFill: true },
    { title: 'Brunei', definition: 'Sultan Omar Ali Saifuddin-moskén, Kampong Ayer, Ulu Temburong nationalpark', difficulty: 'svår', noFill: true },
    { title: 'Bulgarien', definition: 'Rila-klostret, Plovdivs gamla stad, Trakiska gravar', difficulty: 'svår', noFill: true },
    { title: 'Burkina Faso', definition: 'Ouagadougou-marknaden, Sindou-topparna, Arly nationalpark', difficulty: 'svår', noFill: true },
    { title: 'Burundi', definition: 'Tanganyikasjön, Kibira nationalpark, Gitega trumfestival', difficulty: 'svår', noFill: true },
    { title: 'Kap Verde', definition: 'Sal-stränder, Fogo-vulkanen, Cidade Velha', difficulty: 'svår', noFill: true },
    { title: 'Centralafrikanska republiken', definition: 'Dzanga-Sangha-reservatet, Notre-Dame-katedralen, Boali-fallen', difficulty: 'svår', noFill: true },
    { title: 'Tchad', definition: 'Zakouma nationalpark, Saharaöknen, Tchadsjön', difficulty: 'svår', noFill: true },
    { title: 'Chile', definition: 'Torres del Paine, Valparaiso gatukonst, Atacamaöknen', difficulty: 'svår', noFill: true },
    { title: 'Kina', definition: 'Kinesiska muren, Förbjudna staden, Terrakottaarmén', difficulty: 'svår', noFill: true },
    { title: 'Komorerna', definition: 'Karthala-vulkanen, Moheli marina park, Mitsamiouli-stranden', difficulty: 'svår', noFill: true },
    { title: 'Kongo (DR)', definition: 'Virunga nationalpark, Kongofloden, Nyiragongo-vulkanen', difficulty: 'svår', noFill: true },
    { title: 'Kongo (Rep.)', definition: 'Pointe-Noire-stranden, Odzala nationalpark, Brazzaville-katedralen', difficulty: 'svår', noFill: true },
    { title: 'Costa Rica', definition: 'Manuel Antonio nationalpark, Arenal-vulkanen, Monteverde molnskog', difficulty: 'svår', noFill: true },
    { title: 'Kroatien', definition: 'Dubrovniks murar, Plitvicesjöarna, Diocletianus palats', difficulty: 'svår', noFill: true },
    { title: 'Kuba', definition: 'Havannas gamla stad, Varadero-stranden, Viñales-dalen', difficulty: 'svår', noFill: true },
    { title: 'Cypern', definition: 'Paphos arkeologiska park, Nissi-stranden, Kykkos-klostret', difficulty: 'svår', noFill: true },
    { title: 'Tjeckien', definition: 'Pragborgen, Karlsbron, Český Krumlov', difficulty: 'svår', noFill: true },
    { title: 'Danmark', definition: 'Tivoli, Nyhavn, Den lilla sjöjungfrun', difficulty: 'svår', noFill: true },
    { title: 'Djibouti', definition: 'Assalsjön, Ghoubet-bukten, Day Forest nationalpark', difficulty: 'svår', noFill: true },
    { title: 'Dominica', definition: 'Boiling Lake, Trafalgar-fallen, Emerald Pool', difficulty: 'svår', noFill: true },
    { title: 'Dominikanska republiken', definition: 'Punta Cana, Zona Colonial, Pico Duarte', difficulty: 'svår', noFill: true },
    { title: 'Ecuador', definition: 'Galapagosöarna, Quito historiska centrum, Cotopaxi-vulkanen', difficulty: 'svår', noFill: true },
    { title: 'Egypten', definition: 'Giza-pyramiderna, Luxor-templet, Röda havet', difficulty: 'svår', noFill: true },
    { title: 'El Salvador', definition: 'Santa Ana-vulkanen, Joya de Cerén, Surf City', difficulty: 'svår', noFill: true },
    { title: 'Ekvatorialguinea', definition: 'Malabo-katedralen, Monte Alén, Bata-stranden', difficulty: 'svår', noFill: true },
    { title: 'Eritrea', definition: 'Asmaras arkitektur, Dahlak-arkipelagen, Adulis-ruiner', difficulty: 'svår', noFill: true },
    { title: 'Estland', definition: 'Tallinns gamla stad, Lahemaa nationalpark, Saaremaa', difficulty: 'svår', noFill: true },
    { title: 'Eswatini', definition: 'Mlilwane wildlife sanctuary, Hlane nationalpark, Mantenga-kulturby', difficulty: 'svår', noFill: true },
    { title: 'Etiopien', definition: 'Lalibela-kyrkorna, Simien-bergen, Aksum-obeliskerna', difficulty: 'svår', noFill: true },
    { title: 'Fiji', definition: 'Yasawa-öarna, Garden of the Sleeping Giant, Sigatoka sanddyner', difficulty: 'svår', noFill: true },
    { title: 'Finland', definition: 'Helsingfors domkyrka, Lapplands norrsken, Sveaborg', difficulty: 'svår', noFill: true },
    { title: 'Frankrike', definition: 'Eiffeltornet, Louvren, Mont Saint-Michel', difficulty: 'svår', noFill: true },
    { title: 'Gabon', definition: 'Loango nationalpark, Ivindo-fallen, Libreville-stranden', difficulty: 'svår', noFill: true },
    { title: 'Gambia', definition: 'Gambiafloden, Bijilo-skogen, Kunta Kinteh-ön', difficulty: 'svår', noFill: true },
    { title: 'Georgien', definition: 'Gamla Tbilisi, Kazbegi-bergen, Vardzia-klostret', difficulty: 'svår', noFill: true },
    { title: 'Tyskland', definition: 'Brandenburger Tor, Neuschwanstein-slottet, Kölnerdomen', difficulty: 'svår', noFill: true },
    { title: 'Ghana', definition: 'Kakum nationalpark, Cape Coast-slottet, Labadi-stranden', difficulty: 'svår', noFill: true },
    { title: 'Grekland', definition: 'Akropolis, Santorini, Delfi', difficulty: 'svår', noFill: true },
    { title: 'Grenada', definition: 'Grand Anse-stranden, Underwater Sculpture Park, Annandale-fallen', difficulty: 'svår', noFill: true },
    { title: 'Guatemala', definition: 'Tikal-ruiner, Atitlán-sjön, Antigua Guatemala', difficulty: 'svår', noFill: true },
    { title: 'Guinea', definition: 'Mount Nimba, Bridal Veil-fallen, Conakry-stora moskén', difficulty: 'svår', noFill: true },
    { title: 'Guinea-Bissau', definition: 'Bijagós-arkipelagen, Bissau gamla stad, Varela-stranden', difficulty: 'svår', noFill: true },
    { title: 'Guyana', definition: 'Kaieteur-fallen, Iwokrama-skogen, Georgetowns botaniska trädgård', difficulty: 'svår', noFill: true },
    { title: 'Haiti', definition: 'Citadelle Laferrière, Labadee, Jacmel-stränder', difficulty: 'svår', noFill: true },
    { title: 'Honduras', definition: 'Copán-ruiner, Roatán, Cayos Cochinos', difficulty: 'svår', noFill: true },
    { title: 'Ungern', definition: 'Parlamentshuset, Balatonsjön, Budaslottet', difficulty: 'svår', noFill: true },
    { title: 'Island', definition: 'Blå lagunen, Gyllene cirkeln, Jökulsárlón', difficulty: 'svår', noFill: true },
    { title: 'Indien', definition: 'Taj Mahal, Ganges, Kerala backwaters', difficulty: 'svår', noFill: true },
    { title: 'Indonesien', definition: 'Bali, Borobudur, Komodo-parken', difficulty: 'svår', noFill: true },
    { title: 'Iran', definition: 'Persepolis, Isfahan, Shiraz', difficulty: 'svår', noFill: true },
    { title: 'Irak', definition: 'Babylon, Najaf, Erbil-citadellet', difficulty: 'svår', noFill: true },
    { title: 'Irland', definition: 'Cliffs of Moher, Ring of Kerry, Guinness Storehouse', difficulty: 'svår', noFill: true },
    { title: 'Israel', definition: 'Gamla stan i Jerusalem, Tel Aviv-stränder, Döda havet', difficulty: 'svår', noFill: true },
    { title: 'Italien', definition: 'Colosseum, Venedig, Uffizierna', difficulty: 'svår', noFill: true },
    { title: 'Jamaica', definition: 'Dunn\'s River Falls, Seven Mile Beach, Bob Marley-museet', difficulty: 'svår', noFill: true },
    { title: 'Japan', definition: 'Mount Fuji, Kyoto-tempel, Tokyo Shibuya', difficulty: 'svår', noFill: true },
    { title: 'Jordanien', definition: 'Petra, Wadi Rum, Döda havet', difficulty: 'svår', noFill: true },
    { title: 'Kazakstan', definition: 'Charyn Canyon, Almaty, Astana Baiterek', difficulty: 'svår', noFill: true },
    { title: 'Kenya', definition: 'Masai Mara, Mount Kenya, Lamu', difficulty: 'svår', noFill: true },
    { title: 'Kiribati', definition: 'Tarawa-lagunen, Kiritimati, Abaiang', difficulty: 'svår', noFill: true },
    { title: 'Nordkorea', definition: 'Pyongyang, Kumgang-bergen, Myohyang-bergen', difficulty: 'svår', noFill: true },
    { title: 'Sydkorea', definition: 'Gyeongbokgung, Jeju-ön, N Seoul Tower', difficulty: 'svår', noFill: true },
    { title: 'Kuwait', definition: 'Kuwait Towers, Grand Mosque, Souq Al-Mubarakiya', difficulty: 'svår', noFill: true },
    { title: 'Kirgizistan', definition: 'Issyk-Kul, Ala-Archa, Song-Kul', difficulty: 'svår', noFill: true },
    { title: 'Laos', definition: 'Luang Prabang, Vang Vieng, Plain of Jars', difficulty: 'svår', noFill: true },
    { title: 'Lettland', definition: 'Gamla Riga, Gauja nationalpark, Rundāle-palatset', difficulty: 'svår', noFill: true },
    { title: 'Libanon', definition: 'Baalbek, Jeita-grottorna, Byblos', difficulty: 'svår', noFill: true },
    { title: 'Lesotho', definition: 'Maloti-bergen, Katse-dammen, Thaba Bosiu', difficulty: 'svår', noFill: true },
    { title: 'Liberia', definition: 'Sapo nationalpark, Monrovia, Robertsport', difficulty: 'svår', noFill: true },
    { title: 'Libyen', definition: 'Leptis Magna, Sabratha, Ghadames', difficulty: 'svår', noFill: true },
    { title: 'Liechtenstein', definition: 'Vaduz slott, Malbun, Gutenberg slott', difficulty: 'svår', noFill: true },
    { title: 'Litauen', definition: 'Vilnius gamla stad, Trakai-slottet, Kuriska näset', difficulty: 'svår', noFill: true },
    { title: 'Luxemburg', definition: 'Bock-kasematterna, Vianden-slottet, Grund', difficulty: 'svår', noFill: true },
    { title: 'Madagaskar', definition: 'Baobab-allén, Tsingy de Bemaraha, Ranomafana', difficulty: 'svår', noFill: true },
    { title: 'Malawi', definition: 'Malawisjön, Mulanje-berget, Liwonde nationalpark', difficulty: 'svår', noFill: true },
    { title: 'Malaysia', definition: 'Petronas Towers, Batu-grottorna, Langkawi', difficulty: 'svår', noFill: true },
    { title: 'Östtimor', definition: 'Cristo Rei, Atauro-ön, Jaco-ön', difficulty: 'svår', noFill: true },
    { title: 'Maldiverna', definition: 'Atoller, Male, Undervattensrestauranger', difficulty: 'svår', noFill: true },
    { title: 'Mali', definition: 'Timbuktu, Djenné, Dogonlandet', difficulty: 'svår', noFill: true },
    { title: 'Malta', definition: 'Valletta, Blå lagunen, Mdina', difficulty: 'svår', noFill: true },
    { title: 'Marshallöarna', definition: 'Bikiniatollen, Majuro, Arno', difficulty: 'svår', noFill: true },
    { title: 'Mauretanien', definition: 'Chinguetti, Banc d\'Arguin, Sahara', difficulty: 'svår', noFill: true },
    { title: 'Mauritius', definition: 'Chamarel, Grand Baie, Le Morne', difficulty: 'svår', noFill: true },
    { title: 'Mexiko', definition: 'Chichén Itzá, Cancún, Mexico City', difficulty: 'svår', noFill: true },
    { title: 'Mikronesien', definition: 'Nan Madol, Pohnpei, Yap', difficulty: 'svår', noFill: true },
    { title: 'Moldavien', definition: 'Orheiul Vechi, Cricova, Chișinău', difficulty: 'svår', noFill: true },
    { title: 'Monaco', definition: 'Monte Carlo Casino, Furstepalatset, Oceanografiska museet', difficulty: 'svår', noFill: true },
    { title: 'Mongoliet', definition: 'Gobiöknen, Terelj, Ulaanbaatar', difficulty: 'svår', noFill: true },
    { title: 'Montenegro', definition: 'Kotorbukten, Budva, Durmitor', difficulty: 'svår', noFill: true },
    { title: 'Marocko', definition: 'Marrakesh, Sahara, Chefchaouen', difficulty: 'svår', noFill: true },
    { title: 'Moçambique', definition: 'Bazaruto, Maputo, Gorongosa', difficulty: 'svår', noFill: true },
    { title: 'Myanmar', definition: 'Bagan, Shwedagon, Inlesjön', difficulty: 'svår', noFill: true },
    { title: 'Namibia', definition: 'Sossusvlei, Etosha, Fish River Canyon', difficulty: 'svår', noFill: true },
    { title: 'Nauru', definition: 'Anibarebukten, Command Ridge, Buada-lagunen', difficulty: 'svår', noFill: true },
    { title: 'Nepal', definition: 'Everest, Pokhara, Pashupatinath', difficulty: 'svår', noFill: true },
    { title: 'Nederländerna', definition: 'Amsterdam, Keukenhof, Zaanse Schans', difficulty: 'svår', noFill: true },
    { title: 'Nya Zeeland', definition: 'Milford Sound, Queenstown, Hobbiton', difficulty: 'svår', noFill: true },
    { title: 'Nicaragua', definition: 'Ometepe, Granada, Corn Islands', difficulty: 'svår', noFill: true },
    { title: 'Niger', definition: 'Agadez, W nationalpark, Sahara', difficulty: 'svår', noFill: true },
    { title: 'Nigeria', definition: 'Zuma-klippan, Yankari, Lagos', difficulty: 'svår', noFill: true },
    { title: 'Nordmakedonien', definition: 'Ohridsjön, Skopje, Matka-kanjonen', difficulty: 'svår', noFill: true },
    { title: 'Norge', definition: 'Geirangerfjorden, Lofoten, Oslo', difficulty: 'svår', noFill: true },
    { title: 'Oman', definition: 'Muscat, Wahiba Sands, Nizwa', difficulty: 'svår', noFill: true },
    { title: 'Pakistan', definition: 'K2, Lahore, Hunza-dalen', difficulty: 'svår', noFill: true },
    { title: 'Palau', definition: 'Rock Islands, Jellyfish Lake, Koror', difficulty: 'svår', noFill: true },
    { title: 'Panama', definition: 'Panamakanalen, Casco Viejo, San Blas-öarna', difficulty: 'svår', noFill: true },
    { title: 'Papua Nya Guinea', definition: 'Kokoda-leden, Port Moresby, Mount Hagen', difficulty: 'svår', noFill: true },
    { title: 'Paraguay', definition: 'Asunción, Iguazú-fallen, Missionsruiner', difficulty: 'svår', noFill: true },
    { title: 'Peru', definition: 'Machu Picchu, Cusco, Lima', difficulty: 'svår', noFill: true },
    { title: 'Filippinerna', definition: 'Boracay, Palawan, Manila', difficulty: 'svår', noFill: true },
    { title: 'Polen', definition: 'Kraków, Auschwitz, Warszawa', difficulty: 'svår', noFill: true },
    { title: 'Portugal', definition: 'Lissabon, Porto, Algarve', difficulty: 'svår', noFill: true },
    { title: 'Qatar', definition: 'Doha, Souq Waqif, Inland Sea', difficulty: 'svår', noFill: true },
    { title: 'Rumänien', definition: 'Bran-slottet, Bukarest, Transsylvanien', difficulty: 'svår', noFill: true },
    { title: 'Ryssland', definition: 'Röda torget, Eremitaget, Bajkalsjön', difficulty: 'svår', noFill: true },
    { title: 'Rwanda', definition: 'Volcanoes nationalpark, Kigali, Kivusjön', difficulty: 'svår', noFill: true },
    { title: 'Saint Kitts och Nevis', definition: 'Brimstone Hill, Nevis Peak, Frigate Bay', difficulty: 'svår', noFill: true },
    { title: 'Saint Lucia', definition: 'Pitons, Soufrière, Rodney Bay', difficulty: 'svår', noFill: true },
    { title: 'Saint Vincent och Grenadinerna', definition: 'Tobago Cays, La Soufrière, Bequia', difficulty: 'svår', noFill: true },
    { title: 'Samoa', definition: 'To Sua Ocean Trench, Apia, Savai\'i', difficulty: 'svår', noFill: true },
    { title: 'San Marino', definition: 'Guaita-tornet, Palazzo Pubblico, Mount Titano', difficulty: 'svår', noFill: true },
    { title: 'São Tomé och Príncipe', definition: 'Obo nationalpark, Príncipe, Boca do Inferno', difficulty: 'svår', noFill: true },
    { title: 'Saudiarabien', definition: 'Al-Ula, Mecka, Jeddah', difficulty: 'svår', noFill: true },
    { title: 'Senegal', definition: 'Gorée, Dakar, Retba', difficulty: 'svår', noFill: true },
    { title: 'Serbien', definition: 'Belgrad, Kalemegdan, Tara', difficulty: 'svår', noFill: true },
    { title: 'Seychellerna', definition: 'Anse Source, Vallée de Mai, Mahé', difficulty: 'svår', noFill: true },
    { title: 'Sierra Leone', definition: 'Bunce Island, Freetown, Tiwai', difficulty: 'svår', noFill: true },
    { title: 'Singapore', definition: 'Gardens by the Bay, Marina Bay, Sentosa', difficulty: 'svår', noFill: true },
    { title: 'Slovakien', definition: 'Bratislava, Tatrabergen, Spiš', difficulty: 'svår', noFill: true },
    { title: 'Slovenien', definition: 'Bled, Ljubljana, Postojna', difficulty: 'svår', noFill: true },
    { title: 'Salomonöarna', definition: 'Honiara, Marovo, Tulagi', difficulty: 'svår', noFill: true },
    { title: 'Somalia', definition: 'Mogadishu, Laas Geel, Golis', difficulty: 'svår', noFill: true },
    { title: 'Sydafrika', definition: 'Taffelberget, Kruger, Kapstaden', difficulty: 'svår', noFill: true },
    { title: 'Sydsudan', definition: 'Boma, Juba, Nilen', difficulty: 'svår', noFill: true },
    { title: 'Spanien', definition: 'Sagrada Família, Alhambra, Prado', difficulty: 'svår', noFill: true },
    { title: 'Sri Lanka', definition: 'Sigiriya, Kandy, Galle', difficulty: 'svår', noFill: true },
    { title: 'Sudan', definition: 'Meroë, Nilen, Khartoum', difficulty: 'svår', noFill: true },
    { title: 'Surinam', definition: 'Paramaribo, Brownsberg, Central Suriname', difficulty: 'svår', noFill: true },
    { title: 'Sverige', definition: 'Stockholm, Vasamuseet, Lappland', difficulty: 'svår', noFill: true },
    { title: 'Schweiz', definition: 'Matterhorn, Zürich, Genève', difficulty: 'svår', noFill: true },
    { title: 'Syrien', definition: 'Damaskus, Aleppo, Palmyra', difficulty: 'svår', noFill: true },
  ],
  'Ledare (färskvara)': [
    { title: 'Sverige', definition: 'Ulf Kristersson (M) — Statsminister sedan 2022, leder en M/KD/L-regering med stöd av SD. Tog Sverige in i Nato och har fokuserat på lag och ordning samt energifrågor.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Norge', definition: 'Jonas Gahr Støre (Ap) — Statsminister sedan 2021, leder Arbeiderpartiet. Har styrt under hög energiprisdebatt och Norges roll som gasleverantör till Europa.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Danmark', definition: 'Mette Frederiksen (S) — Statsminister sedan 2019, socialdemokrat. Känd för stram migrationspolitik och bred mittensamarbetsregering.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Finland', definition: 'Petteri Orpo (Saml.) — Statsminister sedan 2023, leder Samlingspartiet. Fokus på budgetåtstramningar och Finlands färska Nato-medlemskap.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Tyskland', definition: 'Friedrich Merz (CDU) — Förbundskansler sedan 2025 efter CDU:s valseger, efterträdde Olaf Scholz. Inriktning på ekonomi och försvarsupprustning.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Frankrike', definition: 'Emmanuel Macron (Renaissance) — President sedan 2017, centerliberal. Driver pensions- och arbetsmarknadsreformer och en stark EU- och försvarslinje.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Storbritannien', definition: 'Keir Starmer (Labour) — Premiärminister sedan 2024 efter Labours jordskredsseger. Fokus på ekonomisk stabilitet och offentlig sektor.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Italien', definition: 'Giorgia Meloni (FdI) — Premiärminister sedan 2022, Italiens första kvinnliga regeringschef, leder högerkoalition med Fratelli d\'Italia.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Spanien', definition: 'Pedro Sánchez (PSOE) — Premiärminister sedan 2018, socialist. Leder minoritetskoalition och har drivit sociala reformer och amnestifrågan i Katalonien.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Nederländerna', definition: 'Dick Schoof (oberoende) — Premiärminister sedan 2024, partilös ämbetsman som leder en högerkoalition byggd kring Geert Wilders PVV.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Polen', definition: 'Donald Tusk (KO) — Premiärminister sedan 2023, tidigare EU-rådsordförande. Vände landet i mer EU-vänlig riktning efter PiS-styret.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Ukraina', definition: 'Volodymyr Zelenskyj — President sedan 2019. Leder landets försvar mot Rysslands fullskaliga invasion sedan 2022 och en symbol för motståndet.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Ryssland', definition: 'Vladimir Putin — President (med avbrott som premiärminister) sedan 2000. Centraliserad makt; inledde invasionen av Ukraina 2022.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'USA', definition: 'Donald Trump (Republikan) — President; tillträdde sin andra mandatperiod i januari 2025 efter valsegern 2024. Känd för tullpolitik och hård migrationslinje.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Kanada', definition: 'Mark Carney (Liberal) — Premiärminister sedan 2025, tidigare centralbankschef. Efterträdde Justin Trudeau som Liberalernas ledare.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Kina', definition: 'Xi Jinping — Ledare sedan 2012 (generalsekreterare i kommunistpartiet och president). Avskaffade presidentens mandatgräns; starkt centraliserat styre.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Japan', definition: 'Shigeru Ishiba (LDP) — Premiärminister sedan 2024, leder Liberaldemokraterna. Bakgrund inom försvarsfrågor.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Indien', definition: 'Narendra Modi (BJP) — Premiärminister sedan 2014, hindunationalist. Känd för ekonomisk modernisering och digitalisering, omvald 2024.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Brasilien', definition: 'Luiz Inácio Lula da Silva (PT) — President sedan 2023 (även 2003–2010), vänsterledare. Fokus på sociala program och Amazonas-skydd.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Argentina', definition: 'Javier Milei (LLA) — President sedan 2023, libertariansk ekonom. Drastiska nedskärningar och avreglering för att bekämpa inflationen.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Mexiko', definition: 'Claudia Sheinbaum (Morena) — President sedan 2024, Mexikos första kvinnliga president. Fortsätter vänsterrörelsens politik från företrädaren López Obrador.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Australien', definition: 'Anthony Albanese (Labor) — Premiärminister sedan 2022, socialdemokrat. Fokus på klimat, ekonomi och AUKUS-försvarssamarbetet.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Israel', definition: 'Benjamin Netanyahu (Likud) — Premiärminister (längst sittande i landets historia), högerledare. Leder landet genom kriget i Gaza efter attacken 7 oktober 2023.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Turkiet', definition: 'Recep Tayyip Erdoğan (AKP) — President sedan 2014 (tidigare premiärminister). Stärkt presidentmakt och en aktiv utrikespolitik i regionen.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Sydkorea', definition: 'Lee Jae-myung (Demokraterna) — President sedan 2025, vald efter en politisk kris. Liberal inriktning och dialog med grannländerna.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Saudiarabien', definition: 'Mohammed bin Salman — Kronprins och premiärminister, landets de facto-ledare. Driver moderniseringsprogrammet Vision 2030.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Sydafrika', definition: 'Cyril Ramaphosa (ANC) — President sedan 2018. Leder efter 2024 en samlingsregering sedan ANC förlorat egen majoritet för första gången.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Grekland', definition: 'Kyriakos Mitsotakis (Ny demokrati) — Premiärminister sedan 2019, mittenhöger. Fokus på ekonomisk återhämtning efter skuldkrisen.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Ungern', definition: 'Viktor Orbán (Fidesz) — Premiärminister sedan 2010, nationalkonservativ. Känd för konflikter med EU om rättsstat och migration.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Portugal', definition: 'Luís Montenegro (PSD) — Premiärminister sedan 2024, mittenhöger. Leder en minoritetsregering.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Irland', definition: 'Micheál Martin (Fianna Fáil) — Taoiseach (premiärminister); roterar ledarskapet i koalition med Fine Gael.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Österrike', definition: 'Karl Nehammer-efterträdare / koalitionsledd — Politiskt skifte efter valet 2024 där FPÖ blev störst; regeringsbildningen präglades av svåra koalitionsförhandlingar.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Schweiz', definition: 'Förbundsrådet (roterande) — Styrs av ett sjuhövdat förbundsråd där presidentposten roterar årligen — ingen enskild premiärminister.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Indonesien', definition: 'Prabowo Subianto (Gerindra) — President sedan 2024, tidigare försvarsminister och general. Vann valet i en jordskredsseger.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Nigeria', definition: 'Bola Tinubu (APC) — President sedan 2023. Genomförde kontroversiella subventionsnedskärningar på bränsle för att sanera ekonomin.', difficulty: 'svår', noFill: true, stale: true },
    { title: 'Egypten', definition: 'Abdel Fattah el-Sisi — President sedan 2014, tidigare arméchef. Stora infrastrukturprojekt och hård säkerhetspolitik.', difficulty: 'svår', noFill: true, stale: true },
  ],
};
