// Sport-data: Basket (NBA 2025-26) och Golf

export const sport = {
  Basket: [
    // ---- LAG (titel = lag, definition = tränare + nyckelspelare) ----
    { title: 'Chicago Bulls', definition: 'HC: Billy Donovan. Nyckelspelare: Coby White, Josh Giddey, Collin Sexton, Matas Buzelis.', difficulty: 'medel' },
    { title: 'Cleveland Cavaliers', definition: 'HC: Kenny Atkinson. Nyckelspelare: Donovan Mitchell, James Harden, Evan Mobley, Darius Garland.', difficulty: 'medel' },
    { title: 'Detroit Pistons', definition: 'HC: J.B. Bickerstaff. Nyckelspelare: Cade Cunningham, Jalen Duren, Ausar Thompson, Tobias Harris.', difficulty: 'medel' },
    { title: 'Indiana Pacers', definition: 'HC: Rick Carlisle. Nyckelspelare: Pascal Siakam, Bennedict Mathurin, Andrew Nembhard, Tyrese Haliburton.', difficulty: 'medel' },
    { title: 'Milwaukee Bucks', definition: 'HC: Doc Rivers. Nyckelspelare: Giannis Antetokounmpo, Kevin Porter Jr., Kyle Kuzma, Myles Turner.', difficulty: 'medel' },
    { title: 'Atlanta Hawks', definition: 'HC: Quin Snyder. Nyckelspelare: Jalen Johnson, Dyson Daniels, Nickeil Alexander-Walker, CJ McCollum.', difficulty: 'medel' },
    { title: 'Charlotte Hornets', definition: 'HC: Charles Lee. Nyckelspelare: LaMelo Ball, Brandon Miller, Kon Knueppel, Miles Bridges.', difficulty: 'medel' },
    { title: 'Miami Heat', definition: 'HC: Erik Spoelstra. Nyckelspelare: Tyler Herro, Bam Adebayo, Norman Powell, Andrew Wiggins.', difficulty: 'medel' },
    { title: 'Orlando Magic', definition: 'HC: Jamahl Mosley. Nyckelspelare: Paolo Banchero, Franz Wagner, Desmond Bane, Jalen Suggs.', difficulty: 'medel' },
    { title: 'Washington Wizards', definition: 'HC: Brian Keefe. Nyckelspelare: Alex Sarr, Trae Young, Anthony Davis, Bilal Coulibaly.', difficulty: 'medel' },
    { title: 'Denver Nuggets', definition: 'HC: David Adelman. Nyckelspelare: Nikola Jokić, Jamal Murray, Aaron Gordon, Cameron Johnson.', difficulty: 'medel' },
    { title: 'Minnesota Timberwolves', definition: 'HC: Chris Finch. Nyckelspelare: Anthony Edwards, Julius Randle, Jaden McDaniels, Rudy Gobert.', difficulty: 'medel' },
    { title: 'Oklahoma City Thunder', definition: 'HC: Mark Daigneault. Nyckelspelare: Shai Gilgeous-Alexander, Jalen Williams, Chet Holmgren, Isaiah Hartenstein.', difficulty: 'medel' },
    { title: 'Portland Trail Blazers', definition: 'HC: Chauncey Billups. Nyckelspelare: Deni Avdija, Shaedon Sharpe, Jerami Grant, Donovan Clingan.', difficulty: 'medel' },
    { title: 'Utah Jazz', definition: 'HC: Will Hardy. Nyckelspelare: Lauri Markkanen, Keyonte George, Jaren Jackson Jr., Walker Kessler.', difficulty: 'medel' },
    { title: 'Golden State Warriors', definition: 'HC: Steve Kerr. Nyckelspelare: Stephen Curry, Jimmy Butler, Draymond Green, Kristaps Porziņģis.', difficulty: 'medel' },
    { title: 'LA Clippers', definition: 'HC: Tyronn Lue. Nyckelspelare: Kawhi Leonard, James Harden, Ivica Zubac, John Collins.', difficulty: 'medel' },
    { title: 'Los Angeles Lakers', definition: 'HC: JJ Redick. Nyckelspelare: Luka Dončić, LeBron James, Austin Reaves, Deandre Ayton.', difficulty: 'medel' },
    { title: 'Phoenix Suns', definition: 'HC: Mike Budenholzer. Nyckelspelare: Devin Booker, Dillon Brooks, Jalen Green, Mark Williams.', difficulty: 'medel' },
    { title: 'Sacramento Kings', definition: 'HC: Doug Christie. Nyckelspelare: Zach LaVine, DeMar DeRozan, Domantas Sabonis, Russell Westbrook.', difficulty: 'medel' },

    // ---- STJÄRNSPELARE (titel = spelare, definition = lag, nr, nation, stats) ----
    { title: 'Shai Gilgeous-Alexander', definition: 'OKC #2 | Kanada | 31.1 PPG / 5.4 RPG / 6.6 APG', difficulty: 'lätt' },
    { title: 'Luka Dončić', definition: 'LAL #77 | Slovenien | 33.5 PPG / 7.7 RPG / 8.3 APG', difficulty: 'lätt' },
    { title: 'Nikola Jokić', definition: 'DEN #15 | Serbien | 27.7 PPG / 12.9 RPG / 10.7 APG (trippeldubbel-snitt)', difficulty: 'lätt' },
    { title: 'Anthony Edwards', definition: 'MIN #5 | USA | 28.8 PPG / 5.4 RPG / 3.7 APG', difficulty: 'lätt' },
    { title: 'Giannis Antetokounmpo', definition: 'MIL #34 | Grekland | 27.6 PPG / 9.8 RPG / 5.4 APG', difficulty: 'lätt' },
    { title: 'Donovan Mitchell', definition: 'CLE #45 | USA | 27.9 PPG / 5.1 RPG / 5.7 APG', difficulty: 'lätt' },
    { title: 'Kawhi Leonard', definition: 'LAC #2 | USA | 27.9 PPG / 6.4 RPG / 3.6 APG', difficulty: 'lätt' },
    { title: 'Stephen Curry', definition: 'GSW #30 | USA | 26.6 PPG / 3.6 RPG / 4.7 APG', difficulty: 'lätt' },
    { title: 'Lauri Markkanen', definition: 'UTA #11 | Finland | 26.7 PPG / 8.4 RPG / 2.8 APG', difficulty: 'lätt' },
    { title: 'Devin Booker', definition: 'PHX #1 | USA | 26.1 PPG / 3.9 RPG / 6.0 APG', difficulty: 'lätt' },
    { title: 'Jamal Murray', definition: 'DEN #27 | Kanada | 25.4 PPG / 4.8 RPG / 7.1 APG', difficulty: 'lätt' },
    { title: 'Cade Cunningham', definition: 'DET #2 | USA | 23.9 PPG / 5.5 RPG / 9.9 APG', difficulty: 'lätt' },
    { title: 'Deni Avdija', definition: 'POR #8 | Israel | 24.2 PPG / 6.9 RPG / 6.7 APG', difficulty: 'medel' },
    { title: 'Pascal Siakam', definition: 'IND #43 | Kamerun | 24.0 PPG / 6.6 RPG / 3.8 APG', difficulty: 'medel' },
    { title: 'Austin Reaves', definition: 'LAL #15 | USA | 23.3 PPG / 4.2 RPG / 5.5 APG', difficulty: 'medel' },
    { title: 'Jalen Johnson', definition: 'ATL #1 | USA | 22.5 PPG / 10.3 RPG / 7.9 APG', difficulty: 'medel' },
    { title: 'Paolo Banchero', definition: 'ORL #5 | USA | 22.3 PPG / 8.4 RPG / 5.1 APG', difficulty: 'medel' },
    { title: 'LeBron James', definition: 'LAL #23 | USA | 20.9 PPG / 6.1 RPG / 7.2 APG', difficulty: 'lätt' },
    { title: 'Anthony Davis', definition: 'WAS #23 | USA | 20.4 PPG / 11.1 RPG / 2.8 APG', difficulty: 'lätt' },
    { title: 'Bam Adebayo', definition: 'MIA #13 | USA | 20.0 PPG / 10.0 RPG / 3.7 APG', difficulty: 'medel' },
    { title: 'James Harden', definition: 'LAC #1 | USA | 25.4 PPG / 5.5 RPG / 8.1 APG', difficulty: 'lätt' },
    { title: 'LaMelo Ball', definition: 'CHA #1 | USA | 19.7 PPG / 4.8 RPG / 7.1 APG', difficulty: 'medel' },
    { title: 'Jalen Duren', definition: 'DET #0 | USA | 19.5 PPG / 10.5 RPG / 2.8 APG', difficulty: 'medel' },
    { title: 'Franz Wagner', definition: 'ORL #22 | Tyskland | 20.4 PPG / 5.3 RPG / 4.1 APG', difficulty: 'medel' },
    { title: 'Jimmy Butler', definition: 'GSW #10 | USA | 20.0 PPG / 5.6 RPG / 4.9 APG', difficulty: 'lätt' },
  ],

  Golf: [
    // Klubbor & utrustning
    { title: 'Klubbtyper', definition: 'Drivers (trä), fairwaywoods, hybrider, järn (3–9), wedges (pitching, sand, lob) och putter.', difficulty: 'medel' },
    { title: 'Driver', definition: 'Långstav med stort klubbhuvud för tee-slag (längsta slagen).', difficulty: 'lätt' },
    { title: 'Putter', definition: 'Klubban som används på green för att rulla bollen i hål.', difficulty: 'lätt' },
    { title: 'Järn', definition: 'Klubbor med tunnare blad för kontroll och variation i längd.', difficulty: 'lätt' },
    { title: 'Wedge', definition: 'Kortare klubb med hög loft för höga, korta slag och närspel runt green.', difficulty: 'lätt' },
    { title: 'Hybrider', definition: 'Kombinerar egenskaper från trä och järn för lättare träffar och kontroll.', difficulty: 'medel' },
    // Banan
    { title: 'Tee', definition: 'Liten pinne eller plats där bollen placeras för det första slaget på ett hål.', difficulty: 'lätt' },
    { title: 'Green', definition: 'Det kortklippta området runt hålet där man puttar.', difficulty: 'lätt' },
    { title: 'Fairway', definition: 'Det välskötta gräsområdet mellan tee och green, designat för enklare slag.', difficulty: 'lätt' },
    { title: 'Rough', definition: 'Längre gräs vid sidan av fairway som gör nästa slag svårare.', difficulty: 'lätt' },
    { title: 'Hazard', definition: 'Vatten eller bunkrar (sand) som straffar eller påverkar spelstrategin.', difficulty: 'medel' },
    { title: 'Bunker', definition: 'Sandfylld grop på banan.', difficulty: 'lätt' },
    // Poäng & slag
    { title: 'Stroke', definition: 'Ett individuellt slag med klubban.', difficulty: 'lätt' },
    { title: 'Par', definition: 'Det förväntade antalet slag en duktig spelare bör använda för ett hål (3, 4 eller 5).', difficulty: 'lätt' },
    { title: 'Birdie', definition: 'Ett slag under par på ett hål (t.ex. 3 på ett par-4).', difficulty: 'lätt' },
    { title: 'Bogey', definition: 'Ett slag över par på ett hål (t.ex. 5 på ett par-4).', difficulty: 'lätt' },
    { title: 'Hole-in-one', definition: 'När bollen går i hål på ett enda slag från tee på ett par-3.', difficulty: 'lätt' },
    // Regler & tempo
    { title: 'Ready golf', definition: 'Regel för tempo: spela när du är redo istället för strikt turordning på casual ronder.', difficulty: 'medel' },
    { title: 'Droppning av boll (regel)', definition: 'Om bollen är ospelbar eller i en vattenhazard får du droppa enligt reglerna och ta eventuellt pliktslag.', difficulty: 'svår' },
    { title: 'Lättnad vid hinder (regel)', definition: 'Om föremål eller hinder påverkar ditt slag kan du ta lättnad utan plikt i en obstruerande situation enligt regelverket.', difficulty: 'svår' },
    // Handicap
    { title: 'Nybörjare (Hcp 54)', definition: 'Du får 54 extra slag. På en standardbana (par 72) förväntas du gå runt på 126 slag.', difficulty: 'medel' },
    { title: 'Medelgolfare (Hcp 18)', definition: 'Du får 18 extra slag, alltså ett extra slag per hål. Förväntas gå runt på 90 slag på en par-72-bana.', difficulty: 'medel' },
    { title: 'Proffs / Scratch (Hcp 0)', definition: 'Inga extra slag alls; förväntas gå runt på banans par (oftast 72 slag).', difficulty: 'medel' },
    { title: 'Beräkning av exakt handicap', definition: 'Genomsnittet av de 8 bästa av dina 20 senaste registrerade rundor.', difficulty: 'svår' },
    { title: 'Världshandicapsystemet (WHS)', definition: 'Det globala systemet som gör att golfare oavsett skicklighet kan tävla mot varandra på lika villkor.', difficulty: 'medel' },
    // Majors
    { title: 'The Masters Tournament', definition: 'Årets första herrmajor. Spelas i april på Augusta National – vinnaren får den gröna kavajen.', difficulty: 'medel' },
    { title: 'PGA Championship', definition: 'Årets andra herrmajor. Spelas i maj på skiftande banor i USA, arrangeras av PGA of America.', difficulty: 'medel' },
    { title: 'U.S. Open', definition: 'Årets tredje herrmajor. Spelas i juni på extremt svåra amerikanska banor med fokus på precision.', difficulty: 'medel' },
    { title: 'The Open Championship', definition: 'British Open – den äldsta herrmajoren. Spelas i juli på tuffa, blåsiga linksbanor i Storbritannien.', difficulty: 'medel' },
    { title: 'The Players Championship', definition: 'Ofta kallad "den femte majorn". Spelas i mars på TPC Sawgrass i Florida – störst prispott.', difficulty: 'svår' },
  ],
};
