import { fotboll } from './fotbollData';
// Sport-data: Basket (NBA 2025-26) och Golf

export const sport = {
  Basket: [
    { title: 'Coby White', definition: 'CHI #0 | USA | 18.6 PPG / 3.6 RPG / 4.7 APG', difficulty: 'lätt', stale: true },
    { title: 'Josh Giddey', definition: 'CHI #3 | Australien | 17.0 PPG / 8.3 RPG / 9.1 APG', difficulty: 'medel', stale: true },
    { title: 'Collin Sexton', definition: 'CHI #2 | USA | 17.6 PPG / 2.8 RPG / 3.5 APG', difficulty: 'medel', stale: true },
    { title: 'Matas Buzelis', definition: 'CHI #14 | USA/Litauen | 16.4 PPG / 5.7 RPG / 2.2 APG', difficulty: 'medel', stale: true },
    { title: 'Nick Richards', definition: 'CHI #13 | Jamaica | 8.5 PPG / 7.6 RPG / 1.0 APG', difficulty: 'medel', stale: true },
    { title: 'Jalen Smith', definition: 'CHI #25 | USA | 8.0 PPG / 6.7 RPG / 1.3 APG', difficulty: 'medel', stale: true },
    { title: 'Tre Jones', definition: 'CHI #30 | USA | 8.4 PPG / 2.9 RPG / 5.5 APG', difficulty: 'medel', stale: true },
    { title: 'Jaden Ivey', definition: 'CHI #31 | USA | 11.2 PPG / 3.4 RPG / 4.0 APG', difficulty: 'medel', stale: true },
    { title: 'Evan Mobley', definition: 'CLE #4 | USA | 18.3 PPG / 9.1 RPG / 3.4 APG', difficulty: 'lätt', stale: true },
    { title: 'Darius Garland', definition: 'CLE #10 | USA | 16.8 PPG / 3.5 RPG / 6.9 APG', difficulty: 'medel', stale: true },
    { title: 'Jarrett Allen', definition: 'CLE #1 | USA | 11.2 PPG / 8.1 RPG / 1.8 APG', difficulty: 'medel', stale: true },
    { title: 'Lonzo Ball', definition: 'CLE #7 | USA | 9.4 PPG / 4.2 RPG / 5.1 APG', difficulty: 'medel', stale: true },
    { title: 'Dennis Schröder', definition: 'CLE #24 | Tyskland | 8.2 PPG / 2.3 RPG / 4.3 APG', difficulty: 'medel', stale: true },
    { title: 'Jalen Williams', definition: 'OKC #8 | USA | 17.1 PPG / 4.6 RPG / 5.5 APG', difficulty: 'medel', stale: true },
    { title: 'Chet Holmgren', definition: 'OKC #7 | USA | 17.1 PPG / 8.9 RPG / 1.9 APG', difficulty: 'medel', stale: true },
    { title: 'Isaiah Hartenstein', definition: 'OKC #55 | Tyskland | 11.4 PPG / 9.4 RPG / 3.1 APG', difficulty: 'medel', stale: true },
    { title: 'Luguentz Dort', definition: 'OKC #5 | Kanada | 11.2 PPG / 3.4 RPG / 1.8 APG', difficulty: 'medel', stale: true },
    { title: 'Cason Wallace', definition: 'OKC #4 | USA | 10.8 PPG / 3.2 RPG / 2.9 APG', difficulty: 'medel', stale: true },
    { title: 'Ausar Thompson', definition: 'DET #9 | USA | 14.8 PPG / 5.7 RPG / 3.1 APG', difficulty: 'medel', stale: true },
    { title: 'Tobias Harris', definition: 'DET #12 | USA | 13.3 PPG / 5.1 RPG / 2.4 APG', difficulty: 'medel', stale: true },
    { title: 'Caris LeVert', definition: 'DET #8 | USA | 12.1 PPG / 3.0 RPG / 3.5 APG', difficulty: 'medel', stale: true },
    { title: 'Isaiah Stewart', definition: 'DET #28 | USA | 11.4 PPG / 6.9 RPG / 2.0 APG', difficulty: 'medel', stale: true },
    { title: 'Ron Holland II', definition: 'DET #5 | USA | 10.2 PPG / 4.8 RPG / 2.3 APG', difficulty: 'medel', stale: true },
    { title: 'Bennedict Mathurin', definition: 'IND #00 | Kanada | 17.8 PPG / 4.2 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'Andrew Nembhard', definition: 'IND #2 | Kanada | 16.9 PPG / 4.1 RPG / 7.7 APG', difficulty: 'medel', stale: true },
    { title: 'Tyrese Haliburton', definition: 'IND #0 | USA | 14.2 PPG / 3.8 RPG / 8.4 APG', difficulty: 'medel', stale: true },
    { title: 'Aaron Nesmith', definition: 'IND #23 | USA | 13.8 PPG / 4.9 RPG / 1.8 APG', difficulty: 'medel', stale: true },
    { title: 'Ivica Zubac', definition: 'IND #40 | Kroatien | 11.6 PPG / 7.2 RPG / 2.2 APG', difficulty: 'medel', stale: true },
    { title: 'Kevin Porter Jr.', definition: 'MIL #13 | USA | 17.4 PPG / 4.1 RPG / 7.4 APG', difficulty: 'medel', stale: true },
    { title: 'Ryan Rollins', definition: 'MIL #6 | USA | 17.3 PPG / 3.8 RPG / 5.6 APG', difficulty: 'medel', stale: true },
    { title: 'Kyle Kuzma', definition: 'MIL #4 | USA | 14.2 PPG / 5.8 RPG / 2.9 APG', difficulty: 'medel', stale: true },
    { title: 'Myles Turner', definition: 'MIL #31 | USA | 12.8 PPG / 5.9 RPG / 1.7 APG', difficulty: 'medel', stale: true },
    { title: 'A.J. Green', definition: 'MIL #9 | USA | 11.4 PPG / 2.8 RPG / 1.9 APG', difficulty: 'medel', stale: true },
    { title: 'Bobby Portis', definition: 'MIL #10 | USA | 10.3 PPG / 6.4 RPG / 1.4 APG', difficulty: 'medel', stale: true },
    { title: 'Dyson Daniels', definition: 'ATL #5 | Australien | 14.6 PPG / 6.8 RPG / 3.8 APG', difficulty: 'medel', stale: true },
    { title: 'Nickeil Alexander-Walker', definition: 'ATL #7 | Kanada | 20.8 PPG / 3.9 RPG / 3.5 APG', difficulty: 'lätt', stale: true },
    { title: 'Onyeka Okongwu', definition: 'ATL #17 | USA | 11.4 PPG / 7.6 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'CJ McCollum', definition: 'ATL #3 | USA | 18.8 PPG / 3.1 RPG / 4.2 APG', difficulty: 'lätt', stale: true },
    { title: 'Brandon Miller', definition: 'CHA #24 | USA | 20.3 PPG / 5.2 RPG / 3.3 APG', difficulty: 'lätt', stale: true },
    { title: 'Kon Knueppel', definition: 'CHA #7 | USA | 18.5 PPG / 5.3 RPG / 3.4 APG', difficulty: 'lätt', stale: true },
    { title: 'Miles Bridges', definition: 'CHA #0 | USA | 17.2 PPG / 5.9 RPG / 2.8 APG', difficulty: 'medel', stale: true },
    { title: 'Tyler Herro', definition: 'MIA #14 | USA | 21.0 PPG / 4.1 RPG / 4.0 APG', difficulty: 'lätt', stale: true },
    { title: 'Norman Powell', definition: 'MIA #24 | USA | 21.7 PPG / 3.4 RPG / 2.1 APG', difficulty: 'lätt', stale: true },
    { title: 'Andrew Wiggins', definition: 'MIA #22 | Kanada | 14.8 PPG / 4.9 RPG / 2.3 APG', difficulty: 'medel', stale: true },
    { title: 'Davion Mitchell', definition: 'MIA #4 | USA | 12.3 PPG / 2.8 RPG / 6.6 APG', difficulty: 'medel', stale: true },
    { title: 'Jaime Jaquez Jr.', definition: 'MIA #11 | USA | 11.2 PPG / 4.8 RPG / 4.6 APG', difficulty: 'medel', stale: true },
    { title: 'Kel\'el Ware', definition: 'MIA #7 | USA | 10.4 PPG / 9.1 RPG / 1.4 APG', difficulty: 'medel', stale: true },
    { title: 'Desmond Bane', definition: 'ORL #22 | USA | 20.5 PPG / 4.0 RPG / 4.2 APG', difficulty: 'lätt', stale: true },
    { title: 'Jalen Suggs', definition: 'ORL #4 | USA | 13.7 PPG / 3.8 RPG / 5.5 APG', difficulty: 'medel', stale: true },
    { title: 'Anthony Black', definition: 'ORL #0 | USA | 15.1 PPG / 4.9 RPG / 3.4 APG', difficulty: 'medel', stale: true },
    { title: 'Wendell Carter Jr.', definition: 'ORL #34 | USA | 11.2 PPG / 7.4 RPG / 2.3 APG', difficulty: 'medel', stale: true },
    { title: 'Alex Sarr', definition: 'WAS #20 | Frankrike | 16.3 PPG / 7.4 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'Trae Young', definition: 'WAS #3 | USA | 15.2 PPG / 2.0 RPG / 6.2 APG', difficulty: 'medel', stale: true },
    { title: 'D\'Angelo Russell', definition: 'WAS #5 | USA | 13.4 PPG / 3.1 RPG / 5.8 APG', difficulty: 'medel', stale: true },
    { title: 'Bilal Coulibaly', definition: 'WAS #0 | Frankrike | 12.1 PPG / 4.8 RPG / 2.9 APG', difficulty: 'medel', stale: true },
    { title: 'Kyshawn George', definition: 'WAS #18 | USA/Kanada | 14.8 PPG / 4.2 RPG / 3.3 APG', difficulty: 'medel', stale: true },
    { title: 'Jaden Hardy', definition: 'WAS #8 | USA | 12.6 PPG / 2.8 RPG / 2.4 APG', difficulty: 'medel', stale: true },
    { title: 'Tre Johnson', definition: 'WAS #12 | USA | 11.8 PPG / 2.3 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'Aaron Gordon', definition: 'DEN #50 | USA | 16.2 PPG / 5.8 RPG / 2.7 APG', difficulty: 'medel', stale: true },
    { title: 'Cameron Johnson', definition: 'DEN #23 | USA | 14.6 PPG / 4.2 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'Christian Braun', definition: 'DEN #0 | USA | 12.8 PPG / 4.1 RPG / 2.3 APG', difficulty: 'medel', stale: true },
    { title: 'Julius Randle', definition: 'MIN #30 | USA | 21.1 PPG / 7.8 RPG / 5.0 APG', difficulty: 'lätt', stale: true },
    { title: 'Jaden McDaniels', definition: 'MIN #3 | USA | 14.8 PPG / 4.8 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'Rudy Gobert', definition: 'MIN #27 | Frankrike | 11.2 PPG / 11.5 RPG / 2.4 APG', difficulty: 'medel', stale: true },
    { title: 'Donte DiVincenzo', definition: 'MIN #0 | USA | 12.4 PPG / 3.9 RPG / 3.8 APG', difficulty: 'medel', stale: true },
    { title: 'Naz Reid', definition: 'MIN #11 | USA | 10.8 PPG / 5.2 RPG / 1.9 APG', difficulty: 'medel', stale: true },
    { title: 'Shaedon Sharpe', definition: 'POR #17 | Kanada | 20.8 PPG / 3.6 RPG / 2.8 APG', difficulty: 'lätt', stale: true },
    { title: 'Jerami Grant', definition: 'POR #9 | USA | 18.6 PPG / 4.8 RPG / 2.4 APG', difficulty: 'lätt', stale: true },
    { title: 'Donovan Clingan', definition: 'POR #23 | USA | 13.2 PPG / 11.6 RPG / 1.8 APG', difficulty: 'medel', stale: true },
    { title: 'Jrue Holiday', definition: 'POR #12 | USA | 11.4 PPG / 4.1 RPG / 6.1 APG', difficulty: 'medel', stale: true },
    { title: 'Toumani Camara', definition: 'POR #33 | Frankrike | 10.2 PPG / 4.7 RPG / 2.4 APG', difficulty: 'medel', stale: true },
    { title: 'Keyonte George', definition: 'UTA #3 | USA | 23.6 PPG / 3.8 RPG / 6.1 APG', difficulty: 'lätt', stale: true },
    { title: 'Jaren Jackson Jr.', definition: 'UTA #13 | USA | 22.3 PPG / 6.1 RPG / 2.1 APG', difficulty: 'lätt', stale: true },
    { title: 'Walker Kessler', definition: 'UTA #24 | USA | 12.8 PPG / 10.8 RPG / 1.4 APG', difficulty: 'medel', stale: true },
    { title: 'Isaiah Collier', definition: 'UTA #0 | USA | 10.4 PPG / 3.1 RPG / 7.2 APG', difficulty: 'medel', stale: true },
    { title: 'Jusuf Nurkić', definition: 'UTA #27 | Bosnien | 9.8 PPG / 10.4 RPG / 2.6 APG', difficulty: 'medel', stale: true },
    { title: 'Draymond Green', definition: 'GSW #23 | USA | 7.8 PPG / 6.4 RPG / 5.5 APG', difficulty: 'medel', stale: true },
    { title: 'Kristaps Porziņģis', definition: 'GSW #7 | Lettland | 16.1 PPG / 5.8 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'De\'Anthony Melton', definition: 'GSW #8 | USA | 12.4 PPG / 3.8 RPG / 3.2 APG', difficulty: 'medel', stale: true },
    { title: 'Brandin Podziemski', definition: 'GSW #2 | USA | 11.6 PPG / 4.9 RPG / 3.4 APG', difficulty: 'medel', stale: true },
    { title: 'Bradley Beal', definition: 'LAC #0 | USA | 18.2 PPG / 4.1 RPG / 3.9 APG', difficulty: 'lätt', stale: true },
    { title: 'Ivica Zubac (LAC)', definition: 'LAC #40 | Kroatien | 14.4 PPG / 11.0 RPG / 2.4 APG', difficulty: 'medel', stale: true },
    { title: 'John Collins', definition: 'LAC #20 | USA | 12.8 PPG / 6.2 RPG / 2.1 APG', difficulty: 'medel', stale: true },
    { title: 'Kris Dunn', definition: 'LAC #8 | USA | 9.4 PPG / 3.8 RPG / 3.6 APG', difficulty: 'medel', stale: true },
    { title: 'Deandre Ayton', definition: 'LAL #22 | Bahamas | 13.8 PPG / 8.0 RPG / 2.2 APG', difficulty: 'medel', stale: true },
    { title: 'Marcus Smart', definition: 'LAL #36 | USA | 10.4 PPG / 3.6 RPG / 6.2 APG', difficulty: 'medel', stale: true },
    { title: 'Rui Hachimura', definition: 'LAL #28 | Japan | 13.1 PPG / 4.4 RPG / 1.6 APG', difficulty: 'medel', stale: true },
    { title: 'Dillon Brooks', definition: 'PHX #3 | Kanada | 20.2 PPG / 4.2 RPG / 2.8 APG', difficulty: 'lätt', stale: true },
    { title: 'Jalen Green', definition: 'PHX #4 | USA | 17.8 PPG / 3.4 RPG / 3.1 APG', difficulty: 'medel', stale: true },
    { title: 'Grayson Allen', definition: 'PHX #8 | USA | 14.6 PPG / 3.2 RPG / 3.8 APG', difficulty: 'medel', stale: true },
    { title: 'Mark Williams', definition: 'PHX #5 | USA | 11.4 PPG / 8.0 RPG / 1.8 APG', difficulty: 'medel', stale: true },
    { title: 'Zach LaVine', definition: 'SAC #8 | USA | 19.2 PPG / 2.8 RPG / 2.3 APG', difficulty: 'lätt', stale: true },
    { title: 'DeMar DeRozan', definition: 'SAC #10 | USA | 18.4 PPG / 3.8 RPG / 4.2 APG', difficulty: 'lätt', stale: true },
    { title: 'Domantas Sabonis', definition: 'SAC #11 | Litauen | 15.8 PPG / 11.4 RPG / 4.1 APG', difficulty: 'medel', stale: true },
    { title: 'Russell Westbrook', definition: 'SAC #0 | USA | 15.2 PPG / 5.1 RPG / 6.7 APG', difficulty: 'medel', stale: true },
    { title: 'Keegan Murray', definition: 'SAC #13 | USA | 14.0 PPG / 5.7 RPG / 1.7 APG', difficulty: 'medel', stale: true },
    { title: 'Malik Monk', definition: 'SAC #1 | USA | 12.5 PPG / 1.9 RPG / 3.0 APG', difficulty: 'medel', stale: true },
    // ---- LAG (titel = lag, definition = tränare + nyckelspelare) ----
    { title: 'Chicago Bulls', definition: 'HC: Billy Donovan. Nyckelspelare: Coby White, Josh Giddey, Collin Sexton, Matas Buzelis.', difficulty: 'medel' },
    { title: 'Cleveland Cavaliers', definition: 'HC: Kenny Atkinson. Nyckelspelare: Donovan Mitchell, James Harden, Evan Mobley, Darius Garland.', difficulty: 'medel' },
    { title: 'Detroit Pistons', definition: 'HC: J.B. Bickerstaff. Nyckelspelare: Cade Cunningham, Jalen Duren, Ausar Thompson, Tobias Harris.', difficulty: 'medel' },
    { title: 'Indiana Pacers', definition: 'HC: Rick Carlisle. Nyckelspelare: Pascal Siakam, Bennedict Mathurin, Andrew Nembhard, Tyrese Haliburton.', difficulty: 'medel' },
    { title: 'Milwaukee Bucks', definition: 'HC: Doc Rivers. Nyckelspelare: Giannis Antetokounmpo, Kevin Porter Jr., Kyle Kuzma, Myles Turner.', difficulty: 'medel' },
    { title: 'Atlanta Hawks', definition: 'HC: Quin Snyder. Nyckelspelare: Jalen Johnson, Dyson Daniels, Nickeil Alexander-Walker, CJ McCollum.', difficulty: 'medel' },
    { title: 'Charlotte Hornets', definition: 'HC: Charles Lee. Nyckelspelare: LaMelo Ball, Brandon Miller, Kon Knueppel, Miles Bridges.', difficulty: 'medel' },
    { title: 'Miami Heat', definition: 'HC: Erik Spoelstra. Nyckelspelare: Tyler Herro, Bam Adebayo, Norman Powell, Andrew Wiggins.', difficulty: 'medel' },
    { title: 'Orlando Magic', definition: 'HC: Jamahl Mosley. Nyckelspelare: Paolo Banchero, Franz Wagner, Desmond Bane, Jalen Suggs.', difficulty: 'medel' },
    { title: 'Washington Wizards', definition: 'HC: Brian Keefe. Nyckelspelare: Alex Sarr, Trae Young, Anthony Davis, Bilal Coulibaly.', difficulty: 'medel' },
    { title: 'Denver Nuggets', definition: 'HC: David Adelman. Nyckelspelare: Nikola Jokić, Jamal Murray, Aaron Gordon, Cameron Johnson.', difficulty: 'medel' },
    { title: 'Minnesota Timberwolves', definition: 'HC: Chris Finch. Nyckelspelare: Anthony Edwards, Julius Randle, Jaden McDaniels, Rudy Gobert.', difficulty: 'medel' },
    { title: 'Oklahoma City Thunder', definition: 'HC: Mark Daigneault. Nyckelspelare: Shai Gilgeous-Alexander, Jalen Williams, Chet Holmgren, Isaiah Hartenstein.', difficulty: 'medel' },
    { title: 'Portland Trail Blazers', definition: 'HC: Chauncey Billups. Nyckelspelare: Deni Avdija, Shaedon Sharpe, Jerami Grant, Donovan Clingan.', difficulty: 'medel' },
    { title: 'Utah Jazz', definition: 'HC: Will Hardy. Nyckelspelare: Lauri Markkanen, Keyonte George, Jaren Jackson Jr., Walker Kessler.', difficulty: 'medel' },
    { title: 'Golden State Warriors', definition: 'HC: Steve Kerr. Nyckelspelare: Stephen Curry, Jimmy Butler, Draymond Green, Kristaps Porziņģis.', difficulty: 'medel' },
    { title: 'LA Clippers', definition: 'HC: Tyronn Lue. Nyckelspelare: Kawhi Leonard, James Harden, Ivica Zubac, John Collins.', difficulty: 'medel' },
    { title: 'Los Angeles Lakers', definition: 'HC: JJ Redick. Nyckelspelare: Luka Dončić, LeBron James, Austin Reaves, Deandre Ayton.', difficulty: 'medel' },
    { title: 'Phoenix Suns', definition: 'HC: Mike Budenholzer. Nyckelspelare: Devin Booker, Dillon Brooks, Jalen Green, Mark Williams.', difficulty: 'medel' },
    { title: 'Sacramento Kings', definition: 'HC: Doug Christie. Nyckelspelare: Zach LaVine, DeMar DeRozan, Domantas Sabonis, Russell Westbrook.', difficulty: 'medel' },

    // ---- STJÄRNSPELARE (titel = spelare, definition = lag, nr, nation, stats) ----
    { title: 'Shai Gilgeous-Alexander', definition: 'OKC #2 | Kanada | 31.1 PPG / 5.4 RPG / 6.6 APG', difficulty: 'lätt' },
    { title: 'Luka Dončić', definition: 'LAL #77 | Slovenien | 33.5 PPG / 7.7 RPG / 8.3 APG', difficulty: 'lätt' },
    { title: 'Nikola Jokić', definition: 'DEN #15 | Serbien | 27.7 PPG / 12.9 RPG / 10.7 APG (trippeldubbel-snitt)', difficulty: 'lätt' },
    { title: 'Anthony Edwards', definition: 'MIN #5 | USA | 28.8 PPG / 5.4 RPG / 3.7 APG', difficulty: 'lätt' },
    { title: 'Giannis Antetokounmpo', definition: 'MIL #34 | Grekland | 27.6 PPG / 9.8 RPG / 5.4 APG', difficulty: 'lätt' },
    { title: 'Donovan Mitchell', definition: 'CLE #45 | USA | 27.9 PPG / 5.1 RPG / 5.7 APG', difficulty: 'lätt' },
    { title: 'Kawhi Leonard', definition: 'LAC #2 | USA | 27.9 PPG / 6.4 RPG / 3.6 APG', difficulty: 'lätt' },
    { title: 'Stephen Curry', definition: 'GSW #30 | USA | 26.6 PPG / 3.6 RPG / 4.7 APG', difficulty: 'lätt' },
    { title: 'Lauri Markkanen', definition: 'UTA #11 | Finland | 26.7 PPG / 8.4 RPG / 2.8 APG', difficulty: 'lätt' },
    { title: 'Devin Booker', definition: 'PHX #1 | USA | 26.1 PPG / 3.9 RPG / 6.0 APG', difficulty: 'lätt' },
    { title: 'Jamal Murray', definition: 'DEN #27 | Kanada | 25.4 PPG / 4.8 RPG / 7.1 APG', difficulty: 'lätt' },
    { title: 'Cade Cunningham', definition: 'DET #2 | USA | 23.9 PPG / 5.5 RPG / 9.9 APG', difficulty: 'lätt' },
    { title: 'Deni Avdija', definition: 'POR #8 | Israel | 24.2 PPG / 6.9 RPG / 6.7 APG', difficulty: 'medel' },
    { title: 'Pascal Siakam', definition: 'IND #43 | Kamerun | 24.0 PPG / 6.6 RPG / 3.8 APG', difficulty: 'medel' },
    { title: 'Austin Reaves', definition: 'LAL #15 | USA | 23.3 PPG / 4.2 RPG / 5.5 APG', difficulty: 'medel' },
    { title: 'Jalen Johnson', definition: 'ATL #1 | USA | 22.5 PPG / 10.3 RPG / 7.9 APG', difficulty: 'medel' },
    { title: 'Paolo Banchero', definition: 'ORL #5 | USA | 22.3 PPG / 8.4 RPG / 5.1 APG', difficulty: 'medel' },
    { title: 'LeBron James', definition: 'LAL #23 | USA | 20.9 PPG / 6.1 RPG / 7.2 APG', difficulty: 'lätt' },
    { title: 'Anthony Davis', definition: 'WAS #23 | USA | 20.4 PPG / 11.1 RPG / 2.8 APG', difficulty: 'lätt' },
    { title: 'Bam Adebayo', definition: 'MIA #13 | USA | 20.0 PPG / 10.0 RPG / 3.7 APG', difficulty: 'medel' },
    { title: 'James Harden', definition: 'LAC #1 | USA | 25.4 PPG / 5.5 RPG / 8.1 APG', difficulty: 'lätt' },
    { title: 'LaMelo Ball', definition: 'CHA #1 | USA | 19.7 PPG / 4.8 RPG / 7.1 APG', difficulty: 'medel' },
    { title: 'Jalen Duren', definition: 'DET #0 | USA | 19.5 PPG / 10.5 RPG / 2.8 APG', difficulty: 'medel' },
    { title: 'Franz Wagner', definition: 'ORL #22 | Tyskland | 20.4 PPG / 5.3 RPG / 4.1 APG', difficulty: 'medel' },
    { title: 'Jimmy Butler', definition: 'GSW #10 | USA | 20.0 PPG / 5.6 RPG / 4.9 APG', difficulty: 'lätt' },
  ],

  Golf: [
    // Klubbor & utrustning
    { title: 'Klubbtyper', definition: 'Drivers (trä), fairwaywoods, hybrider, järn (3–9), wedges (pitching, sand, lob) och putter.', difficulty: 'medel' },
    { title: 'Driver', definition: 'Långstav med stort klubbhuvud för tee-slag (längsta slagen).', difficulty: 'lätt' },
    { title: 'Putter', definition: 'Klubban som används på green för att rulla bollen i hål.', difficulty: 'lätt' },
    { title: 'Järn', definition: 'Klubbor med tunnare blad för kontroll och variation i längd.', difficulty: 'lätt' },
    { title: 'Wedge', definition: 'Kortare klubb med hög loft för höga, korta slag och närspel runt green.', difficulty: 'lätt' },
    { title: 'Hybrider', definition: 'Kombinerar egenskaper från trä och järn för lättare träffar och kontroll.', difficulty: 'medel' },
    // Banan
    { title: 'Tee', definition: 'Liten pinne eller plats där bollen placeras för det första slaget på ett hål.', difficulty: 'lätt' },
    { title: 'Green', definition: 'Det kortklippta området runt hålet där man puttar.', difficulty: 'lätt' },
    { title: 'Fairway', definition: 'Det välskötta gräsområdet mellan tee och green, designat för enklare slag.', difficulty: 'lätt' },
    { title: 'Rough', definition: 'Längre gräs vid sidan av fairway som gör nästa slag svårare.', difficulty: 'lätt' },
    { title: 'Hazard', definition: 'Vatten eller bunkrar (sand) som straffar eller påverkar spelstrategin.', difficulty: 'medel' },
    { title: 'Bunker', definition: 'Sandfylld grop på banan.', difficulty: 'lätt' },
    // Poäng & slag
    { title: 'Stroke', definition: 'Ett individuellt slag med klubban.', difficulty: 'lätt' },
    { title: 'Par', definition: 'Det förväntade antalet slag en duktig spelare bör använda för ett hål (3, 4 eller 5).', difficulty: 'lätt' },
    { title: 'Birdie', definition: 'Ett slag under par på ett hål (t.ex. 3 på ett par-4).', difficulty: 'lätt' },
    { title: 'Bogey', definition: 'Ett slag över par på ett hål (t.ex. 5 på ett par-4).', difficulty: 'lätt' },
    { title: 'Hole-in-one', definition: 'När bollen går i hål på ett enda slag från tee på ett par-3.', difficulty: 'lätt' },
    // Regler & tempo
    { title: 'Ready golf', definition: 'Regel för tempo: spela när du är redo istället för strikt turordning på casual ronder.', difficulty: 'medel' },
    { title: 'Droppning av boll (regel)', definition: 'Om bollen är ospelbar eller i en vattenhazard får du droppa enligt reglerna och ta eventuellt pliktslag.', difficulty: 'svår' },
    { title: 'Lättnad vid hinder (regel)', definition: 'Om föremål eller hinder påverkar ditt slag kan du ta lättnad utan plikt i en obstruerande situation enligt regelverket.', difficulty: 'svår' },
    // Handicap
    { title: 'Nybörjare (Hcp 54)', definition: 'Du får 54 extra slag. På en standardbana (par 72) förväntas du gå runt på 126 slag.', difficulty: 'medel' },
    { title: 'Medelgolfare (Hcp 18)', definition: 'Du får 18 extra slag, alltså ett extra slag per hål. Förväntas gå runt på 90 slag på en par-72-bana.', difficulty: 'medel' },
    { title: 'Proffs / Scratch (Hcp 0)', definition: 'Inga extra slag alls; förväntas gå runt på banans par (oftast 72 slag).', difficulty: 'medel' },
    { title: 'Beräkning av exakt handicap', definition: 'Genomsnittet av de 8 bästa av dina 20 senaste registrerade rundor.', difficulty: 'svår' },
    { title: 'Världshandicapsystemet (WHS)', definition: 'Det globala systemet som gör att golfare oavsett skicklighet kan tävla mot varandra på lika villkor.', difficulty: 'medel' },
    // Majors
    { title: 'The Masters Tournament', definition: 'Årets första herrmajor. Spelas i april på Augusta National – vinnaren får den gröna kavajen.', difficulty: 'medel' },
    { title: 'PGA Championship', definition: 'Årets andra herrmajor. Spelas i maj på skiftande banor i USA, arrangeras av PGA of America.', difficulty: 'medel' },
    { title: 'U.S. Open', definition: 'Årets tredje herrmajor. Spelas i juni på extremt svåra amerikanska banor med fokus på precision.', difficulty: 'medel' },
    { title: 'The Open Championship', definition: 'British Open – den äldsta herrmajoren. Spelas i juli på tuffa, blåsiga linksbanor i Storbritannien.', difficulty: 'medel' },
    { title: 'The Players Championship', definition: 'Ofta kallad "den femte majorn". Spelas i mars på TPC Sawgrass i Florida – störst prispott.', difficulty: 'svår' },
  ],
  ...fotboll,
};
